
import { register } from '../core.js';

const lookup = "AAAC6IkZAh4YbRoCI3VJWDdGRWUEcreBJzcUJjhYR5OFY3glJ4U1Y0MzQ3VqZDhlRFZ2RmMjIiVXZZXDZDdZRncTYxS1RCUEWHBDFhgCB1gSAp0BCMMypwcpigIBAShzBqIIBB4FCYcMDdADATOMDZUBYycCV+sGEgEbAQMFCgYd5wHEEAsHG48BDUMUNjsItgEuBAJkAQECCjISEi7xC/mSAQErGQHvAgwbGaQEuAIYBRHijwEJFxAEAlkCHue9HE3P5flclln/0Yyfc9FJTJpNPKl3maxL6/CSoByzZODgovIPXv/WoADzGTUgwJTLtnRxMT/0dCh0x2vM3dTIkYNWF3M1A+E23IzJMlZKCRIEDyOAwhQt0x0cHkt13yRVHdGJ7mA8Ayl3hSsuQyymCdwww6Kj+tsRIzQL15P8Be8r0FYjqXv/gHsNo8r18bi/5pQb+Bek0o3MjFXcl87lRCZNXTuA0PL68O1CEpCBvvqX4TxZ53h2GCU78QQ3ttHd6BuamgzSM/TeF/WX7Xci3sJe/q5aK40GcRxCTr/fl6FGjzpZlfV0N2JE4AgMJ0EHmNZvJLhtQfdpG004dmAExOCapb++uCh/OIpWK/qcuFC+8nrdArGR+EU30X1814HVb5Hxi9jEvpIPGH5p/7YtOOpLRhkGzR9cy/rz8kH/MTa9bOhp9b2SltDuq5iFRVO0E/Jb5vKmYdsrxqew/U3YZfAMxDR1v/lyohi43F0Wz2Ip+0bsByDIFhUmWBJ/4qkJ0xArrEh+JCmhFC4PRaEN3qXCs6OHI4ki5XDs2iIzI8/+fO3vvP0AlU8MkvcF3FTVIUdjTxE91NCgdywZZMSJjh0xkDUIPCjMBfW6LW+RRZiJHm5c2H1vc/Fao1PR5oRWICEQgAFQ6Ila+oaNYXXVTlBCi7HLwaRCKEutcMPj5er77huZKrk6+YfK2nZfhSU64BAR13YfE9n2BsP0ToCQKAAgEAKIACgSACcIAAAAAAMAAAALZmxhZy0wMS5zdmcAAAALZmxhZy0wMi5zdmcAAAALZmxhZy0wMy5zdmf/////AAAAAgAAAIgKGmqlARlAARhZIZVEBCBKZKioCCYlAZJVAQBQYhlEhUYkKIRSQpRlAAQhEVSVWWolGmGYRoEQAJAlRWREmYmkUJEKJoRQGBQJgBSJYGloFKhGgZUWQIVBFoAYARpQgpgKSFViGZFWAWQopaGKZSUBUElFFBUEoUWZlQFqkQWUAWpJKZhYJgYBAAAAAA==";

const chunks = {
  "flag-01.svg": new URL("./flag-01.svg", import.meta.url).href,
  "flag-02.svg": new URL("./flag-02.svg", import.meta.url).href,
  "flag-03.svg": new URL("./flag-03.svg", import.meta.url).href
};

register('flag', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
