
import { register } from '../core.js';

const lookup = "AAAC7okZAh4YbRqr+NkjWDdJZTRFI1JXZlV1UIV6NUdkNlQ0MzR0RVQyRGdhRzZDY5h4Z7ZTQzRiVFU2hERRhDQ5ikRHVXUIWHblCB8KDwEXCwE8FwQYEiUQGRQcnAWKG/QBpAEHBQojBAEQAgcHEgPBATsLCQcQAQqaARQfAagBDg8NAfcB+QO7D/sBhgGaAnOwAs1hBTIIBAYCIxEMGQi4AQXGBhIDDiWQBQED+AzcEswBHAXxARQnIhzTAu8GAlkCHkIsGMeA8YwooLi90P2Wb0uPhZ/UvYlpWiUPFihBkm9NEDGR4DrohTg12pr2Hfr+zBAgKSfRxN6LHeCX4dPAM4FTtPIpnFupCB97C6Eo3H5iBbNQGwUSfN3LdMyXyjRN6kaJHE3wIgziG/9kkzukO9SL2r4gKivo0MhVe87DRdb1me7jHPNL3uaS9/XLoTrf0VbbZEwjLr4mFES5h1a4df+GRo3ePCvo59Km9RT/TkERlKKiktzs8gOjlNe/xu44pVzNUPr0dr2XX/X9kdzluNchEXQNwxj0JNUoWc8w0YA9IQ+8+lhJxCtwXchUv9AMhZHE/BlNDL6K+OEt4HNLFsLLNB9CNrZQGw3/K16Z0i1awhClcCsA7UJT5XPvmNf5ExGabQZxN8+H1SUHmnN3HB6geGCDGDYjADhCVazgByMt5RME+mES8WmsmLhymmLdwXyYJPpKPI2tRlbZqUi4XETxTyRepM+AVthNBOXYdaE8Iol/lZX7zO3w+3f3d8mQVn8xR4lxMsMBjCv0d7NljEUiepZPsXaJutXyow9ZM7DEpvJ25nYbQ1mQJhlutvIF+k50by51CI3sdOeSP9COXX6XfaO/8afzsUHv3PW+F2HtCVrbv3340QyikW8SCd3qD/4GAjc88NFLKTVrIxzWRdMXyjEjwmw6owm2Ga4gXNGE3N/m/2MdoOCBA6seF6k3aQYVgAT56yz5RTXY8u5gTgIFEggoBEMAAEBABAIAAAAAAAMAAAALZmxhZy0wMS5zdmcAAAALZmxhZy0wMi5zdmcAAAALZmxhZy0wMy5zdmf/////AAAAAgAAAIglWWaYWhGFBUQZIVFVaCQIJWBQGKYaWIEEoQVVQCBmGQYgWWgCCZAJVplEgFAGFEpVJAEgWkCWYSBEgQSgCRQCBhpAEBaUamUlWZKIiKiVBaoigBhVRJFkaphgFFUiCREiWAJkQimFBmZaGQQQIRVAkkQpFRpZViJaaWkkEFgEUZGFGYgAUCkIAAAAAA==";

const chunks = {
  "flag-01.svg": new URL("./flag-01.svg", import.meta.url).href,
  "flag-02.svg": new URL("./flag-02.svg", import.meta.url).href,
  "flag-03.svg": new URL("./flag-03.svg", import.meta.url).href
};

register('flag', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
