
import { register } from '../core.js';

const lookup = "AAAB9IkZAWgYSBr8xysLWCSRdTUoNlxFNmcjeGNlVGJEhUYmJlZ3eoSGpXMzZjJBY2MkIYNYSuUKDiw/vwUBoAEFjsoDGhMDOggBQQRvEmkCJgQ8AQEDAgJBPQsTAVJZC60CU8BRTxvvAsUC0gEL8h0KOwEGbRYDEwoDAmoMA6sKAlkBaI0OvZ930/k/V0fHD3CHiBvxRaZ90JbxmNtVNRKHsbB7EaZDcRepN+dTqhVvNen74pBoaPzXPLQ9gNceinJmBj+sOBWmiUfWbvRs4KFzkw/Y5t0l2SEIVivSyzApANX5IIZTQU+3azBla4GX4nAHN924jTCwgfnNQfGqJ+qTV7KDTid1oIo4kL1EpuTLFyoDBIVmT7eVOXzX79cwlgK+6rGhT3u+4baU7UUZ8nKuq4xIEPSFuG4Mi2PLZL4vzLUBLSAsWZ805emUwf92qs6s08Srlx3z+tt6hWq7GLs45AnEatughiCsp7yvk/UgPIupkj3AycVh9yit9DP/0THJtxp1yILUUWYQHzNLCT8r6DpHqzH/51ohp1rQv0aQRlU6R5f043MBOlkVcWhTJ1NzqVXDyJMlHNfFzsyPmd9LMXd5jyxULQkUt3a6BZqn2/JIXxIV4SHuvcHYSWwVIPCuYRs6dl3P7HEIOUkhAEgAgAAAFDgAAAAAAgAAAA9ndWlkYW5jZS0wMS5zdmcAAAAPZ3VpZGFuY2UtMDIuc3Zn/////wAAAAIAAABaAFEVEEAFUBQUQBQAREVVEFFBBFBEREURAQBFBVFQRQBQBVQBVQBAAEAQAAUUBAFVREEQAQEBREREUFFRFBQRQUEBBEUAQBFABFAUVRAAVFREQBARVUVEAEEQAAAAAA==";

const chunks = {
  "guidance-01.svg": new URL("./guidance-01.svg", import.meta.url).href,
  "guidance-02.svg": new URL("./guidance-02.svg", import.meta.url).href
};

register('guidance', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
