
import { register } from '../core.js';

const lookup = "AAAB+YkZAWgYSBplSOj0WCRCNkQkg2RpwjNDYoV0RGeDU2xJY4Q1hVY5Q0M4ZGNidIJGZUJYTwtpBg0LAW0yvQ43AZaoAgMBBh/KAQbZDAGKAQICmwE3AZMDAQmYXBOsAx8B0wKYAgcY4QUtJMQGAQMYAgrTBggMDQM+BhYGRcACzQIFGWwCWQFoLej5MNh513BPrw9mOJDnJYFfU0STFfs4vqcSMGPfT9unZVkB+X3RQXtu13KKBcsbWtN1NDegrfprdmbXlGjIqrQnHzDqw6tH5IuL7nNujeq9hiBBrnMGR9A65CuWtjnxxACm03bQsVXd4hHdcx41ZKn0lsAzZtZw8AL3bDOpstsJORi4rJWrhZmat8nvxRUcFcxV12HZL1m+cZ8Bxydo7OBdhYwQR7EsrIFqtcGnIWHLv4X09SxTKVcHgJBPFLy6VP/YesV8ivEDF3Fq+cyPKLeuy5MZSzWPIOK72/MxiEb0RdfhOp8gcRrjqWtOSHXEd5dyCGiX9BI9sIIxV7erMCGDFb3Jk75JS+W7zUiSt8gJlzd26e2UKjrVvabbmPG4jelH/AQOF1ogP6Hyqjzy/1OHzncQ5wghqqwP/1MVhjHOzytFoKYtiUYMCT885kM9HaYbodI/kCBskzol1CewhzhvUcF7VeFWSYEFEAAACQAAwQAAAAACAAAAD2d1aWRhbmNlLTAxLnN2ZwAAAA9ndWlkYW5jZS0wMi5zdmf/////AAAAAgAAAFoVVVUREQAVBEBEABFRRARFQFBBRRRQUUEEBUAUVQBQRAAARRBRRAAREFBBAFFVFBAQEARFVEQUVEEFQVBBQEQRUQBQFQAQQEFQAABFUBAAFBRURFEEQQEREAAAAAAA";

const chunks = {
  "guidance-01.svg": new URL("./guidance-01.svg", import.meta.url).href,
  "guidance-02.svg": new URL("./guidance-02.svg", import.meta.url).href
};

register('guidance', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
