
import { register } from '../core.js';

const lookup = "AAAB9okZAWgYSBrE4Q1eWCQ3VWREE2UYVURoQ2JTOGNMUzR0VXQDh1V3NiR0RzJDV4ZGZpxYTAoBCwJsCQchTNQLNAoBCPEDMwQaMQIXpwIHDUaV8gMHAQwPAQIaATcNtQKZAaoBCBNxJSAXA74B1AEXAQEOQg8M9wIVARRDycYE+gICWQFoIb0rFTXT2Heriywg74D0LQ+09O2n99u/N6HiZlUg8rCmseSqcifIdXvxLcFGj2R3P8mrEmqgpnBhR1ZEracfCCzTF0n/5wwxVfPpRQECIJB7PRJzpmpTK3O1sjG3vSduESnDHKyKNDr0BZTfl5TohZPQ8d1LMMjiesXgiSrAcYwgqgE6t+S+V04/rOa8U1SFIHMQ+XU8AOmQDlUh5Y37Y1dyayglx4V8lvy7i8uKRwlu9BXhT9GfOfpoaHEHZteVMF0wvteDk4bE8mWB0JAV1xsXOFnX23nbIdefFcloPfmTqxvNOOM3cY2SuN1fgsSq9dnPyzwzb7fsh8y4uuqPFXCY1JbVrEZ9P2sYh/+ISBrBOmxDRwbYT6HqoAOG5/lBdjnS1jowHc52Dyc4qVOnmUhPHkWXdpq+Ua4EgS9HvTUJzmxaZlqpFLvwU5dZr6axCDH/CbDutyWTy/FLGUEzxcyu26nhELZhSQIjQAAADCgQAAAAAAACAAAAD2d1aWRhbmNlLTAxLnN2ZwAAAA9ndWlkYW5jZS0wMi5zdmf/////AAAAAgAAAFpRUBFUAAQQRFBAEERQVAREARAAERRRRUUEFFEUFABABAAEBEEAFRAAQRQVFRQQBQUAQEFBVBRERUEAVEBVAQBAUFQEVFBUBBURRQRFEFQBRFAAAVQVBUQEVQEAAAAA";

const chunks = {
  "guidance-01.svg": new URL("./guidance-01.svg", import.meta.url).href,
  "guidance-02.svg": new URL("./guidance-02.svg", import.meta.url).href
};

register('guidance', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
