
import { register } from '../core.js';

const lookup = "AAAGt4kZBPsY/xobnWxXWIBEiFhTVYJYVDYYdIhVtHE2hVd2IkYmViWjUrVoNqhWE0dzVQEjZERVNTeXh3NkdEQphUQsk0h2JlZEYzJbNFRGZylKUSKUJVM1RjJDdCRGRHiISSYXpVVUUmUzI1lyZUU1kmNlWIclJiNFdncxNGNVNQZWdoUqQjU0RDdJZCKHCFkBBQkLygE+iQIQAhAlwweaBAMFDjEDsQIWB07XARFDAvQRdgsCId0GGihFcgESEk51KwEDArNAAn0D9gWoA1lvA5oF4gQTAQKyBAIFYgcFBAFMHAIMCA0FiAEHK6sO2gG2AykNIwI/CQa5FwIJ2gQlDtYGAQL9CegFDB4hSSs+ASYJQQEBtjIRBywCJ2yRCIUJBisBCcAOHgIEDwkDUwMBCAMGdgdPJR4IywOHAeEB/gWCEwNMGAv+IBsIBRkFBSsYAQMGAaACC7kBIhUCAwKqCQE9ARUUF7gBmwN5CgM9EQI0twEBCzohEAGwAQMXC08b2QalMgELCBoJGQKkAQR3Ag8HYf0IGgJZBPvokZvXDKwwXW8P7n4hRv2xygu7ZOmeAhjFOq4lTRZ22LgYNJmg4gk2tcasDIyTvj5GhusYlqyQKHbrErynU0w0AtBsXaD3RAcj3tu1sNbCjkd8gU0zaC0udZF9XL3rbxwVPXhWJqMtEqZqFgOTuOSw0mB8I/23zNtPG8oUbO4+Q0b+iHn73MpHi+Im634G6aK6/PP+BJ39ScqOJsGEjn7N7Yprvo7SLIXw52MywNesOXJyppjmpAq9VcZlozzDdX+53UPmbb27TQIIzd1vElFDCvFp2Nbgh9/STYHWKvtYoToDhVso7pkcLb/5UFuFAYECoscl+FxK6jlceJB3zrko4zPkWuQSalJsC2gbTl8+9NJKMQUmFKbbmaZfhO8F7nwn6ImJnOawHbws90iYOIQiewTY+6RQNh+zbHsIgmYgLG4EubwH36jc3ZvEsmI9p5swIRaAQEizHWvuVJoXEku344q5C9WFhU90ZsGz/u8tZ1pFUESGSGV+S/nDaHg0a/cd+duZZLYGMtJ1Q4yEqBe5xHe3ssoHJIMmPBG+UyNqs6l5Rml1a+yHdKnOABgK8KzDqrH6zS/9xYqEbnfAexgTA/wJGzKnEm7yEiD6N5h2L5AtjKsdD6ReSNGI8XFUAPVYwl/sTwhVbb2tmCSPCAuOoBEGXZLN0xGaz9WXPW/gFdHqdWsOQ17JmpnNBMPMutGqpzcjzHPDmZn/NXQfkrqGfWDwsr8GNR0HooAF+xw/Qm7mP1oJjVC2KWt2zD/P77y9gYEOjpnhdtkxVWMspkv6y2rhDR+T/UcF9eka+e8BhE0PaivEYKb8FF61nNHm7biWzh3Xyu6+ghKTm/NV82YphDvB0AD/xLWHNKHQhdNocdOQG5CQTeXFkKAiUxckYl0EWQLQ4QsDWQHJgfcP4npYzoGlSZtcEfOlycv11lq25lH2VVuKGRltzvfILmAUexHA8i1D5IQsuSaSvTVbGWDATdEYR15qmPuaiC6AOWWBw32anc4RtGN9FiacCNrvc5Xmg6pHjretNR0OKzSmqXEA+tA/YTCf4YxD/fjH8/95bZDIOoE/aeR4QSw8YnylpzWkwcjFaQjHIFPwZrmUAzLtr3bsgEirakqwYAR1PIKc5gw+2t4PMh9shyqHGhsjTjYZBQ+cz9oYIjP5LY7Ms8qj4M9yLO35nahvOcmLalUbIWrhwYrMEww8RjSCExXepYMQL4xdJBIIaZYkFxLPhc72TQslcw4CSpq0J9/SKoSsge7GVsSrjyh+3gfEBWdJ+Rc6gR9Kh1gQs9pBMtfTFuaInDhU0FnELfENjPsVglzvKo+/DzxaV9yBVxslgSifJ6IHngWMUKaaQrjJ+jD6YJwWZDP+FBH55WU0y5TXf0OdDAHX0MD1E0dvYcFU0veVN19pg4KnXIkzVDJW4kYxw7FmVyvPPrflIov7fCVtm/FcjXtsf2g2tdnMth89r61ASB+4k77D2TA4PZrQHoOZGXgPOcnLZC0AkZTxEZf276t3Mikw/d3ty/lySFp6egF6/tdhGkMReeBISQtP87r5/yMfAXrVTtjpDatQ1lSTJi6b8KNlGKaXbcrzDpHFkcb+/Lq/R2FtIc04c+6PMblGtOCF7Hdzhrg+9zIB59YNDQXy1zVevRmddcnqO9zcRl03mbcb71wM6gPJuwxsiXIWjJLVhM/ydE4S+P9mtkBYIAAGCBBACACAwAIAAQCAADhIAUAIgAIABAWgEhMJiAAMAAAAAAcAAAAWcGVwaWNvbnMtcGVuY2lsLTAxLnN2ZwAAABZwZXBpY29ucy1wZW5jaWwtMDIuc3ZnAAAAFnBlcGljb25zLXBlbmNpbC0wMy5zdmcAAAAWcGVwaWNvbnMtcGVuY2lsLTA0LnN2ZwAAABZwZXBpY29ucy1wZW5jaWwtMDUuc3ZnAAAAFnBlcGljb25zLXBlbmNpbC0wNi5zdmcAAAAWcGVwaWNvbnMtcGVuY2lsLTA3LnN2Z/////8AAAADAAAB39KEQqSGRosADOqAJujYRiSTFmwkmainIYuNtq06LVParZKDtM3ARovZUQ21hKa0qdPqgGQSQ1IwDWIyiosrEJTFgnA4R1DRWANZVGHnMRAYbQXRAlagRqMTbcDocgNVZuq4UiQEiNJGqiwhcCQpVIu3WjOaLRENLlamGACbYWMLydlQd8OgKhFZAoZVtgwEaIicgGWpogrIiprlQXOAIipJCEAbRh0ijFk1aRATq0qGFdSQDVKH0WyWkVykiCm1FIJCp9GazoBQyOUkEEMppNEWieImkFhCrFoKVmA4bihAdGVKccKaFluJbqVTANnUlWLSbOnmUsEaAgEVbFCZTWqCZWpVlILLhaWgEEQ3lANSpxvWFGrVVgRZIVyjsAW7FFSVJou3uMlIpNAQEMtAxXLUNkuLJPM2MA3Qbe7CJZzQSKQ5jUyylQM0NENmRsGYBlybbBMQuFNRgODUNg1YNlTUyHOkSqgIm47TqRwkZdgSSFAhdFXDlCSRDLKkzMa4guXkVistkplUcUg8CqQbEYOaUNIYBh05sYoExEjdTqEakSSgBSYGhwa4BIXSgkqqJC3VLVRYUCTVdetAtAnFyFhTxhS3gA6hzBgtBggKZhg5F1IBU02CgBqobaWacgIBAAAAAA==";

const chunks = {
  "pepicons-pencil-01.svg": new URL("./pepicons-pencil-01.svg", import.meta.url).href,
  "pepicons-pencil-02.svg": new URL("./pepicons-pencil-02.svg", import.meta.url).href,
  "pepicons-pencil-03.svg": new URL("./pepicons-pencil-03.svg", import.meta.url).href,
  "pepicons-pencil-04.svg": new URL("./pepicons-pencil-04.svg", import.meta.url).href,
  "pepicons-pencil-05.svg": new URL("./pepicons-pencil-05.svg", import.meta.url).href,
  "pepicons-pencil-06.svg": new URL("./pepicons-pencil-06.svg", import.meta.url).href,
  "pepicons-pencil-07.svg": new URL("./pepicons-pencil-07.svg", import.meta.url).href
};

register('pepicons-pencil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
