
import { register } from '../core.js';

const lookup = "AAAGuYkZBPsY/xro/CcnWIBUVHRGY2dDIaeMVEZGRHRlRik0V1Q1VyJURohjdkQWRDZ2djZgZ1B5szJ0RSQickNldaVzdTU0NFQyOGdkYTJIQ3Z2dVJENEZzN2aFRSMpk8MlQ1JlZmIzVXmEQlFiVERJeENWJUhVaXc3RYhId0VqOhRjYjMkVWSIQ2dEO3VVCFkBBx4HEAsIlQEXBQEw6AFOH9Yp8BfeAQgbQQwWBQEKBwIUGwKBDAMCEJ8BGQMKCI0BOAEGCAIIiATSCRcmEw4EbAUPBSevAj55BAetAVo95A0o9UMBDAWuAxgCDgEBAoECCBsbICGlEgYZLMACMgUWBAIEGQUSDycDXGMBCY8FCAMqAw0sBh0CKwoCBgFXAgLGAvkBCQcS+gEBAQdBoQMCyd4BRAUBCggYCwUfAsMBAQYKAWF+AugMAQQDFggOCQnfBgPkA5MGAQhmEggRAxYIwgiSAYED0AHQAQwLAy2RBPYBxAFABgzhEirODQNSLwURAw8UEg0bxgUEA54BQAsGzHMCEhgHCY8BAlkE+zn17cqtUOYSwY7Z5ZCxLNpIiyFgUYkqPxv9Ix2H7y21T/Em6r77DSGihLXBH0A9JKcqxFUWIjOgukTg5raFmUfP/c7/JQLZGMloD95kSoFrgXvWfN1cWSymtdDx/X+Hkb42j4ino6usxpRVpNzOq9r2bockkl0xi4xyBIXY8hcGERcMDu6BWMN/C/7blTfibIpz/feRyryBTpsB/RINBYEqBMExR0W+AsXMpvoLQZnXjvlVv02A0YnBW+GO+g4C/oGYprWOPYw5chwYMizBhsW/KLNMRAkgu8q/pA2CAV15doHIFcnnoyypJoSS20EtLRDsRg+Ulngs+Tw/+mkP8i1bTsSnXBTgEjjX5DHQvv3VuaYYjJc+qgFILs3PpdEdSLBibAXoHWgTIgQ65Dmavc0fdyMwZXvAG5Xha9fVnmDA0mlJCA1GTwhRsp25+ZL6YtusErkSpoExKQRmE6HzJXZ3XOfmmrqH+5eQpLYyiLDMNCbw5NmED9aCipivaoVWnDImK8TeZh8lLZsFWkiMVHRN0+LNoNdr5qM18G88XvBzG/nLGC7l9/ct74FfJ1Xi1SyEtxkPEcXNz6BL83xIl6w3Tga9B/IVNgsRnTCZ0p53Clpvt5/uhNBGPO2sT/c25j63rz37YO8oE1Rh0sL+avX2AbFAzpundBHRAMjcEerr7lgSFyYYU1o914GO+6BiByKruZlG6ZjYCT0uFTQjnMADiaalinqoqym0uUaCbAXJnSnBvV6RQ3Tr+JBNQ7uOSj9ak7jMxpoX+UfGcTUfTVLvPspAkgy25mD4OjWu8zJ+B2tlHnKHSXtJScPuVVcCcoOEg2U6uAFGLUh2ZmwHnXXLFn1tb6oUbGAavHNP/wMRhWn80fMWemvKhRFqKt2M7/UjH01NmRcHR0P0bXjjovhvIt8diCgEk/4ZaQg6R7mO68CEyZyRNb+FDFDQGX9aEjIDgag44fnHzpwJpewI3nPQDD6Fk5ylg5g5SskWrbMmsM91gNNb8o+Oodbv36d8sxi8H5A1AbgGDg3LbYrwVsMbaL2CDrmi7nIb1lRYYEek+nNmt3VDHxIPb4BtJjSKe5zOsvlDGitqAEJqt4wGmqmxVfsbtiMPogHQaMw790OmfcJhGrz/u+YW7vPbJAvaR9pDPlOahNeTflv3FI1W63VZbGWbpqn8NITEKMkYeC8AZ2EzbjL9+ySMZ8nz+eF+fOmBfdz6zBnPkC7d45DXBcU3k7psXBiGPINgTV63n+nKPJYwzfFjbWQU/yXg5gvY/ulqFTmbIIFj/vFmgnQ/zxnXTQ6GOHjHdgow4I+IMNLDHSvu04+AA15CDAvAY7rEM700q75cdVOUeQBIvREIau2cz3rh70teDzQyjDQhUAv5aySZyTc+3AijL8Uc9237w8t8hOhkjQoyIXXOQ6ziwwgn7b2tkyaZ8/+0HUptyE7DRhJUApmRPFQCcRNhXHVQDNLlzfFxMlfKXcuaBWrRNhbMmQebd1/skPBdelebZNI7WBRGecRqXdyY1Yt9XX7dbppQbh8sqG+s5D81XIOC7PV67R3HWVrWmermXIbqBUvSVN9IULOz5FOw2OB2aAy0ZrO4FvkzQxKqaSPWJRsF7y32nXsA7mnGpi8beRzetn7QzpYtEgQwSsrDurlfXyeH/DMRKGWFOKcDsrUgiRDQdsz8mgN4xBm4d9OQuFggAPAAEACCQKCAEQHIAAAMBQEACGRAAAAFAAIAAlwBAAAAAAAABwAAABZwZXBpY29ucy1wZW5jaWwtMDEuc3ZnAAAAFnBlcGljb25zLXBlbmNpbC0wMi5zdmcAAAAWcGVwaWNvbnMtcGVuY2lsLTAzLnN2ZwAAABZwZXBpY29ucy1wZW5jaWwtMDQuc3ZnAAAAFnBlcGljb25zLXBlbmNpbC0wNS5zdmcAAAAWcGVwaWNvbnMtcGVuY2lsLTA2LnN2ZwAAABZwZXBpY29ucy1wZW5jaWwtMDcuc3Zn/////wAAAAMAAAHfw1qmZVhtAkCWKrqmdoCWahNw3SSx7AJLSMCiEFBlEIgkGzUlUocMJlqOXDCNoQTVjIqoGsSUoqAtKISibEJ0dRc5BIWBQRSgIaEFERBWlKCwkmGhclsl0dZtGktkKQMAWRSuyxiFkUSBWlZrlUKMmdkpSqFtWCwEJQJlpVBtlOqNXbEgSRpa8oItW5uNg0slpIWRWMetKoN6iD2UMQp40MBuXgZ3YyMCSpCEVEd4WJZhSISOitNmAS2mTMspLKOinJDaHVJEXDm0WiFGUBVWyAqtY1BFsWqCy1RymTRTmYgAZTOmTUGKMVoSDetpqOTGtp0ubakQJqRGrNuIlFRSKmNpZQyCCzaGkYiA3RhxCEQQQou2CQMa8dCUJhigQZQum5IZQVdBItFBXrcqhRTGJYgUasuKZVpsTEgFFKpFGzmK9FRqKxaralBEmpaulkbIQLFZBIxqIbOwITYNhkeCGgasqypiGkUyGNiQkqCBEwsu4TI065RmJuihQApu7TTDbLKFU4eFZSqWpZo2rQSAM0kFKlsqiIMq0dZlsVqZKpFJQDhBYREAVLOIUKkaI7vMiESv00ChGSLKIDyy2SRGSiGQSD0EGlBNYTc0pYUsVGQW0MpVVIJi5LBkoUai0gAAAAAA";

const chunks = {
  "pepicons-pencil-01.svg": new URL("./pepicons-pencil-01.svg", import.meta.url).href,
  "pepicons-pencil-02.svg": new URL("./pepicons-pencil-02.svg", import.meta.url).href,
  "pepicons-pencil-03.svg": new URL("./pepicons-pencil-03.svg", import.meta.url).href,
  "pepicons-pencil-04.svg": new URL("./pepicons-pencil-04.svg", import.meta.url).href,
  "pepicons-pencil-05.svg": new URL("./pepicons-pencil-05.svg", import.meta.url).href,
  "pepicons-pencil-06.svg": new URL("./pepicons-pencil-06.svg", import.meta.url).href,
  "pepicons-pencil-07.svg": new URL("./pepicons-pencil-07.svg", import.meta.url).href
};

register('pepicons-pencil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
