
import { register } from '../core.js';

const lookup = "AAADi4kZApYYhRoSFwP/WENFMyQ3JChjVGWlloZ2fHJVoieTUlNDJWUmd4Y1dDZGRSY1VlVTaqN1RGJkZQUiRDcldEYnVCVldXIpp3BXZ0VjSCEHWIwHBAQBDgHlAQLwAQoBEgQHXAH8K4wB8ggK9wcSRdo91QEEfSQZAfQWwwIJ9AcBBCEDBXoTSAsIVALaBAEEDbcBGgU2AjAWFBEKBAUWEQIBukUh/BA4HQIPUg6EAQI7AggCFbABBQcBnAJGAYkDAgEVMAE7cg+3AbUD3winAcEVdD1uFBcMCt0DAgTBAQJZApYHrY7FgQpS2Zm0UEF+SfjyYCozOx9age4lI7Q1FOQokLPmTxr5S/tBq/MamMf3ZqgtFHPCnBUvnmMDx//jA1vCxdPGa5RfuahpFjENwqXGR3EglL3SrioqDnMq+VuXG4r2CE9pK71DYg3s+F1Nq7OgTlO0c7ieryaXaLvxrGz7vGz7Y4s/MAqGuV4Ny8HgSQJrPO4UhL3NhkquIZSniuGJsuGPddKUzma86yedhnkVlgKWuKsgc2iHblbt6TxZv2/nuMfxlzgZGToXsGLFV40iFvemdhkqgs8mGFquOucDon73PtAgMYQcz7VoISzMPce2P3RwxFB6xqzGLE6qR1saUNnpiqMVEAMMCv4rA7wp1uWM8FqcGQjusf8aA+pNwqR7zly1HqTt9aNGsVkqkEYJFaSpVb+cVD6laKRuLxWcU2EZEQRUWO1mIjM6jUpLKa9vHP6w6BJV3nqQbOg4IcAWk6c5hgxEGe0clnAXkBZ1j7Gx6rL3Xp78LEDweZQY/MqvWqgQZGDH71iguDgK3hx8qkjKxCiGvvVQpSPh1AlVsgXYQB0PDEzK8pOgNcnDW5l9PXycBRs2mR/aFVhPH5oVj7/Hs03oMtzJwGnC9+GSldBsTujxoQ6i4p9HIp7XYMpg1Pf13HAPNHuprNgzQpcybNAK/wyyYQNRln40psPZtjxiWn4XXf3iWmEpPKaR512ur+JsnEZVQyQZzcGN8Lxae2uhey9iQEuktZliHbww1jBEAL+43w2X3vWBzq8fnB0//s0MPWugU9+SzJXCzUr9gENTgGVHwprlIROKHB3A8Y6L/99YKCI6Lyv4h85WZZAC3nccT7WSNpYyjp1SV/w9wJ+2gBmKKfE2QzQa1VdaD+GOe6jrnVEACwAASCACAAIQBBICAMlABAAAAAAEAAAAF3N0cmVhbWxpbmUtcGl4ZWwtMDEuc3ZnAAAAF3N0cmVhbWxpbmUtcGl4ZWwtMDIuc3ZnAAAAF3N0cmVhbWxpbmUtcGl4ZWwtMDMuc3ZnAAAAF3N0cmVhbWxpbmUtcGl4ZWwtMDQuc3Zn/////wAAAAMAAAD5QLRgkRYlQiREipQhwhZBEBBMUCIlAaJsiCRBEDYtSRIlUZJBkqZkQCIkkBBBUDJswaBImQYEEIBEkRAoWhIEUSAFwJBAAjZEiQJFgpJIiRAgwhRNyKApCZBIUpBBSLIEAhIhiZAsCQIMSiAMGaANSSQEgCIEQSQgCaJAkhAFiBQEkiBICQZsEJJJELIpkQRpkQIkAgAIQqQMiZQogAIBSSRBmRBFiiIhACQJUZJk2aBACAABkRQBigQAgpZIQgYgkAQNSiQIEYAAAIIJiDQgAKAo0QBIESAkGRQBgbZFCpIICSIFEAIlgQAgUiYkkqAEwgRIQJAhEiQBAAAAAA==";

const chunks = {
  "streamline-pixel-01.svg": new URL("./streamline-pixel-01.svg", import.meta.url).href,
  "streamline-pixel-02.svg": new URL("./streamline-pixel-02.svg", import.meta.url).href,
  "streamline-pixel-03.svg": new URL("./streamline-pixel-03.svg", import.meta.url).href,
  "streamline-pixel-04.svg": new URL("./streamline-pixel-04.svg", import.meta.url).href
};

register('streamline-pixel', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
