
import { register } from '../core.js';

const lookup = "AAADhIkZApMYhBp2VfkaWEKUUkWkiaGUCFNYU3E2Y2dWInJJNCUzRkRWKHMxN0R2VIRxhEclQndEdzhnQyphRHdVdEM2QoYsQ1QERlNoMWmmZ5VYiRr5FUU4EQGYCaoK/QXXKwrGGAkBDTYQCacBJAQtb1ICDAKaBJEHEgERAQEBRAQgC0kGxQEEPATMAQUHEnhAAxgQOa4DCB+8AQEJCqMB1AEKAt8BrwHJCwQcAwId+wYDQQ8SHqsCAxAGoAQEZQIFhwX8DAQBBCENPwwGSwML5QEBaeNW3QELEoUIAlkCk/2oEpP4sQBm5P5KECV9Dky1Nv2ar4x1uqiAE3oL9nN6p3yCvJJDncVP4Q/nvg7+UQTH928kphXie/5KmbZ3V+1Mv1WiswpHbQbXuCGUt8/JAlu9/vr/L1RcCcjOQOqcA+SIViin4uZ4Q2bglFnDozBx1sEqFio4hYoQ8TRwYz06Fd/r9gFG2RiOCJGIw5DMPxiu6Go8TKLUxYcfLgbzAZFWnVmbD1sAinczlfigb2BAWc558XQj3AVfBwKUKvc2arT8j0erhSdoI4v/IVPOjrA+ON+QEBMNEMOYxUdXa7c88jOjMdsAgjzO4uHLn4DrlKongsmw5FwszC2ucMyUG4XOteSquKuooZYFQYhHspMS3DZy3/0DZZNe7As2aN8C7NcOIz+unfkp22F+JmbwfyUnP3GGxEDFs5rMgh0A2DqmXst5YVbH8CbRzYBIlQhnh8lGH1OXh8ZkXuscNq1plhlq95vg1aQlwPEbz7VYMcAZ373cYBcsIwjVqGWT3TZ0fNCDVnRzQSzoyZm7AHqMY4/pQEXcGkMDdqOlnnNiPNAxALykJ2d7Bzv3CMd9k1FrFjT8Lm2zEQfdHuvQblziXTOfjVEe79hSbD0LJj72z5hpravYY9qpHbrRWLMNyCTgdulqqGlgqiEGulOudjLizucXInh4oak/uY6Ki0J0NKok0Rv9MkIj07vc3fQqRJBrB0L1b7sHzYwUv7leVWDQbKco1oZqvP912co9Sy/Cy94pejzIp/aChEi/ajzTRslBuE3crdt8ll52DtaZLDUz9Vo9Ld9CLa/Rw0pZihbLL55q/Z3tWEBmGtHwMLqnoAD56EwxF/iVaghSuWDAJbnLz3U+xd8rgmFC6NoDBB++3+X2i3eiUQSEYAQlAEgABAYABJAhCAwAAAAAAAQAAAARY2F0cHB1Y2Npbi0wMS5zdmcAAAARY2F0cHB1Y2Npbi0wMi5zdmcAAAARY2F0cHB1Y2Npbi0wMy5zdmcAAAARY2F0cHB1Y2Npbi0wNC5zdmf/////AAAAAwAAAPiKACSTpiCLEAWBAAmANgGKgm1KgkTRJAXTkChIIABSJihSEkFJgCTDgiiBoCCBkgBRAgEIAkBDokASICACkkCRkgABIEWBJmmCEAQSAAjQhC3bEmlShiSSpETIFAQSIkESoiiQJEAKtgQCgCgYImlKhGxSkghAJkCBBEmIIAAJgAhIgAySFERBEiBBBggJEk2AEgjQEkSSBClBlCgSkAVCJEmRBCmJoCRJhEAKACVBEkGBIggSICGIggUIFkUYACgSkiCZIEiJki1KgEHatkCCBGhQpkhDkmRIoGQaoERAkESCIEBAoAjZMilAgihABACApAgQAAkZAAAAAAA=";

const chunks = {
  "catppuccin-01.svg": new URL("./catppuccin-01.svg", import.meta.url).href,
  "catppuccin-02.svg": new URL("./catppuccin-02.svg", import.meta.url).href,
  "catppuccin-03.svg": new URL("./catppuccin-03.svg", import.meta.url).href,
  "catppuccin-04.svg": new URL("./catppuccin-04.svg", import.meta.url).href
};

register('catppuccin', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
