
import { register } from '../core.js';

const lookup = "AAAC8YkZAiQYbhqh7B2oWDdxhHlDVINHRlQoRSdFMnN5U0FDQ2RWNHRYVlOzhVdoMkVnRWVmQ1RRZSNkVjOFUoVEl2gkZzhWWHMmEEixDe0BAgMEHQjnAr0BBZwBFQIMDgEIA0EBAgUGIfAB3gERChIPHQYuBQkRAgSwAecJAwYEFxIBtHgh6wllAxs4AwEDbUAEDwibASsYCAEEEQQZAwUZCzUDC/UNATdYpQUCAfgDtgl9NwTHARfXBgoKAlkCJE32eKfDzpOGXhJhuLE6QcMhtq5zI37ZUUeJtc4wrcp/RXvQSzzm3YGWVTLug1cf9VDDMlo4hDg8tRGySNhtwrbGiWddTSKP71YSKC/KZrdXzWQAP9ZFcbkjzalpmHq5lLZxYdPrSST0YXRveonGyGpAalO6UsPRXDzXR9vt7jmkmEEfZwy8ELl2rewySOQLMXFxX4X3yggwr1Ov5PnO8Zf3Ex7mEkY0dsmkYLKMYPuhX4z8QonciG++4xm24nLvRGU97iMHcpGHWwbYeaeceuJBst86WNHcQQ9FwdeNGzAosUby+GMQgTm3AuMY+XU24ss+cnFcSKtpVw4xQNxW/fIeIfYqlohIwm0dhrhRsWCssDpb6zxTXYed82VIsP2dko677X1AJ5wVkx+HF/aiDhq71OfK3zw0UbNeE0GyowGDwpHeIQOs6M58r3kBvc5lI0Ktwto8j1h2bW+0kLKkruZ3trXQERAT2JTGRDHyZs2ZtfKm59C1EvBsNrubYa1Q7tgSlC5R6LWOCyXazI4fqzGi/T0mt39lt5uyIkbBKsuuk3UFJUI9bdXPIp1n53D5G5/jiOuDXFqDvIBABNarKhVRi6kQ1wSlKptRo06hgALFwbrBCa3+l8cJ64XtrMmNNDca0bqhy1WjrohRn1CR6UfJD1+3IRUa7ZePbZRc6y/Qc4iPfoCYeLntGzMybyoqgn/pQ4eb76F3wmzl9DDQV89oPfZATgEAoAAVAABAAEAMAoAIAAAAAAMAAAARZmE3LWJyYW5kcy0wMS5zdmcAAAARZmE3LWJyYW5kcy0wMi5zdmcAAAARZmE3LWJyYW5kcy0wMy5zdmf/////AAAAAgAAAIkWUqVKRVSIKhRlIFSSKUEYYWGJBClZGACBRZkARhQQhGAEaKEKmqBVpIAFGQpAZUKhFUREIFQRAREmCAqYFCpaURUQqEUhBKGhEQJVZAFYEkpYmQmpGpJZQAqhhkEKIUpVlUgQERSkkhSBkCFCpFWCIEISEahKFqWqJmEoFVFJUUQhBGCZZWkVmgAAAAA=";

const chunks = {
  "fa7-brands-01.svg": new URL("./fa7-brands-01.svg", import.meta.url).href,
  "fa7-brands-02.svg": new URL("./fa7-brands-02.svg", import.meta.url).href,
  "fa7-brands-03.svg": new URL("./fa7-brands-03.svg", import.meta.url).href
};

register('fa7-brands', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
