
import { register } from '../core.js';

const lookup = "AAAC8YkZAiQYbhpbrPqWWDc1h1M0VVd8Y0Z5kyQnYzhRaFiFZYY3hlV1BEOFh2NUZFV2VScSFFNjGCRkViVYNFVhQzaIRRoxWHMovwE1BhoJARkvJarGBP8BAwRPCKkJrQEEzwYKhgMBCiHpBhT3A8cBvAUFJqYCKkSyAmUCPyIZMkkOAwEPG9IDqAQBXgMiF1kKBi1IGQlJAicBJwYCywsOAQyjAUgmJwTOBEgCAhkYBwMFYM8FLQYCmAEDAlkCJLwmj4i95EdGt5KcSOdBn3cO123BIRKAZVLmhwK6RTEjtYPGrfZy4zyDCV6RmLaUKrNBkXEu9vydZzhgmyPBJDCvHtvdsbmyz5hJI3bx+Owf0GH9q00b4obryrU8wn7O0MxtH1+jByptYYVWm5vw/XYef+6sDkWrSBDQUeV/antgU4iy0GfvlgtlKhudspSybFX1sO05lEjKyyFfiLtRxkQqh1DeI64RpKGlQV0PulGL6wQVjzD3IdpRRM7cdeeyjmE4iUKMQCIf4rU69ti7XKFlzYT5AcOJKhgVQMq46GGYj7aJW6PRPRrRtzziuq5TELG2ojJR03a5++6GPeuNL6evSLAMExqDpG1eMEHmJfI3gz0+rUM6mwi3MgtRUJZq+Z+vE3f0gFCOu8VpriJWcW9fb9fkKFft7lUx86czh+mty9CPlyLZ55xc9qM82nEhtaSpNs49xxHJJZPCKu2seM2dbHmTcfQwrnw5l3o2gnAv6I63z7kxeJRR7hLCD6HXl6v+NEBHBhu13z8STnUQPGDREldz37cD3OvDR2hLfVPUBHpaW7QyhUgBNK2xTcJBQlfOcTqBvu9azhV/gUZdcoxYPNjL2Om2Jyi48veHyfKI7abmemnWgJB+GdVvCW1cQLVm+XPcwoiTMu1Yb8qyRQXJY5nGeUKiw3RAH1y5tqHDwTHNEO/WvAIS4/IdrEZnABMa45EXjcjr/VeticFyZmQ0ZanYTgIEgGBAgAgAAAsCACEYAAAAAAMAAAARZmE3LWJyYW5kcy0wMS5zdmcAAAARZmE3LWJyYW5kcy0wMi5zdmcAAAARZmE3LWJyYW5kcy0wMy5zdmf/////AAAAAgAAAIkhGRhiYRloqoKBmBRgRQYAiBaEYRFRGUYBFGYARVKYlWAVEEFWFFVIAKiBBaWJqIZJimCAYaVQJAREgoaRCRkVFmlogahhJIIJAQImIkQYoCVUFRBKRUaoGmYRhAVQREGJRBGVBUKBSChBqhZqlkFUFRgYFBKYaRplmEFCaVUGoBqUIKpVCCSWFAAAAAA=";

const chunks = {
  "fa7-brands-01.svg": new URL("./fa7-brands-01.svg", import.meta.url).href,
  "fa7-brands-02.svg": new URL("./fa7-brands-02.svg", import.meta.url).href,
  "fa7-brands-03.svg": new URL("./fa7-brands-03.svg", import.meta.url).href
};

register('fa7-brands', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
