
import { register } from '../core.js';

const lookup = "AAAD5YkZAtsYkxrEElwfWEp5h0UiNoNUR3hRR1RDZEVFQ0U0WFRCJrVDhJZmOngyI3tXaEVjVGZ2RFKDQliGJWE1cqZ1JYUVNCR0MgUmYzVmc4RCZzVqk3U2A1iYwwZG7gN7AgMBVwEBzgIKVQhYxAEeFQETFQEBGA85VgcLAQMEEBAZBgkoAVjrhgIBAisQpgpAE74FzgL+AQEDAqw5uAGGBC24BE8EFgM3CgFFBjAsAQIBCTMFBB0oCREGEjsJAlSuAacCAgUGCcALtgEEAhqPAgcdBQEFIwm6Aq4BA5ECBacBAwzvAhoJApo/cZQLB54CEQYCWQLb31xhuvs84jDCuGEp9UQwqx6QePtHHGpxVUxCMp84mToWbubKP6yugK+lSG3/RTkuoyq01rQ3xS9UR3Ivux790ys6oTzhqVLPAKoERzUVUbgJY5nJ+J1DtoPZmSJffDyfs+mfmPJRCiDFewd+C/yxt1FTk4AlwyVzy9R1t5osji0F+t1tXJ25X69dTkxQwmcnQL8p8xjoL7rSsJah7len3SchPauqzkZ7VjTolIx41AZmPBP3uW9yzDILopA+mRl0EItpzTbFVCyifNPaNE+NkQF6j/jc9lpTnclsru7v7i/3alhsSJCymK9vGxDZbuYCZfx6iz+/XUXhOdrRtL7tcyJzGmMZXmTb4W0MIvum6ulrfTZEeP+F59OIuwY1Oz+WFP2mJTUGkFedsRipZumi09UVPPyMosYw2kE194khVC5qNWhzzQ1wH5s+B3th7YuikFQaeonJMSMptenJRsy4UE8Lq1QfY+bqxuk8daKPappxEqIdgiGKvu+3XLZUzr+2ABhw53tSDRIbM+i2eAEf2yrrfDv7vfXpIcxr/jQTuinQM/MFfGDKD2y42liL0WpdG4iV8BbDYhgxk4IT+qWKVcKRQN2Bjo73hUJ4DG2anPj3dN4iKJKpemrdNGYa6zeZgqQ1EmMuk5b98uuQASUXW1sC3bEUpzIvUCWKPAqRRqi27fONom32ck+rPHutb6hN/3Fq4/hNFQN+TjHdoisafpDceyzK9pFTeOTi2BHN+Du7+Dbv4uLVMyZMAshBgnFrxvEumi52W6nhM5KDGeTrR1bOSGU1tTPb6tQjA95iG91JRMyP55l8wsaBTdwXVEvZHTzqbw0/Ip1AqzZgJcGh6mokrfrVxc2iwSqzBmgrMYk3KAnFNl2d53QcAd8KeMfCS+3fNssnO3Qxsw8sd+iMym5V7TTTFIPllKt7coxcXTMFVgYhGJPJ/FTXXBbYQXDL7eH+cVQP9RRI1WBTgBAEICEEAkIAABBgACKWAgAQBAAAAAAEAAAAE2NpcmNsZS1mbGFncy0wMS5zdmcAAAATY2lyY2xlLWZsYWdzLTAyLnN2ZwAAABNjaXJjbGUtZmxhZ3MtMDMuc3ZnAAAAE2NpcmNsZS1mbGFncy0wNC5zdmf/////AAAAAwAAAROSEEgIhiiAECkIhCFYgEDAJAkJMigbgiEQhiwBNAEQpClagkCRoGjBkECAEkxSAAkJEggJFgVbEEkZFknRpCCCMAURkCxZJAkTMERCgiQAkgAbsAwLgmgLgGCBFEwRpmxLAkyLAEUAJimDFCXLMkBaBAVKJEjIhCnRggSBNkmYIiFBkggCAkiJJCybsCUDhkRSli3BEkXSEmVJMARQhg2CAgEIoGTDMkmSlAQSNgHaBEVTgglREGiBpiARJAFTJiwRoAyAkC1LgEnTJCWQpECKEkyDgmiANkGQNimTIADIlixQki0YkCFApEQJMEmYoCXYtESCgEDYoAzRNGSYgAjIEgxSMkVSNkUJMGhAhAVZkgkKAAAAAAA=";

const chunks = {
  "circle-flags-01.svg": new URL("./circle-flags-01.svg", import.meta.url).href,
  "circle-flags-02.svg": new URL("./circle-flags-02.svg", import.meta.url).href,
  "circle-flags-03.svg": new URL("./circle-flags-03.svg", import.meta.url).href,
  "circle-flags-04.svg": new URL("./circle-flags-04.svg", import.meta.url).href
};

register('circle-flags', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
