
import { register } from '../core.js';

const lookup = "AAAD4IkZAtsYkxqjM7JBWEokJGVImIR2NLRWVWUzZjY1Skc2U0comXJVVjQ6UlZxFoVpE2SUNFgWJpUyVSiGh1JRUTY1UTZVdXZWZUMZZnRChGM4dWc0RiNABliTHQELLXe7AQapAo8TAs4DG4QBHg4NyxnxARUHHgzDAQUTJQoBFgqHEwG6AQZUAwdDIwMVAnGGAlEQHAEPBwTJDQcBBjQBcRgULcYIBAEBaguiBQ0CqwlWRjADpwMHBnwBL4wNCigFBiECPicJBAQQEwNq1wMMCy56BAruDAUvEgEDCMkCBhTbAQgJYHZ+B0EGAQowAlkC28UhKem6GmuoNVGfozviNPU1RtRxOkRqQZaachQD+0TRFmo8Njft7o5zeClQq8IiXUxSuk5ILHD3APHdbvcUJlvDITt4kCeimpGdGbc4fDz6/PiM+zVj+L/C+OPZTF2iV29Sq1SSFYOrXA3yR9oi5Kvn87iQKessgBzqYswoEM11iMESVIrGJKqNwtRh28WBk7RtsYGlsDxWoj5AwpSKHOL2cDc8m9HaXKwCxljhdDNzK36vNcupuFTVucmnSDWMVFBxL3obxbQL7nPtFGVNGyXMQhPLEy88tpLU1uvqenOzezyxRufJsf0XKsmYDc4SOt1NOd98mUfh6lttZNeiMfVcN+u+kz57aoxsLh3MUzynGGozdFyltIIRkGCI5/BwBiUi72MtQb3Lbp1sg5bmT1SRj7d7kxqrYjSfU7bVyvrFA3vab1F8/OlaXRt4Xu19e7aZZhAYne8G6Iu/VVH9Ihou+AbHbffcaycrgt2u1Xp7CuQy92p+6uUKYaFQP4//NGcuVtnt3EcXZv6a0yEsTywYG+atkJoa/pm1EraW6COMa7YuJZ2LDAUwO2rPFk0vL8zKmfKpezFyuB/pNjI8DyjIj6kh//iVNaFAonwiC63TS0SD6XyknY2JRmamonF0gs4MkWVH4vM8RcHbMQ9x9iqzYYty+0HN2h8N347vuJxs22pCM52QGb9UU3JF+yqrbcpgJYDhMhVfBf89T3jhNjYJ2Bbu0qLGwzF2oj+F1Qs/yVQgwvxquwQxJ0CqTiVvNqK6t3SQApg1Bt38NIoHyveiqIJf3RnrE3WfMw/tNBjN3d39mYnz568HzlTTW8kVO5lLFN7T6FSTCXi7eHfci+EGHSk2PwCQM+lDAVbZ9cZ4u+pjIx4w+o5xSAGubV3YCi8BGIUFpu2v5jBc9iXQoVgCtc34bwEhSC5d6R/TsitVM97fkbN6icVuaB5o4jnoTKl+lGm5vmBVSVdjUwgAAAIAQACQIIAyQIcBABIASAEAAAAABAAAABNjaXJjbGUtZmxhZ3MtMDEuc3ZnAAAAE2NpcmNsZS1mbGFncy0wMi5zdmcAAAATY2lyY2xlLWZsYWdzLTAzLnN2ZwAAABNjaXJjbGUtZmxhZ3MtMDQuc3Zn/////wAAAAMAAAET2YRogyIhQ6Zk2CBsSKRMSaIkWQAFkSRBgQQkmrRByLIgGoZB2SJFCQQBAJJJyrJBWRAMgBQEC6ApwoQoCRAJETIoCoJIUTRti4QI0bZAEQAsUoQskRItkrYsigRsSQZBggIFwxBE0RZAwTAE2YJJmxBgAKQgkaZFQQYsyAQBEbAFwhBAgrIpyYBpipBBWiBoibQEiaZIiQIAATJEECIp0qIhAJQAQIQBQyYgk6BsmBQhWpZkWQJEkjYEgZYAmJIgAiYIAYQkQoIE26JgiBYFkyAty6YBCCRBEiAhSKJBSiAggRYMUCZkShApiJJBgxBpCBANkgBIEwItGaBgkRQpkTYAS5RFwBJBmiAA2SBpgpBAkAAAAAAA";

const chunks = {
  "circle-flags-01.svg": new URL("./circle-flags-01.svg", import.meta.url).href,
  "circle-flags-02.svg": new URL("./circle-flags-02.svg", import.meta.url).href,
  "circle-flags-03.svg": new URL("./circle-flags-03.svg", import.meta.url).href,
  "circle-flags-04.svg": new URL("./circle-flags-04.svg", import.meta.url).href
};

register('circle-flags', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
