
import { register } from '../core.js';

const lookup = "AAAEHYkZAwgYnBrPeRM+WE5WEXR1jGZUZkNkZDNmo4NDclKUNXVjpTNzBSVkKGdWQwdWhUgTM2KXRTVTh0WCSDQVVSRDZ1gGIjRYVGxCV5ZiNjNmY2RiR0sqsmKSS4RYnlIhE1c1KNAjRTIGBgwnBQECAgYUJB4HAsUcAigPBRIBAbsBMAUyMgcgZ4kBAwQKmQIsAwMegQGPAREKMlEkBh3XDaUBBQMHUZgCugIIA0QGBhmVAg0YCwHbAY0BBS8SDgEOAQsntgEQSgICBgavAgseB9HIAkwBB1M+QKEFGAQFAwEgLwNnAyxlzgMBi0X/BAGchQECFQGPD+ZyHbICAlkDCDOeBi8zbSlDuRXgLnSVnlWak0Ar4J0oHGdYTBRUVvnpF5uP5Sfcst+QNA+xkzr2PeGOrvJld9gccP4xqojaYJUDi1EJtRv9WV/49s8WQxCLeD6U414xCDIdZMH2amFsmpEo+Liu5taUVJXs8Ah034SERJFxzvgvywbYpJE1hXPIRe5pr8MF2LTViDpcMRQPTEqbQhh2OdJk8l9QgaAoHvirff5OzpsUB029WMhN81SR2Cd/zpv1UVyL//sCNNkF07MDl8MEGx7SUbQnCOm2w3ujsEKM1v80Z973/RBVMb0ohzRhvZLy1bG/buLLFydNE1wIz/+XVJuCAEokpe1J+LIZ3a3i+8cHhSghKFb3GJY6eNLH/er2VQtWYrdsv9f+eC4FzQAH/Q/XMVI15dfmb877i4wA3D8Oh0ce1n4RORAwnDdQs7ZPoN/E3SqF+ISOwbkaYUL3L0xQ1Bm7mFnQfHgG5jL4PZIZZMg3MQt3rY+xtMZUeDRJBhJ3bkkB/pocuQJbqbT94Pq7vUcinZ2v6nOHCQFLv2qY+MMNLefX3vnyjgxfC5EA3pS83/FIpJomW4Cuk5gLFdp0e1+DAKYfrxZx8lfQy3b0Ysxji6U6dGxDDmo0qGmiftM5kLyBvWOHPIlhXnlJKSuAci3tMyYAtXrdYFwfuuyI1mXR7pqMIw5NfB7eXIGzrgDJOZNWE8lSasvZNMxcaWdh6XvX3zZBLrbKUuANl/CZrKy1Gmlgv8pzaguKAvibr8Hv3qfw3P3/wvAzChrSmp2ZfWAioP55WqOFtsqsNZrye4jZX0IMTCfGNZJlPO1g/201VqSdgKYB9L7Zaw4Y4IGjZBBF9mN0cD26Q44SURalJn4xGrmNZ6pL3RryvUYPSsSTguQ0YYWqCAPGa2fkbb1RxYVai7d9Z7qxMIX2hpSQzZS5GBeJMmPdr6OC8H9QfKnUwH6sPr6yAaRdgvmK7JVa8SDJn9EMTCpQfk0tcCawgvYsL59cGzqDAJaMgX12OHXOTSGsTRs5pZjqhvH+pFY9VAwAwEAIACjCghIAwBIgAEAAhAQEAAAAAAQAAAAUZGV2aWNvbi1wbGFpbi0wMS5zdmcAAAAUZGV2aWNvbi1wbGFpbi0wMi5zdmcAAAAUZGV2aWNvbi1wbGFpbi0wMy5zdmcAAAAUZGV2aWNvbi1wbGFpbi0wNC5zdmf/////AAAAAwAAASMBMCSAMmEAEAmDBCgTAikIgghTtgmRBCiQtAQDgCFYEmgIFiwLlGELEE3ZskyIFEnIMARJgigRNE2IEmjLFAXQoi1CEEUQJklABgXakmBJIE3ZNkmbFCFDBijaFgFDAgzJlinJBGBYEgUTtgwJpiFRIAHJJEHQAiAblihKAAGSlmFaFknZlAVZlkmRskDBBC3apgDIIGwQNgmZoElCkCWKAixSBgRZokhQhmSZhkiBJGTSkmgDoGkAggxCEADDsA3DoAASoC2CtmmApmiABmiCtCTItgCQsChZFAyZEiWAkGXZgiSQgmkCFEHTlmUDogSCMEmKhmULkCwChAEKgAnKEikYkElDIkTZkimCpCibhAmIJkCRFmUAFAXJpGgahg2SpikAAAAA";

const chunks = {
  "devicon-plain-01.svg": new URL("./devicon-plain-01.svg", import.meta.url).href,
  "devicon-plain-02.svg": new URL("./devicon-plain-02.svg", import.meta.url).href,
  "devicon-plain-03.svg": new URL("./devicon-plain-03.svg", import.meta.url).href,
  "devicon-plain-04.svg": new URL("./devicon-plain-04.svg", import.meta.url).href
};

register('devicon-plain', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
