
import { register } from '../core.js';

const lookup = "AAAFR4kZA+gYyBpQjjbzWGSFIEI2VGI3WUh1NGdnVzYiYzVSZygxQWhEZjSEZ4JUiERqRmWGIzNSWGNlMTZHZWVIYXWlVVdlIwZkaHlElFVlRCd3Q3I0aVRFQoNxNmdXhSQ0hHc1MzlzkaV1lykkonNmMVVVWMwJLgQUWBINA6kBvQEBMTnqAgYJLAEGEQ6CAS0/CQkDwwEHAwF+KOMCCxueASELAVE5AiEmMEICxwgIMLoIbgsDiAMSRhW5AUXnAgQDBQS0BAsgGgECKQ01BB1UIhiyAgMDJykMyBAHHZgBLAgxuQEtKxQSpAtnBQaOAjwFEtkBAwQNA+ICegUJPgJGNgJVEAEKA9cBaEoBWhHyBEgXYQkCCg4ClAHYAgYBBQLJBgQFxgKBDAWvERIQgQGPB/8RBLgXDOkBNX4IGpcBCgECWQPoX0EPZ+WRo7CH2OLe+V04+yWxoDoMeJgTXxtfKIAJXTXJ5lVm1knOE37ONZRsb6YQIbQfDCkFFZzq0+9pXB1qIIWw71cHnoe5TE0+7VlNf+XcyAEvdE5KwWsiBhYT7tflYWeZGlcRwJS0nR6gTMCM4347rYbKbQLTEm1uvw4yy+XF9XHd9NCqnmM/aGlIxrODTMTiG27FGKEXbzyBFCI5NjrKhmp9HaVRS7nymzcZ1XgY59c3Wq2+GXj858n8Rh2b/EvFuoKCYkSGqn1wjlAlBjho5hBa4unK/tLndQtWOwqmP2VZzhd4DFPLox3PfIFj5YFzojciBI5y1/OeopqCxCPUsC3YpFbcnTbOSoWAhJV1Ss338px04wRP0HY8D8Src1T4d+FV3eaFmXH9F9IcWrEkkk+h6p4AUgbOIpE7ock4UYlZLQ8jPZNynYEg/ELpOWGqzcKgpw1sdkiH3ZH5BjG5E1zyrPLlHJr5sIIOQ/78UpZ6zsziZeItguNYDozLAqNy0HnzKWVSP1x3r5D0BOEdgRIO4h5qgs9/2jvYmvrHiiUzRSyqf9papr1s3oKsttBmMPuHtNSY528pkIpYZvzfSgPQNjHBq+lz8LHAh3br0CY0M3SbRtxla4IH9QGL1S2keusc9zuQMqm660PN4zvHFVSpKm+VTwnZN55EChrxHGL15pC4YWnlFCpXRpQOGjFXbdtYuBRgpZ1UFM08j+8ekYzZsq/dehoKxZOw97hDbLZSFonNRE3cvijqr8jNkqvJI3ypFCA78+Q9n4FTPrjHjk91iz4Bp5Ug/fIC45ICBAjL0r2Vco/T5dmTwNMbP6kHd/hZejPxpzEGdlul+lCg7myLAxzWndBx2qQ5z7dldowMTccoC5mlGspf8jkDf90N7Bw5Y1Ly4Ty5qHGU8TnauBU/TXV8rPC+P4jxcSI2TBzhvHV6MNqDeWMmWpxbTxbTcXQYUhlmeMlcQJq2Vaeyh2WASQjr0p+tdPuQa2h1z7jdIM57T+1tRhYHf0h9GURn6ric7jfth95zeIihs90dC9b/mxsBmkGuPlSsMXjyavRkP/pIxDGeQxePYmzdx45u9yLPSbY3SEbvp4sr9aXDXGElvfYG1P0TPQp6tMfa+xJgleXMgHop0HqECNy58tzrXr9G3jtwKR3De5aibGkdohb5DSxmEZFJVJv18GH2IpcWh3r/q7Sr3UvcGwD74Z8S1CR7odvCLwDVA94yRVYQPVc1wnoK7pIZLcgwYUUrpKjJxE6PwoJl2zWHfd5vGHvJRd8qHWuqSDICuhrgyOxY5obiDElrTFUk/z+zFMRLS13XOJ/daVgZjAAA0CAWIAAgiEQABMACAgAFRAACAAEaBAAAAAAFAAAAHXN0cmVhbWxpbmUtc2hhcnAtY29sb3ItMDEuc3ZnAAAAHXN0cmVhbWxpbmUtc2hhcnAtY29sb3ItMDIuc3ZnAAAAHXN0cmVhbWxpbmUtc2hhcnAtY29sb3ItMDMuc3ZnAAAAHXN0cmVhbWxpbmUtc2hhcnAtY29sb3ItMDQuc3ZnAAAAHXN0cmVhbWxpbmUtc2hhcnAtY29sb3ItMDUuc3Zn/////wAAAAMAAAF3oJBxFMMlIkVlERhkULhQC0KGJKZtE4IE5DhwyjAloAgRm6IBGTeFISUEXMBpTIRR5LIMTBSEABAA3IiB2zAwC5cMQIJt0JYsgRaNCzBICylFEiBSAjUxwBgEhJRN0ggx47SBIwJo4AAJmsBNDMllmDAQWCQggbCQSaZwGQcmHCNJ3LAx0rSJXABwASKFYsYpQiiSY7JIEARmyhAgiiAwiqCRAjJN4AJOHJJwgoREC5FgUTZuUCBSEiOBIhWQwySGwbZQYrgoYkYEGYUQCgKOwiKC0ogkE4klGsZlgRKAmBQJkIYhxBZiEcCJETFK4rBhwqAt4hSJABRgHIIsyKRRi0ZkhBhioxZMICgmIIhBkqgNDMRF2paA0riIIzlqZERpwEKRoZRsUQBwEbApEECQEyIAjKAhw0ABICFxS4KEGAaGEQYq2EBQpMIpoDiSYKSAY7QkCCIOoaaJnCQlgxBqAieBiRaN5EYkIZIk1KgoCZFNCShoI0AmAAAAAA==";

const chunks = {
  "streamline-sharp-color-01.svg": new URL("./streamline-sharp-color-01.svg", import.meta.url).href,
  "streamline-sharp-color-02.svg": new URL("./streamline-sharp-color-02.svg", import.meta.url).href,
  "streamline-sharp-color-03.svg": new URL("./streamline-sharp-color-03.svg", import.meta.url).href,
  "streamline-sharp-color-04.svg": new URL("./streamline-sharp-color-04.svg", import.meta.url).href,
  "streamline-sharp-color-05.svg": new URL("./streamline-sharp-color-05.svg", import.meta.url).href
};

register('streamline-sharp-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
