
import { register } from '../core.js';

const lookup = "AAAFRokZA+gYyBpn3WnkWGR5YyVVNoUnYmg1NUUUSVhWZIA7d1ZCUzc3YlVkVWJIWEUldCc0NlRCkkQUd0U0PEQUJkR1ImZTZlZoEHc0RFh1dDlUgWGBtYpFlmdkpmWRckNRYkJ2c0JVVlN4M3eIpZNWM1KEWMvtCCwIOwcBBCwwFW4VARHjCRwjAU8DOQgF8AUDwgIeHGewAaUHigQCKC0NAQTHAYEBWREDAhIHCArvBQE8LgMvAQIMkgECAQRwAwEhAgoB9w4GDQirAiMaBgsHxvsDAxMLAQoFDAopAgERKwUbBGsrPLIEWTTYASUCCAvlAg0zEA7pAdgHCQgLZS6JBQWIUIAlIRoEHJMTVyoKBzWYCAKPAbkCATcDDQICigFOiwEKHAECPw4BBuAECQlp+QHWAQEPvQEC1ghNFQcTHwJZA+g82t1sVj+g1y9RJbg7bZuJ+coSz0nxkUtagIpE+fzlXspg6qsqHr/29CUG82/DixPI1NUUNdAHIH85W4GOrtmlAC0zEnPlldjFZQN6nBYQjNY/Kp77/pmTOT/pqxaH/IctTZ1J63Wkmsk/NmwTJIGxBcp0x1WTMjPegnwjO0v+de+ezU9X3IAM+Rh6JSJsFs9dHBk7CN2r6Vc91wlmcYFNLBVx0IfTVeEwye7J42sAVA/Hxe2HHXHaYdYUfJ1xAX0M0OGR1X0/PU24CZ6aHkROyA+FFMmMlIIZO3jy5zHq4eUoi7gCoYzazfKOAsejp0Ok1D9D4qev8coawtNSpdms8tyIMnQ6gqhfsWugIFehakGP3GkIPfGfc7rPXMPQVVzbb7Py4PxhGRhPxAc+zWHtwYmxpUzdfzvrUuNmIyLaBGzkkTezO960bVh23Y9cuWArbHZ+nXpTDNDLxkZlwPveGTi4+zZLzsRwxwShUhrwewMBDtoXWmWfTxPbMcvlQ2bhBIodVoEOXE/jwHywIveGlMKadoczAbeeYZxo0DZyB0Zljj62hyw5GuJIEBeVUGMGe87ZSvAXWc3O9Wu6p5mv+i16RfastN2sRtKkVGF2wLLu2Njb7+takdftUouwdTIPnK2q9FllTOeCpbgcgkimkRJ/FiJdO5CSb/C0b6fmHOlL93X8ky3O++ci3D/4QSW59XOknVoTOBvEbG3PHWTywEM+fdD6FTGeGvJpuiTsTINorxD3GEoxBn+PNwoIgvFycZUgRmjfVAocaS8b5QJySwTzyeJnHbQgWDEGSZj1VBj1N4Fa06IaN+Uthl/SlWnOhzUrX5BFZSkHxe+aRAxsi4OiT+bzEe7i8oS8s2NT0Krj7lIU0256KIA4fd2WwXqi0tw8vmophpZuMJBfkDC4V7Cmqd2Qq0ZiSJv3SfU3yKplnt0dY7mj3hp28hdzdOagVM4RAwqHFEAcRJh/KYSUeAL0eCRiPFiPiNVNH4DNbmpvtOa+hZfdv/1rSmO5+Q0N5TlnINNMKn7HIVh43GLeZp9nSpvqgnc9eXhZFtdXvQLMFQvhTM9Ip9TiSAFIxDew60Yewg6lNBImZjys/HVdkql6Sb0W3wALHbAGqnmVT9rlbTL6qbbeI8yjhaFCaT62koZ6+CYG/a2rwgsODsTqe3G4vZoieHcZdKGCA+PlzU3ngtxFYY6yuXefpv86Gyk1/Tl0a+LrHdb7W+zmKMU1URyMHVXJeAqUO3WZWdT/y/INe6jOtu8UalAdkqC+qil6xDkbNqLI0kWHxzGcPwzLm6lyIlJO4lwKeq2B/xxWG8k4nXD8E92bWBkAIgACRbAGBAEAIAAKADAAQAUAEMRAggBYAAAAAAUAAAAdc3RyZWFtbGluZS1zaGFycC1jb2xvci0wMS5zdmcAAAAdc3RyZWFtbGluZS1zaGFycC1jb2xvci0wMi5zdmcAAAAdc3RyZWFtbGluZS1zaGFycC1jb2xvci0wMy5zdmcAAAAdc3RyZWFtbGluZS1zaGFycC1jb2xvci0wNC5zdmcAAAAdc3RyZWFtbGluZS1zaGFycC1jb2xvci0wNS5zdmf/////AAAAAwAAAXdDxEiLoiicOAxgkABJlmiTwGyZsGzZKAwhKHDkgjALtDFIJJKLMm4AoYGjKEXUGApANmXExCgYtiULgG0cBIWCtihiQkpCQG5hBkwhuEQagTAkQQGkyAGASEgZES4KN2JTppHBKAASgyzUQk4cpgwRqIELpiQMuEkQGGmEEGXhSEEIwiAJhmnYCGDCEIgTtZABOYDiOGERwIiigozDqGETyYliAGphMm6QyAUDIiAbNEkDJmLZIhLgiEAEtCmZQk0IQErZQFKiso0KJwEQkHFAEoTkgHEYAkoakESiyCzTwAkgh1DYEkmhhggcgIgcFk6iRoKUNCLECAXMFkDSqARThIRZSCjTGCgcEo7hOFHalCgEIUERpDHLCCQKNySMiEyUMIUTh0DigjETxhAKRSWgtDHQyAACxSxJImwbM0DgFGXToGgBMgIJAwycKAWDEDDClISjRJEZoyyZRGihlGVJKAGYhEEDBFIJQVAJKJHZIAHLEIIMqRAAAAAA";

const chunks = {
  "streamline-sharp-color-01.svg": new URL("./streamline-sharp-color-01.svg", import.meta.url).href,
  "streamline-sharp-color-02.svg": new URL("./streamline-sharp-color-02.svg", import.meta.url).href,
  "streamline-sharp-color-03.svg": new URL("./streamline-sharp-color-03.svg", import.meta.url).href,
  "streamline-sharp-color-04.svg": new URL("./streamline-sharp-color-04.svg", import.meta.url).href,
  "streamline-sharp-color-05.svg": new URL("./streamline-sharp-color-05.svg", import.meta.url).href
};

register('streamline-sharp-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
