
import { register } from '../core.js';

const lookup = "AAAEmYkZA18YrRqNtyllWFdEZCRoUzVjJ2dVUnaDcmdnZGiVZDKFeEJUE2QWJbgldWYjUmY3NTglOFQzU0Q3NzdkhENpbDc2RYMjZoVWZ1ZkM3Q2U0J2VjdZSnNiSTQ4QUMSdKlDRQhYuAULhAEFAsUDAgIoAwEWHAKpBFgDJwldAk/WBE8fyQFFBsUByQoNH68DFBAGRrEBZA4EJQEgdBEuwwetFQwSjwIwagMGJNUBqwECAQ0HCwGbAwwBFgEBPkIWewGOAQdkBAgVB4wKAbgPCrzPAVLWBgMJAQEOA/4BAgFSAglsFhKWAQobSgccAwEBjANUBAcNAxZ2oQEZLSUMChCbEAMF4wEDjwFABQgBQQMGAxwUmAHcB8gTAgkIFFICWQNfhKPKdAtDgGXmF9er3lfJag1zFU/WclpyYNr0x3RtISS80SPurYGgcQYPe3/5CsnP128HX1r50PYVXLIVG/6KxAm2XuZBMkPDzlUSrSwXiTwqNppKEQYXtkegH8Q/uNTD0ryBeyIlIIUOXnDDhginBem+084mzGlUypY3DuwPeu1Oi4bvu9ajB4ZOKT63Xfh/ZzHR7JMUukX3RUb0FpG+RNB15j+bKvuj6CwB26NvfNdoJDaDWwkXJ78HasQYRHAbOdnL79WLWGRI//8MrldjASULDW/zAQHcoX49SvE4naaTXJKDra3RMCz6ZDsYYfSRHb0IT0ZIPKAR9/NL7pbO5KaFR759oqmcALdZ/V1tGv+HRLoy17UQTkjf5r0NKocHjozgfNOuRJQDiMupbBjkPOYGd1mNqWiOzZLLFZO1q+mKugR7zlA/aAASOxpMgt9mI/YclnE0zT2K29LMVuQdHVXyf6zl7fUbkAU1I62sdSM09L6AGZ2p0AZWKPSd9sVXE+KtKoSv6yU8S6rfUZ95Ay0YZ+sUIM5lmHbvM7TvPmGu2Ehbc0IwyoqmGIdpXY4j9ONL4YLKjAE4k/WbrCZzyyIJ17EEW552XbD8h1kuAf0wOkgbGwjYcz5fTDOVAiZ90uuez+wYbu6pGRw1/6osHfyeoiqm3d+lL1sn3T6j3M96QHjCgz/StjmdytiQTdpEOWD6pv1WGXCKgX6e9ePdMWq2eNBxFL2Gbm+VtiU+2zn8cUdJMi9NCX6uR5yEektM30c0Pn0nVs7ZU0I8GfzZxR2+jgSVTKqYM0YIgTv6vzvQKPlYGbkWB6yF+rjZqMXixK/wiXoH5NAhZaIA/7HnQRIYw2uWT/Pncxz/o8wtStqsh+50e+KhWg6tpyGbFUniIN9lbgKiAkrELyuYVMW4NpwiGORodXjnUcaYFZDpYOm8ga6U1TJ/fpfVpZ5KEN6UqfIndL4Qx5NKPk6vf/7d5LwqwWFin+TufX+C+FR3PcmsUmZbsN/7AfscdRbtu8J9FTLMph69xnBV0BuWzQDsceaEM/uktQPNsnyWneCdbud/xtv2VgfGKzR7lvI2w24DAUuv78HsklAwknRD+qNUq7kweeQy2ssHbY+SzSEviJNp8CD3LIlgCemVpNSdaWlWBAQYBABBiSIQCiAAIAAAAAAAAEAMAAAAAAAFAAAAEmdseXBocy1wb2x5LTAxLnN2ZwAAABJnbHlwaHMtcG9seS0wMi5zdmcAAAASZ2x5cGhzLXBvbHktMDMuc3ZnAAAAEmdseXBocy1wb2x5LTA0LnN2ZwAAABJnbHlwaHMtcG9seS0wNS5zdmf/////AAAAAwAAAUTahmTTlCARlEmRBCQElADCpBDSgGVTsgQbpG1EggDAAAzQIIIJJmEDpkWaJkLEgEVRAAFKsCjQFijTCCAhqGWTsghAAEVZpiWYJggTwohSuASRuAAZtyEhgADKJElCsGSLEE0YAECYqAnbMi7IIk2Rpk0QMi2akESDgGiZMGSQMCQENoFREEmYkCxbIm4BuAHTEALDEjKiJEqZFkhTkGUCJm1iCAAcpFBglCTLJi3ZtARAgEwBsgSjlElhMGhBsAnYMgXUJkhYFoRKIEzZlIWYAgpgoGWUoiAIIiJEmGmKhiAJFGratkwksy0Tpi3LokTJFmWLAEQKgghDlEFLgGyIgEBDJIhDsE2RNGiEJmgMkkViIGEaRghZsgikNm5CIGTjlEAQJmCaCEBjBiRLGAEBtQnBFk2JoGnSJCQMJmXhJBDDBgwAAAAA";

const chunks = {
  "glyphs-poly-01.svg": new URL("./glyphs-poly-01.svg", import.meta.url).href,
  "glyphs-poly-02.svg": new URL("./glyphs-poly-02.svg", import.meta.url).href,
  "glyphs-poly-03.svg": new URL("./glyphs-poly-03.svg", import.meta.url).href,
  "glyphs-poly-04.svg": new URL("./glyphs-poly-04.svg", import.meta.url).href,
  "glyphs-poly-05.svg": new URL("./glyphs-poly-05.svg", import.meta.url).href
};

register('glyphs-poly', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
