
import { register } from '../core.js';

const lookup = "AAAElokZA18YrRpIxAGMWFeFtVNGRTY0JzUlZjiTg0SDV1cVc1kmZBJXdUNFU7VTJiNmUyt2dpOVU2NUQmFVZ4RhcUdURCUTKGZXNBU0NDeSY4ZUe2Q3R2VUZHWXZGGkVogihFdTRgRYtReDBR/OHAQGTQETB9YCAQEC6wEOBQkEowGnAfACA68DAUADBwm7B/4BI6QCBQIBcawFKwkMRCYODSkGGwMLBAkK0D8OVAMJMgEpmh6vAQU+A+MSNJkhAwEKBxgDAiUjCg1i4gUElANBAgUEAQoTA5QJAQkfnAIjDhUBBgEdThKaBwEPowHyAgQqtlVzBRHZAwgWByG1AQ0EAgaNBjmPDBMDRgOse6oBHcYEhAQLVxQdCZEBEwUCWQNfddoYseagbpi9+iPr5P/JlfqeB8RxYSqmuqwwpOztvtBv0WrdCPTZ99ucowMb5LBD5tQS0DKpMO7ZP8USlqkyfyC8Hf4HKn3uBzz3zGl+HeAbkdyIYJPyetrPMlnoZg7a+K/NwwT5S3NJsZ+UNSeiRN99DxJvRYFKT/921aI8mCMBaaoLGsplPOvmhQyeIGfXFemJrua2zlFJgmBF/xeexjKNuDB9vYG4aC30zc3EpjQOk19U9udO3YVN//HOboKjbcyGRNL4PuJP0hxft2UJqwEYnKxC+s4AWhe2zw+bwc/tLN+tf8PLLB0wpKqO9V0ziktOKu7s73B6Z31XiodoXcoio9l/9nxCB8TXznfKNuRk+6/drB0GNffrMocYVeLs34CWGbrsjjbmxyEFV6l0by+djiYdiTpIJazWJu7VyacDRJ95eIvvtp1LuKDstYmYcYOKUMXFWIB0vClyhCLp2/VwSocRvlBDcRwVqhlSnTsoxkfZCVQZgQGIo2msc9MGAfwk7+/M1dPwfLLUlpZZ0T6KBaduxVUbFKDktBHe3mqefh9AMdtg862daa5obw7nohvfLq0LUypuB/Mn0LwWRCEb52UUhDN7AUatWtLgfyq/A04VfOU+Fm2jTJvQrGJNg60JjD1hOa7EKizNe/Yv+hCuhAYzvphX0jOEt5AJpUq28pStWXS7Xr6SVob+aHUVWzRuf7tW84xznVXjMFYjku8KRidRy1v6gjz17gdcP857yi8VF53Dh2yWMuQ+nHP2qb3kJKa1GgSbP3Rl+0ejnk78CSYitrJwFhBbWlyp2KtxITg2hTat9D4Xiv0YRJDdFIbH+SsVe7rQYZa1GO0TcqZBR0hY2wBk/d/0lAjaN8Nxaq+SsBzNdp0N/8NB3xnLyZMvMef8PksbT5ffvn0o4gR+LUxH16t6JTk+Abl3YwIY8BWmXkxdvf9KPwhwQx4sJUgnI1ZHrxiWmniOOUrQPJVG0KEQGL/82Du5xJAHhjslk87jlVSoa2m+Voc9+Tk9DSBbSiAcS4NIi9zXxn/99CNUBjvMosKmow00enThLFs41yttIeR+k5Xy5Mp14q7YXYHGebx1kgMH+wEBeALLc6lIAjR75gB/AI/W0WahYEzp9BnCksuBk5EI++nppcFWAICAACDIABCSEAFBBSiASAAAAgQMAQAAAAAFAAAAEmdseXBocy1wb2x5LTAxLnN2ZwAAABJnbHlwaHMtcG9seS0wMi5zdmcAAAASZ2x5cGhzLXBvbHktMDMuc3ZnAAAAEmdseXBocy1wb2x5LTA0LnN2ZwAAABJnbHlwaHMtcG9seS0wNS5zdmf/////AAAAAwAAAUQQMyhhNEFZsGxCBmVEAE3KIAVCwmUUkkmUJAThhmGDwkkIs0HatgEQJS4QNknSkAURgEXAkkkTBCDIohAbkogCJSgLJAKBpmAgl0RCsEHINCYKMAVSMEoKNmRBqI3AoE0EtCUCEkggIUUAMGQLBiWLFi2Dxm2gAjEZNmBEBCAEsyxKJiiChihQFk6AtjHUEkpbhE1kxmiYgkHTIiXIpiQBBC0CNQHYomBKpGBLEGhCpmBEIjKLklGDtEnbECCRJmrRhgBjlHFAAgRZqGHLsICQgGlYIGyaJInLsCAiogzJpE1AoC0ZwY2cEm2QBEASBk1QJADRFG2LMCVKpkhYtA0TEy2Spi0AEygCgCyIliWKBgCZAARQpASKhmUKAW0DokHDOGQTkgCAgGTLEgKREDHIFjEIyCVLtGkcAEFJoCxTMkHYtAEAAAAA";

const chunks = {
  "glyphs-poly-01.svg": new URL("./glyphs-poly-01.svg", import.meta.url).href,
  "glyphs-poly-02.svg": new URL("./glyphs-poly-02.svg", import.meta.url).href,
  "glyphs-poly-03.svg": new URL("./glyphs-poly-03.svg", import.meta.url).href,
  "glyphs-poly-04.svg": new URL("./glyphs-poly-04.svg", import.meta.url).href,
  "glyphs-poly-05.svg": new URL("./glyphs-poly-05.svg", import.meta.url).href
};

register('glyphs-poly', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
