
import { register } from '../core.js';

const lookup = "AAAElIkZA18YrRqWqLC1WFeER1SFR2RTI0kzWzYSQlV2VFVSQyV1REVYljVWSSZlRVVlVDRac0dGOHRkVFaWhWQiRXZTMzVLZlRDVjc0QxZyRWKEplZFJ5NUdlRplaM5glYSgiKUVwJYswXcCOoBDwZiVBr1AQgfdgQD+gQIAcgFFhABAwQzJQWJAgoEGCwCGgcGTBISCAEGBPQKCg2+BCYCIyHkAgLYATn+AgQBIQUPwQEHBgf2AwgF0AEyCDYDKgFXEAgIL1QLWb0RKyUTCgELWZ0BBBkBAQMCyhcGrAJeBAkGVxn9AgEKBAkBdwEJBxfrBC/ZKWgZMgVBBQnbCgQKRwQEFcwEngEOPgWJIOoGAicrVYQJBQ+MBQMFAlkDXz2UCSF57+l7fpvXYd2Lli/SngQHYixblux1/8asOEi9JmjLE1VfrwS0f/WQPzfm/RxO9K0x8IVkBYmThJVKAESu8ztwaIr3kyVJnd9GfI5zfx2kzNJBpi825gN3uObmTRcUHGFlWe3vhg2/PYtwtjKHrHEuWpJgltGS0/FqLwgtDxc5qTymgUvkvtAq+bfWf39VK+m+RyLifxZG9zsQ9uyuCtYninTVXWfRoxmc5FTPWO9Og3QNotS19gcBbSq+w0rroDTalXwXRSMqliwZTzb1QznfM0cf7pQ/9DmYYM22kGfmvYoBoM1cM081S4oZ7qMBFdtzURm4NAYFwgCHu7irMj5LrJM8JeuhfANby1SmvkplJRijaaisNp3jzkqT2sdFrYUNEfipwc2vqhA//k1s9Ed9dSJ42VAje2glG5x+XSbLzpKC954V38PQQM21mJ7G7Llb5afFdeQnTgNWNHLnOglJTNuMzJamndn0plfsXe2FKLzKZtkm5CyGSJ7/d0PziFr5OwF6Vq2sPK0XPvKeg4cjhKnhqqGYye7+FZLaByy9ZavueRZLViDphte78s4+RA5m+mm6tYoh+v9VmHr6aftbdv+jc5Z+brZeJyjJrsrj/IlK5mUkPAzn00QcIfsrqfUSNu3JrpOmAbHO8jjk/XQ+scSi3WQY4p0ZVBLcID8tR8WWcf00R85xFfZ7MXNSG6OOcRzDFTwzh0GCru8JgQsqxfpXWXtCfzJG27zPMOgHU8RLYA7zb47EB/r0xb4YI+TnT5t/3r9W+MxvIv9ZHZduCQcJTAEGcP/ZzeIGo6Dfa9D5rcvQkALKgsNvvg5uiPbYetDYJN3SagYASNEbjRhEW8Rhc0Kfzl8PbT19FISB/IEH5BanXlbevSkwPmlpctvCHUOVss+Bq+AR16IbdJV4TBSl0Psy/NrdAER9XdJ731eAxNWd5GiRCFpg1TCqI3pISh14bjCtBPseyyAIGry2AgGdzOkzEBgdojJMrZO5vGNImyzX57fUOW1qtu6AbpHGdcow6aOlrBU+ssoYG4R0IboysK+6fnGpNT4qTjvi2H3riQHXqZKc9AJQL1F2n68VCLDG/IyO3MGDEhvDnSca8BhwGOCP0IYHXG9UKgPffZTfmgukWIfHIOzvVgDABAMAAgAIQAACAAkACCoEAABAXBAAAAAABQAAABJnbHlwaHMtcG9seS0wMS5zdmcAAAASZ2x5cGhzLXBvbHktMDIuc3ZnAAAAEmdseXBocy1wb2x5LTAzLnN2ZwAAABJnbHlwaHMtcG9seS0wNC5zdmcAAAASZ2x5cGhzLXBvbHktMDUuc3Zn/////wAAAAMAAAFE0jIIkwYlwcZgSyAmQRYskaYNACMQgwJEGrAhAJNAwxhtQAIJkhIJigSBE6QloJYEC8YpS6ZFgYZAmyYMi0QpwjgJW4Zk0AZugiZwGqBoCiRM4hhqwKJBi4QM4MIliIKBE4BJiBBB0LRl1KBFCTaFGSElUjJMCQSImwYoC7cki4IkHAJEGzAAgSZgUhBqmjgIS7AhSbYwxLBxCiAMQxIQwKZBUTAK0yIAhDBhFIIMGgFCQKJJwZCI3KIoS5YFQKZNkzQsEJdNobZkEKBIgzAFiLYomQBsiSYCCUQlCTRKEcMoUkAJE6ZNUYYpixhJWSJoWTYIAwBmUyYIwZQkwxRCQTRoChZM04QswJZg0DAMGbJISsQIQIZg2iAxi6hJyQAECwBAmghsnCZhUDgRSSYtUMJJCbUFSYBlA0ExSBJNC7UMUEQMAAAAAA==";

const chunks = {
  "glyphs-poly-01.svg": new URL("./glyphs-poly-01.svg", import.meta.url).href,
  "glyphs-poly-02.svg": new URL("./glyphs-poly-02.svg", import.meta.url).href,
  "glyphs-poly-03.svg": new URL("./glyphs-poly-03.svg", import.meta.url).href,
  "glyphs-poly-04.svg": new URL("./glyphs-poly-04.svg", import.meta.url).href,
  "glyphs-poly-05.svg": new URL("./glyphs-poly-05.svg", import.meta.url).href
};

register('glyphs-poly', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
