
import { register } from '../core.js';

const lookup = "AAACaYkZAbwYWRqzxALIWC2DhHlYWIcjNWRThFFDaWdDgzZjZEp1JYN2NWk0JGRkUmVRV2OEA3FFVGdlYgNYX8oGAhl0hgHHBBPXAgnAAYwDAzUEBg0JLQ6AAhsCCdYGUfMBHwQHAcQBZwwTE1XLDRYgiAERA/ABaCAHAfAgUgIHDQINnwEPUAoKAicsQgMEDZYBBF0cEg0zJiUGwAFPAlkBvCPmEG38d1+QyVlhNF9JDobXFcqsX5x4dwsXfH68tgUl+hTBcM8Hz5YW7iyp6V2B65wclY1aS1HhawtZHt6S9N8bySvooLU/7SGXu2BEcuV4ssV3he5JVTOgsmFJiOXQe3p1rLwsAATtFjIpGrNccKU9NVvIB+bmtcZIUPcvtmxDegFQ9ez9GVryW6baO2ZKTuG2oZ3PhnHKq2k6r1OOUw4+cxuH+pNEm0AgFDkzrZttdHPS8CnGSGBVNL1f0TsMUyanRYKkSW0l9Lq1QpO6TaAspBYKYzPa6w4l5L9avG/ye1PT1FL+3+q48YScKTMZtl0ea6mH8VmqU1OAS0rQYUTEuP6eNpY+yfLzw41MUN6jrEE7ArVscKsDJGQopDgVrR/9OciB40o0eqFa1h2ULGfPfFEOcuZDc3wUFzb/N/RQFb8vBlcBioyjlTI6onM1SEymoM0ut0FWkBgNEIlYBm4SSe64Lgi40SD6iO1ZlftrKQJtwTA0WTy+EKVtOsDdbfzcylJsn5Ayu1MjwTGf9uv8zqUQ4XgYFGdU4JBnW39Wwp8scANj1mux/ccZdcBfUoEouZxjNh19ZgTmz0wBIEAACCAAQAQYQAEAAAAAAwAAAApvdWktMDEuc3ZnAAAACm91aS0wMi5zdmcAAAAKb3VpLTAzLnN2Z/////8AAAACAAAAb1BERFJYFUAVaWFRUEBUQRUhRBASERgAFCAFRBAYaEQUmlEQEBAChShUFQEFlRWUhQBVoUECRBYWEBAVUBEQgFGUEUEQVUJRVWBUUQRUQUUSFQFRUAmhSFUAVRIQAZQABaVQACVRQAEJFAVESZVUQAAAAAA=";

const chunks = {
  "oui-01.svg": new URL("./oui-01.svg", import.meta.url).href,
  "oui-02.svg": new URL("./oui-02.svg", import.meta.url).href,
  "oui-03.svg": new URL("./oui-03.svg", import.meta.url).href
};

register('oui', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
