
import { register } from '../core.js';

const lookup = "AAACZYkZAbwYWRpkgQCZWC2DRUZpGWM1ZHMjRVVjUiZXk0YkR1V4RGZzcySVZYFnUlVsNUgyVUkzuFVEQwJYW4oBJTIHBpEHQLARBSUaCgZhAboCAV8EJg4DWBIWAogEGQH3CwkHD0UQDglZxQEUBARrB60BGxauEwmMAdoEFx8NAk2dViUrAyABAhW9CA8HA0GhRAsKFgUCAwQCWQG81zRsEOFtbRYyOMnr1pvt7eZf/RslwUmWX9bmTdojtcfIPmfjbJWsOyBgnr14ya2l2jRZX5AQU5zGuHOmLCZ3SjvrMBLKAwYDoB1LSfsHOoH6z4KTcO4NGRW+HVnyB8hbdzSgnOYQLzxmBCxaPbmJLxCpSbYZbcBTLE73DgT2Mt43WaxCn4YzUGHQmwFn8KCjUvqkznWHikhJfOHTcBRQFhdQtaEFXBq2O7z9qRg+hi5MC0VJ9Bus/nxfQaB7KTok1PSBiI3+a9+lYKsURFmVunjKybhf6XACwSzktvw0IzMOhaqmjLWT6IAfQ/FR8oF+ekxYKeHrS62cz+64WZAz+s9jdZ+/h1N6W5ayRKdSOeVkUHfPa89afwyj5jkBUzZjiFd0wn3/7cHqJZK25nCrayBTUrshssNbpEGibwY6bfUeMg4zFGZEXWdt3gK40RUOxbWQ9Mbf/EpI4AsKl1opzb8YXStV0vy3vB5ya3PE/T+6wGmcQK+kHISVQ9ByseW7pfGNewhRJXNsSHqhLChhnW02jvIXVHhzMXxKVbw1FZDKcW42FpTdnyhaNQBW0e4U7PNT3Blhsy5TKWNWTAECCAQgMCBEAAMAAAAAAAADAAAACm91aS0wMS5zdmcAAAAKb3VpLTAyLnN2ZwAAAApvdWktMDMuc3Zn/////wAAAAIAAABvRARFAEQQJCBEYGJQhAGVUQRGFFFFQEFQVZRgFAWVEViUAQRJAUVSABRRBVIAFSEERAWQAUBSUkVBFABVFmAIUQQglmhBGSASFBlUFAAARYUkURFlWFQBEIEFVBGYGQFQFFVVBSQQFRlRRVlGQUUAAAAAAA==";

const chunks = {
  "oui-01.svg": new URL("./oui-01.svg", import.meta.url).href,
  "oui-02.svg": new URL("./oui-02.svg", import.meta.url).href,
  "oui-03.svg": new URL("./oui-03.svg", import.meta.url).href
};

register('oui', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
