
import { register } from '../core.js';

const lookup = "AAACf4kZAcoYXBpZ8njaWC5ThnBDZUOzo2gpVkJEV1YkpEdStWNLNXo1MxJlRSR5JlJFNJNEZjQmNkpydTVmWGYCCy1A9gEHBAsIAhABi4MBCPED/AUX/hcGLAMLERjiCAJoDQIBB9YmmQIEAx4K0CkBGLR6BQG2PRURBgEDAQVrPwcFG1kSAiMSEQ0BA6kEEAqtAaMBEwMOARqcEwPxAhxNRQPAAQUCWQHKKvRplRFUVVy5noQPaW5PFaEabjLzRGIYPHZ+4hXuJTPfLMbybj/oF4h3IoOWVSGybF7LLH1SVe18QrOVfVOUqFxrBXZJI5p9dRdhLyYa82wXcNaR+Yybmeg2iTSwEXQNIvat6XfIILt/2TesSIyz5nnuXZyKHFsHkh6ux3/n0wAZhvmm3A4R/J65a4GQBzD3nPS/BUHR7zecxV7AJCdsNgvWb0S+Ohe8HaDjEtRlNTFz2Ds6B302EoWtA/My53U0qXenKYri83pGXeZxMcvQX71yHeOBJ67vlb/3PXXtMctOqzwYR7Tsgcz/M2mVusBfv7GXFMUCB5RrIZGYycp1P6/4YG2svmLBF62eUGG9A7sUMOXC+awZ0qDCd40HbeRgh2xtZZWSIpXlqBCpObY7WaeEVIyT9SqdMPk+YGMm9Da+TKqqkDCcIRxEMGIshMBsp7m+Ql1vlMW1ubYkh502O1iwcUbPPeYCHx5BaVjD5C/4/tMJ4+Ydc8C5jLbL1x6bddFhGD4m7hvNxSER2SiCRcPxsQhEQMnYeT7ScCfWlNm5sElUadN5qYClpx9eCfnIDR5wfho6sXyUBWa/90hAx1/IftaFUJTreB5MEAAIAAAIIAgBABIAAAAAAAMAAAARYWthci1pY29ucy0wMS5zdmcAAAARYWthci1pY29ucy0wMi5zdmcAAAARYWthci1pY29ucy0wMy5zdmf/////AAAAAgAAAHMJBhRIAFRWEAEUEFpFBBmAAaVCEARBERCFlAVRZhBQRUABVVRkAAkAJAgBABUVRSWWQRBQgFBRkGWhRRYRVBWRAgEEQFYoAaVFaEVQRJQZUBRRRAQBFhVVUZRgZQUkVQkJVUVCJIIREUGQIAUpFFBFaFICAAAAAA==";

const chunks = {
  "akar-icons-01.svg": new URL("./akar-icons-01.svg", import.meta.url).href,
  "akar-icons-02.svg": new URL("./akar-icons-02.svg", import.meta.url).href,
  "akar-icons-03.svg": new URL("./akar-icons-03.svg", import.meta.url).href
};

register('akar-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
