
import { register } from '../core.js';

const lookup = "AAACo4kZAeoYYhrWr2WLWDFkZFRXV2dGhDU1NZIlZFWDRStjWFU0djR1JHVmdkRlVmlFVmdEM4NkV0RUN5ETODczWGYBBAsLBBqDAgK0AgdEQwcOCvQEBgYMAgEHsAEYAioCCwJtAr4IARSqAQsEBAQJBtkBBwEJrwEY8gEuPB8nDQIEGC8QtRMdPQIw0AEIAg0FCvgDFWFGOgcBDS9xAfQBCdQHBQ4HAgMCWQHqTQV2C6MHPtQxSRwT0pVENqR5euj9IedcLqeJ+A8D3VtgJRTMr5A8ecEhC6Xz79KESiQNpp+E4Pfs7z+WkdJb4cXYanvJm8VklgH4U+d4LWqz3XSG6Bh+CqnhoWiL9uBAfYU/3XiNgWXQrTIcd1dyWBs36I60mlTXdtUINQtKKyFGL8SvfLdQuXmMYvDgJ/uwtRpfHnC29Yli7bf3SIm2F2w5mk1gYEevcELpLLdRs+1170N1bDECqhPQPqDGP3ZvpZWUId5KMMkLi4veTJX7l9ynGFVKKC/mmChngog3mvtHfABnrsxIXeMUfmLcVAf15jU3UImtxoB0Uy8g3k6T+buG/3P30yGSHGwix3SZYtmrld72dXimSYF0r2j2PEEmnG2qwUvc7XJzV6rHBape0bZdaZgZbHQarWRPmBfLNBJ0CkOHwc58A+fhHvZnUMCbPgGsJJK7ISAnoKPSv24AWVe7ko5zdxOqKZhReMIZTn1rxO11ReGnd2ceDcRY6OYEVM9ZYJhQM5faKC2A/GYydVcY4sC4jmAnCZoo4Ep9IctUEv6hK7XfaImMz/dJjtWVRytyy5DcE2JeF2AT/J/Xaw4CWJY6H3qn3U+L3ibJDw/14GcSucvd8DS3822ZfiObS+mW//YbP5G9NE0AAEACCgAMACAQAAkAAAAAAAMAAAAKZXZhLTAxLnN2ZwAAAApldmEtMDIuc3ZnAAAACmV2YS0wMy5zdmf/////AAAAAgAAAHuFBFUkEIgIASZIZUUQQIpQVSRGWQRlWElBIBRCEQERCilBaVkigKUKEpEmUBZAKZFAWVIEZUkZEUkACFUQRBQSQRAGBBJiUkUGFWVAFBVRFViRWiRRhkSIIUZCEAEUQgJBCGSlRkEioFBERhEkBWRFhVRVUhQhARqFFQgAAAAA";

const chunks = {
  "eva-01.svg": new URL("./eva-01.svg", import.meta.url).href,
  "eva-02.svg": new URL("./eva-02.svg", import.meta.url).href,
  "eva-03.svg": new URL("./eva-03.svg", import.meta.url).href
};

register('eva', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
