
import { register } from '../core.js';

const lookup = "AAACqYkZAeoYYhqr2jABWDGFREcVdWc0ZDg0Mkc2gzZ5RFO1WXZhhGdnh3eVRUdTVkN1MUZJUzcyNEQ1FCUoFXWyWGyPAfEJDgHFAQQgDhfrARAJBgcF7AMBCAOPAgWSAQMCywELAqULBgQIhQEBtgeTJBmzAQ83GGAtc0HOAQW6A7kC9AED5AIIGi4GDB4wKAoDFqwEBBQM6AcF4QE2AQoBBAcDDQggAYEFBwl2vBwCWQHqtwiaJXSXxltLNGivpWK4pSyZksXMqvBpy12Yo7P251TdK3ULAzdJej+2y3QZ4b2JcohJIekm09JXKVyhVGr1qxT30ovi5sncYDJnSmDtem1QUCGqHj+2bDmMmmtndElqB5DgqQtK90D7Z3O73KefQROWYgB40TfQ3HytpqbhNfwglUYnuXmvkYSYT+iwqrcnYEiLyZYCmLf4IZunpxj7C93BoddzUe3F6DrgAQebfS2tlG2YjnYt3nc+1dI8ZAnM9sFwfXbZEzOAYlBHIZX8DdyVEqo8RSa1d3Z+BKD/K2CbVaBXx+3vbyjE+6xgNugFX9Ivjg7OZ9119o4YGnk0v/Xwy073ld1yZHOGixqQdcALAsEXXt5HTpo+jDchR8fCYjSTD6/XMhuHEjCOZrN4kthX4XxgMegYdBcelsZsXS+BPliBIgrmAOd9tShDUA+JIe0u0JHntiFefhMxz6N43pL1r5/fp63+KIl345jgi1TviSQ1Lygc5mVZ3h9Z8xdw4HUcxLea96oPTPPEI5yEWNUKSn72+fZbA2tP+FFIShMeU3zLASQSeYKFSgWGHA2AYt6NTXhLTVRs4c+0cj9u3UJ0U2hnienJpGh1l0NYbCBX4LuuRNp0/RnsuZUTe8Dv1Cs/mRT/licbu02AABSAAAQAABBkgCgBAAAAAAMAAAAKZXZhLTAxLnN2ZwAAAApldmEtMDIuc3ZnAAAACmV2YS0wMy5zdmf/////AAAAAgAAAHtUUBVQaEARAYFWAIUWCmmESkAUVlAAWFUJWlkVAYaVRBYFEYlIhoCFEpEAQUFkCiBlEFURQVEFSQWQQhImUYYgZBRIRFIIEBVWYhGRZVGQGJYEohkGhEhAFFQBVBppWBRIEIGJqSEUECRBQFREREkkURgkERYCGGVEYgEAAAAA";

const chunks = {
  "eva-01.svg": new URL("./eva-01.svg", import.meta.url).href,
  "eva-02.svg": new URL("./eva-02.svg", import.meta.url).href,
  "eva-03.svg": new URL("./eva-03.svg", import.meta.url).href
};

register('eva', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
