
import { register } from '../core.js';

const lookup = "AAAB44kZAVYYRRpwPB2WWCNCNDJkkyXDZWYkMmdFFCqVNlJkN3ZjRVVYY2NKo2pXgzZCBFhMAgEHAQcPBPsCAQICr20HF68BIQsBAfMBiwITBgaZWwEfjyFJCQUPKHYDPMgBBgYPECUniQMVCA0GOvYkA+QC3w8x3gIPA3ZgAgEeBgJZAVZZrJSKH1bTrYVh7pyyurPoVzFIYZSAkh0fQirQHxudquoWR5v32l/aYEhkzkXTX22lHhGWbNwFOzPP8rqXx3c58Kksk9K+QxIbq2VidczQ0JtBbkTRW1bAJ4GnjX5fxginveYRCLss6CQMyCS7G0p0TOg4vF0p1u3Cc1syR3HvQfQOaR9wTzVmif6xFSSWs+M3nDJ/uBQqaxf3D0c/BqVn+8mQ9HTZf2cRhXlSGufRP1lT3Wtt6twPxkN8/XJFN6PXkPNEeS5RNjCXUB9XWFSD2lmUbXpXNDmj4Kng6tyy0+c3grWEWDF7QgKEOlvQSzPBefPDkWGq0tZ1KVeJMLBoMOaKiPNmbZOoiCmg1uFQikw4XcYBcgrfaP6Clb+tjA7+Yh+Qh416aZVtvnG+NcFs3Np8B86c3HMuO5T68Z3PGLgdltF4Sjw7XeTyLqw11JW18qbwdJJJKAAICAQAAAEAAAAAAAIAAAAScmFkaXgtaWNvbnMtMDEuc3ZnAAAAEnJhZGl4LWljb25zLTAyLnN2Z/////8AAAACAAAAVhARUQAUUARRQABURQFAEAFUUAVFRAFBBVQQBERBEEBEABAREAQAEFFEUUEABAEEQRFRRAEEAFEERQQRREUERUBARQAQBQEEAAFQBFRBVRBBEEVRBEEFAAAAAA==";

const chunks = {
  "radix-icons-01.svg": new URL("./radix-icons-01.svg", import.meta.url).href,
  "radix-icons-02.svg": new URL("./radix-icons-02.svg", import.meta.url).href
};

register('radix-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
