
import { register } from '../core.js';

const lookup = "AAAB3okZAVYYRRqO6BHRWCNGFTZVpGU4NIVFRHdFRKVXJpQoZjWCKXIzQ2VxKXYiViVmBVhHBRYoAyUfDZ4+Ag4NBwMBGrgEDAgEAu0D3wM2FxYHFIoMZy02AQnUBQGbAQogAiv0AlgGDgMCAi2oAgGtAZcBAVMcRAEmKgUCWQFWFLu+9w+IVFc7edA5cSy40FkwyWA1wswz8qWKa23yHYSmkDkIxpKoZl0p2qNyz+F81FBIoAGCvkdtNf5ZrEdWXTYwFX9tYZRnaXobH3UR3O2bLlJKlVOWbq2peXFrqeoxOENitY2nX2yU0dzTUNKcQUyUHSfZdXfnsjWXD+N4vM7zpcdiSLHwXyqKDjfaYR+WQjebwN30clf6lN+rkTHRiZ03o8bvvbD+ik9B0FbIZxG1XWiSPFkf6P58NNzgeh95H6obhVjQ5hYSk9OzGMPygq3PYV8CLjgpS+DawRq/RdI63GT7UaxE1inmWyTobXMGh/OVZbouV8FsCL6nMnPzaA6FjJZb15w/V+pE6sZDuJyJW42AEXT0iCzOlYHxB/cFF5A/0Wkwqn4yG9YKO3DT6Na7HiR7s4PuO5DndIRFJEJml0q6dNwM5H+yk0ed8DNYHyptTNr9SQkAAAACZEEgAAAAAAACAAAAEnJhZGl4LWljb25zLTAxLnN2ZwAAABJyYWRpeC1pY29ucy0wMi5zdmf/////AAAAAgAAAFYARAFFEVEFRQAEQAAQAQVAQVFQFVEUFERFAQFRUQRUVAQFAAQBFEBAFUQQUFEAQVQEFFUFQAREEBBBABAEQAEQBFQRRAAEBQVAQQUQAUBRQAUVEERBAAAAAAA=";

const chunks = {
  "radix-icons-01.svg": new URL("./radix-icons-01.svg", import.meta.url).href,
  "radix-icons-02.svg": new URL("./radix-icons-02.svg", import.meta.url).href
};

register('radix-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
