
import { register } from '../core.js';

const lookup = "AAACq4kZAe8YYxroZLYfWDJDZUQVRXZCJDFFU1M0NXWENZgDZ3SGlqYzlSs0I3VCdIpWZDdFR3FUNUdKelZmVFJGBVhoCRYbKw0JGzQNToUBAQUNNwMBAwMBChUCJTQcEyAIsgHdGgE/DANsmwKCAwj6EQufCgYBNqBNARcHBA7EAQKdAdMvpQEBDnxOARUB/QECWi0FBAiLAQjUBxO5MdsBGjBrRQoJAQEeFBMCWQHv1000dsbQVtGMcebNIcsLHTSz9EY9QhLBp3BRbFy5m82d6Nyp+GVb9jS1url1Nuxqb6wPjLK1Jj2wyMyvUNvujzppIe1v2W/YhteyMWUhj6G5yYO20ccTw8o8J59CwyJT4sYYZqI5iEVxm6M9iMJYq20qmFFbybeH1r3DU4OvBuO3rl1AnCTrZHFhSJHLsjDCGrHnEqQ5h61gEIGiVbQeFUAib6GNttC7ThA8YfLFz471ODijlGxXEbtG7aHC4jqZdx7XeHK1uoH2UmHweYYq+WX9Lu9IPP4ICzCcvkiAm87GXX95fFNcR4lRKu39rFeRh8k8sl8j9Fbr5aYVet+sEwPU7TzjrUH3SW0QgIhQzmoOpSGUzxVgriqndI9BEnfDow+tiRLyBxNx3O1znRIaQ143UYnYes7atyWY8vtcV9Gy/Ng6F1pcfjA+cbgClIOr1uat2F/3Ubrvf2dA5vZteJMbJSpEllGTaZK3H6n96cKuMJheWuRLQCq2ZZQbnzJnP/OIfQS19kIJi0ikHwC1X+dGZ9y5kY8jr0Wdf8phLxCxUbLT7kXyQQ5YuwGXl9XC6+veetDK2h+Twbi2GyjKcrZ1PEe1g0iIcu7nexEobS+wc9Axy86CNjFNQa0C0IfBYFCOVwXfDCKWiTJt+Y6bTYCAIwAgAAQxEBAAAAAAAAAAAwAAABFmYTYtYnJhbmRzLTAxLnN2ZwAAABFmYTYtYnJhbmRzLTAyLnN2ZwAAABFmYTYtYnJhbmRzLTAzLnN2Z/////8AAAACAAAAfKVUEiWARGBEhkAUUllEkaJABaGFRFRKBUYBAlUGBCQUpJGZkZWSYhWBEgQBEYkCkIhYAVEQYVBkRFFCmUSRiRBECAEQUQChFSVVQVAVRACVgEiqASWIZEUgUUihRoJQmFQQkppQEFCVkSRCVAEFRUEVGGWAkRiVCVKJQRkAAAAA";

const chunks = {
  "fa6-brands-01.svg": new URL("./fa6-brands-01.svg", import.meta.url).href,
  "fa6-brands-02.svg": new URL("./fa6-brands-02.svg", import.meta.url).href,
  "fa6-brands-03.svg": new URL("./fa6-brands-03.svg", import.meta.url).href
};

register('fa6-brands', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
