
import { register } from '../core.js';

const lookup = "AAACpokZAe8YYxq4TE0LWDJ6Q0YzOFVUYoQ2ZIRhNGVEZXGoRoUmiDJXVmckWUY1ZkZFYzMpNDV2Ezh1FVtnZCI5BVhjjmIqBAOUAQgGBAIPAyYLASgJng3EAQIEFAjZAV8FKy8NASc6PDzDAUoJUYcFSJMESTYEBgkLHQYBjAcGmwIBBAwSARAGQgIDAQWlEAkCEAUTAwJBmwIJ6R8uOzML0wECKRQZAlkB7wPMWKK2UjydaWWtn/1IzihBDKHLnX5Cbcquo6md0GeuTZKW2KIqSBKPPGYVzrLTYTyHkdhWiTYyGodImM59q1dOWxMTIrAhz23WeiGTuvZLpWDcfxK2Z9Cbn8d/5rayMAJDtyNCOEb0+YhsoVGU6HWmu8m5MRVvr0D2uqfKUYBBwgiRmGGtF/1xL/mb/WETiMK4OXHYxvbrs5hXEB6TUfztUYKke0awrOlzX7dwYaPu9hK3Qm2BKlUAtYnD57aUrLVT0YzrYHejAjGp+DK2yzerb9B4ssXsWN9Im71Fl+OyLofmED1XgdYScRDZ7e95JDTDQB/kxgsSEBvnervVKj0E8ps8uvPlcWxcb10PwmlAalzX2mU6yI1AJSWJeTh/9Soh59RQUetdNl6XP0a19DAqfF/Nz4exOayA0G9RRHiJkRvKL2dbNHKyXNicTT2c4/LaiGDBxreyBbVtuY5Heu1cSO0m4iHJUMHctKSt0e13djoi+7mvKt8ORzDN/h25j5R13OvmKMPvC4vRtV9Qr/cOEVrLg8I6Xq2DuzBlvidThteM0KHXMZSDdKfJVhsfwYiGjvIeWq7CBkVyAWqOEUWP21M8ljxRIleT4soaNN64iPdtgz61ch8HIxgP7hXOSWXuj3HwQa1k8kGxCZlzw00AAQAJBMgAAIAihoAAAAAAAAMAAAARZmE2LWJyYW5kcy0wMS5zdmcAAAARZmE2LWJyYW5kcy0wMi5zdmcAAAARZmE2LWJyYW5kcy0wMy5zdmf/////AAAAAgAAAHxUgWQUQUVFJAkBFaEhQREWEBYWFQBiWkUFRaWWEIImQiZIGhRCUFAFlZkWgEVISoVQWSlQUBFWBBUURBGqZAYWACWRRQCEiVFlUAREZBBVJFBBRhWVQUEEBZaQAkoQIQIVEWCQKkQCBaRSSlJUKkUJghEBgQAWQUikoJICAAAAAA==";

const chunks = {
  "fa6-brands-01.svg": new URL("./fa6-brands-01.svg", import.meta.url).href,
  "fa6-brands-02.svg": new URL("./fa6-brands-02.svg", import.meta.url).href,
  "fa6-brands-03.svg": new URL("./fa6-brands-03.svg", import.meta.url).href
};

register('fa6-brands', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
