
import { register } from '../core.js';

const lookup = "AAAGBYkZBHIY5BpFcVRBWHJmksVEQlclU2VpMpI5Z4dUI1pjlUNYF4NHO3MWVGdjNGM7UGlXJ3JIpUa0RkJVwyQmNjM2ZXVkYjU1g3YiM2SERnZihWdSRHdoJVVFQnNCRGaFdmgyNVNTOHRBd1MkRnVkY2tkZWUSJFVUZVliRUciVidY7nMB6AcGgqUBDwMBBJABGQcBBiUd0wfnAQEBE+sBA4UBhwRRUhslAQHDDxQBBwGJDAe0Ah7eAQcFjAEixQ0DCThEIA4FaAU5AQECD/dGAkHyKSmKAg0VAcEBBRzKGh8HBM41NQ8BAxwBkqIBCjtaBAhXBCJYCBgFEa8BOQURBAYmGi0BAQIBCxLsASwMH4IBPBpekgIvAyIFOqIBmwEVFgECIwIDAQ4HswEJDAJpLRLkCC64A/YBJQILBQ4BPgJAAgQMAgSFAawCDA85DAhQNgNn2Qg/AyMhKUdvBDQelQFvXikCMQoCDQoBkwEhUQICWQRykB7aP+gOefcF5N1bquJYKHxc3CGmNhCmDmRSbxqcrct+QiGvibGr3EcyYQ8zMRDr8Qr+XAMZdw75CK2TH18QsR83o2CFthMDvHpY35ymx90j8Ss/w0gaBJrbKbhhUZAXTji7eG22xR7c90xRxTWUcN9Gv58aXuPSvw4sm1Qik9tL2tdTzLIib07oqWo+rhUtx5R1jO/EvXKTABfHqyUlZOQUVKvfFxtYZXrfguSo9i+tvqMZSDLfTxMHk2JwZogaU3kbGoVjtiRgxPOMOdQESFaYwBc74QBDfmPBLWrR7Ni4vRuCANsoPScCZxyos0IQ5HiqjTxJ7h9vJv3QdOwgc1l0JYhQiB/tPzGTkXxgI+a+zN0SZpKpBYglEegSc/TcuOB3yTGjs607a3PX7zP1kTV21NnZZ0LhtpY1n9aPXqL+xdaq/7kbDFbM7OJ870ZQS9Bgnou1clhSZCp+wY/DcjGxenoAuB390ws4ymcTwYLagVP8wJU9rxGfbX3wVQYlLaBHb88WPyTMYV5dgALB+Cz1NbeL6VuzWjlbRQ9l7vBWS8hz/CeoSaKmg8MudBpl8kDtiB5aDsUkyzAN9+0Xlw9j0HFop7jgmCQfPEtokfpLG/custmpBzTLXT1Y5rbfkwkLhLpHiCkxiucAMhJrZLRH9kBCdoBcst3YPOCHXtucpR0VfyWCeHXFPqPZH616oh7ZxRxCUV2kzw6qbIZdFe1erhVGIWcBohKC9NXxXoxmTfm8J1VBlSWfYC3RCOfH4oXfCckzMB1jKaz++x1HrmNCk2KyfLEbmPh9PDs8dm7CbVx+xpS9XYLLwN3aM/Zqa8BVFqwIgzGiP+5hVrB3Yb/dJNDK7a3edT9X/E74fyrBngCDmj2Wks3ZQoiCIVfg0S6ehCv5gP399sBzGOcFLsJpxgFAJcLnHnuLyK6+ZbboQGGkB1bUzPjFI4FQ7sSdnbO1ISNP9r0zlFMZDif/yJ9Z5HtzCKlggMxOxsWhTQCsU0CCPP6bR5MKv5bH9WALL667QAfkmx806xk/pRejwuCEHFaO0Rr+w58mOUBBvywy3lnHU4MDUMvIA+IWAHmMceyhvw/ysUk5ybDUfxjfHbkHwG9HSIlwXBdJvMmYoiNcx8vYEz5GCYvcX9Mp7OPTRu8hmk1QIQuAmlizGKUs2uDZ3Mp3cN6UU50Ev8rJzzi8s6YmCxcM5DjkzkGKUJKoiP4PrbAo11djYZ3AuoWboUMq0Oxq3ictD6ElWAGFYNbNMVSun6Qlcc3ffW/Jqd2s9j0QVorEkH7/7moMNFIxKQSLKfJvJqnoaSthbojwA2rLE9psMbeusNFW0yoA/uutHhkou1plv/KtR4Pdksoe/SjEoe3hiSUZzcXWInCoq8AJe06nEaEULptrYsPOIz4SJLKzGNBeOtM3CHyukZi7THniSbT525CeDcxVVDakH5uq5O27rmlc8loKMt+1tFOX1m0fk6hCYHYqTKNdr7VuLymeCEXxcZi3bpYOGS0JK8P1KFgdBEAQAAAhgAAQiACBCkAAAhAEABAAABAJAbAUQAAAAAAABgAAABptYXRlcmlhbC1pY29uLXRoZW1lLTAxLnN2ZwAAABptYXRlcmlhbC1pY29uLXRoZW1lLTAyLnN2ZwAAABptYXRlcmlhbC1pY29uLXRoZW1lLTAzLnN2ZwAAABptYXRlcmlhbC1pY29uLXRoZW1lLTA0LnN2ZwAAABptYXRlcmlhbC1pY29uLXRoZW1lLTA1LnN2ZwAAABptYXRlcmlhbC1pY29uLXRoZW1lLTA2LnN2Z/////8AAAADAAABqxUTZoiGoaFKqmnDhBJTkumihQyjtNHYRYgENAWCrAwXQiEFJpm0cGSYdNqIFFuBkQJDZlqgSCgScQkpKOFGEloyiksHZqM0BYGQLpFWlspUgpNSQgOzJmEXZQHWBEKYSIM4BYtYCAIxhBjASdqEUSkpaRwRklsECWwRadsYCMSgAR0zUikYkgLQjCAKROuWQJoKalO6CpMEFOA2dpIYagOgsC0zNEiHZGsTCtEEiEsZZSA2jYSIIdgKCtG4gtJEKgNCoSokKhHDsEmQaekEKOCEiADQYhMTRZOCSQBDSRsECi1HJVgFCqO2BVzQrWOHcN1arRFItONKtMpUJCNYigFYDVqnKNSQNFoTZQtGKiExgRGBaUwQpOI0gdDGcFujFMDIMFOoUkWAJMgAFhnCDUQbqgsGRsGQDhygSGiKjpJQiqLIFJSyFqHURow2QCQ0lQ0RLCogtRIZcELCrg04DQQFYQ2mdGoacFnJaZBaIIw4LGGIsGBScCrJKptAjOFSoOPIsGOrlRIFTFxFQUDIoekGbtCIKKkSZSlXcOIqCSW1bljXoujELdSGFgAAAAAA";

const chunks = {
  "material-icon-theme-01.svg": new URL("./material-icon-theme-01.svg", import.meta.url).href,
  "material-icon-theme-02.svg": new URL("./material-icon-theme-02.svg", import.meta.url).href,
  "material-icon-theme-03.svg": new URL("./material-icon-theme-03.svg", import.meta.url).href,
  "material-icon-theme-04.svg": new URL("./material-icon-theme-04.svg", import.meta.url).href,
  "material-icon-theme-05.svg": new URL("./material-icon-theme-05.svg", import.meta.url).href,
  "material-icon-theme-06.svg": new URL("./material-icon-theme-06.svg", import.meta.url).href
};

register('material-icon-theme', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
