
import { register } from '../core.js';

const lookup = "AAAGA4kZBHIY5Boc2hgFWHIjNFJFYlYTQ5NEYkVUVUd3d0RUZoQXR0aVM6VMSFZkF1NUkUZxgypjRRh2RWNzEUNmVGJkYjaEQTVjhVUnYyQlekd0U1h0R2XEd0d5daVTR1VlRalEElNzcGODd1REdSGGS2JHSUNHVFUoVlR4RjZGA0hY7AUGBgQFDhceAhEBAQgG7wsDDAQICDsoNwhSFjkiBRwDFjETA5QBDc8CATQNFN4ECggaC44EETcFGjMFsQFHAToGEfoEAwosBM0I8x0LuQEbAv4DFg8DHgYQAgS0ASUWFz4NJAR7EgEQiQEGJQgBFQGsAQoMHAk7FQEGyjRuzwMDpgIqGBINvQEfBxEOBamsAQSkAiEEpQX6AgH4AQO1GT/NAgEPDAgqHQTuArcYCwkBBBABOiYHFA0bFUcRBwgBmwExAVvhAZcIGAUmtAESIAIEBW4DAxYHCOkGAT0qAYUDDyMJGweFAQEJuAEBAlkEcnBtI1LA9kBlQjUmXsKUHyjU8TyzRa747KY+5CrBDm6wXsFdk/7HVOc54UyIuBJO4xl9smdHK4jgzCF40LsIRwTd22KkqMYI2lMeKMBAOe55RstzVnxzAEt8y8sOKaLZq6JqVivxqXlbsJpIkfO8pA5ua7vrcNwVttY/DwYzz38/CyMIfrgXeicYiC30A62wtmiflPJcPcNw6JSmmO+/4MuMTrPMjOBWKcnA7XRLORPEjx8hyat9/WlXJNYbbMEAw1ZSpew4SbaerW4qn3VlruxgDUe3CixjkKizKNGpab0qIYHJAAAS8HVhHpH+1FYbEviTQIpRa0bioVJmFTCLOJgn7p1G3/fwekAmQR8Hu06Y9tCo2Rm9/djZY5L5ramDJYYeDIVvOxljwi2xrWFeBW9C+WCfNWQCAHKq+CQ/m98ZJajCNM3HlloP1trc4vGFcZNTnLoymqq8ysgX9TfoQB+K7Rk5gEIXkqOq+2X850w8UMXk6JwwhcUuqajvAiO/rP65ZvY/YxBr/aqyauR3xcUtXtHKPUceA6xV2oRTJyNzXJ7DWwfdCk49CHDpghSuMXJXgMwpV+ZY7dkb8ZNeEAAX4VXDeRWLzICTYUz2Xt8LJF0vH7oE45tYVMEXe5qCz13bzFTdXoCEqCVTc9T8YCIT3pfMbauzsj9dR3HFYMJhCZYW3FkxDoslm7UQo+Im4hHkSFx/SKLZ0CO1GLgl3IiipDKhJawZCnrsJNV4CHevGQXZIp2ACcd2NggbghUkRiXHZzgA/cDSb+T2i0ghxzGuQoksGgNkE/XJky64oqEEC+1xdQEtrYJf4Zyeza+g5Jfback13Vw6zcCu5gtxMWAMZoiQLMr3v18TsyqOuzEfdxtlmw5d05NWs4t+WxQzv7/QEsSsnpRc3b4xq94gMlOdxUnoati/2+cuS4etPN8v3R+TufRapdE3b4xo9/6jR1PERp8pXBhhgWJFITyIHAQowRDToULAp3Mx32yR5GFNVigp3sbGfqEffFGYDd+myPlC9dabR2U0kNEa2U5YuCWS/zTTPQG/fA93kCaCQ8c1zhwzLyS1DrwhWaO2p6OxPD7L3cpPKT5RvbTkWUPRzP5g66lgS9Yxv6JTg1ojim1Y3+s8a5TvdpUdw3nc0/UhuxfyLSvvDPJ6rhJ6Y3IeHT7ysc6Wvo1aVdxzkcVNUO2pfRborg9i/EL2xShhrt8rrrUfJwHXyNcy7D9C7DZBDoxNxfdd4CqY2Le3O/4d2htJUAA/dIOCC0lnT/2kQIOvSWfDxFAi/gfgbw+ffxetDrLaUKaCsm9Y4ilgHB3Xs63TLCXbPY92YGRqiVXu+Rcx1MDKVgdhJ0EW595YVFBcAP9LHvCVsKX4BdAzEXtAny7y+iW2dqMQg+6IO7SE3xoDodAtGsQlA71tzYg4m3TdtlOJRwnLnv+dfK3gahqYYxozsWoJEwfJ5BGxcHgJqu2+7oXAHjJ7ps/Iku2TvMcdfstvbpYan5q0hRhY2ojfgg9+ZC5YHQIhOAAACACAECEYMRBAAIJQAAAQAAgBQAAAIAACAAAAAAYAAAAabWF0ZXJpYWwtaWNvbi10aGVtZS0wMS5zdmcAAAAabWF0ZXJpYWwtaWNvbi10aGVtZS0wMi5zdmcAAAAabWF0ZXJpYWwtaWNvbi10aGVtZS0wMy5zdmcAAAAabWF0ZXJpYWwtaWNvbi10aGVtZS0wNC5zdmcAAAAabWF0ZXJpYWwtaWNvbi10aGVtZS0wNS5zdmcAAAAabWF0ZXJpYWwtaWNvbi10aGVtZS0wNi5zdmf/////AAAAAwAAAauYShAjpKKhOAFQOHIZFiJlMKijGqqFsLKMIgkkJjQilW0EAaSTymAhKWSsOCXNsJYQpDCNNG1gSUBhppJJuEAAoVQKpRTAFDGtqCUBim7dkFaLljEgQEYDClDQRlLAJKFt1g4YkC1hVFFUkRRT1QRK1jHMmJFDNyQaqgUp2WgIOKIAEIzSGLEC1a1ktCZEUW4kxm1BEDYRF03UiE0BSo2bkLWYwEAMwmZiKGEgFg0qAnWAqDTlkohsSKIcRgKa1mhpGHQbW2JIRCRgK4lTkYIIULWbkiHNkkUUlwgbQilrhqBRRIhKMgVjKq1joBEFhEWTlKKKiiFTOZGTNmotBahLVkWctq2iOKmlJFUpQ3IkFBCTuhBZgEEps2oaUawtmXKMQHEJQEgVmCxYsSqIuKVYR1EkJ4BkwDDVxkLjAE4UJQUSKBUhmjXhJAETpzGiCCRjwiYKRnHaQBDZQqbIQAZRhTCIsmUd0yXCtgyaUhVQyWHBRK5YxrFog44BGQIRVhZYFgzMRIkUNoGgEHZFRGITGU0SxWRc2WJttwQaFEbYCEKACiaIkKSdkFEBAAAAAA==";

const chunks = {
  "material-icon-theme-01.svg": new URL("./material-icon-theme-01.svg", import.meta.url).href,
  "material-icon-theme-02.svg": new URL("./material-icon-theme-02.svg", import.meta.url).href,
  "material-icon-theme-03.svg": new URL("./material-icon-theme-03.svg", import.meta.url).href,
  "material-icon-theme-04.svg": new URL("./material-icon-theme-04.svg", import.meta.url).href,
  "material-icon-theme-05.svg": new URL("./material-icon-theme-05.svg", import.meta.url).href,
  "material-icon-theme-06.svg": new URL("./material-icon-theme-06.svg", import.meta.url).href
};

register('material-icon-theme', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
