
import { register } from '../core.js';

const lookup = "AAACl4kZAd8YYBqkXtm7WDCnZDQUN4JmNDSGlkZVZXRUJIcnYhUjUkEkhFVZN3ZldFZXN0K2RnJFRDZSJlOLJodYZyrDEx0EBXYBugEmMQsGCwcDOV9xbwEQEAE1BRgZFxzpB8ABgAEBMQcCAgFABwoG1QEINM4QC/0CCSFyCcMBDs8BB4ACI4ACAgMQAfkMBRUBZxIEBgWxAQYBC3ICBg/yI44BFwIitQECWQHfuEULRZv9FJEfZ+cRbW+fosNd04O4JztzTSOUruK58HUC+LLmX9byRLki0Kp6g1Ze0CrZwJqNS/toykvTYf3GRAqj+4DF91ARxEVobbMSYKN1Fy8weKmMnP4mPt3PSnRn08AdJXEEo75FlIxXk6EMy7DmToabb78sPUZPqeI3zRQ2Uh/AZZ9WxiEyBr++Vz5cuDecUxMBHadSKPAXlYq0HXb1IacI2n/nTmvWu2Mup8c7BkiYdRxnGpFbvte50vdRG6zspNFqFOZv+XErdLpDaQIErBIMRioABXaNkByvvNJVL6o8G6nxgOoT5Ov/UW/vjz+GOjrupHq+C46MUjL5yGF1NYna2FxuM+7RjSMus++I9NpBOSBNIc2F+yRGtyQCRc5dUxbAt+cdjpuiPzN8HiXoL8QynKsOFIqFR7d2pzwUsFFrrRwGbPpCafRlHS6+NrZJ+WFhiQKViyGNiJvymcwnd7PRgHeD8iaYtSlmnulwbTPbPIqtWLNXW4NBbozs1xDinJ2QTAH+zVi2OVNTcc8Iwi0mZ4P0np02+ZJv4nOkFR34+f53RN9ILIeBPwKrEe+nOwJ+3q8HBV2ByEOVE9NaWMOifmfyofcqoP/zR38z408SdRzpMAR8Xd/9/8pMxAQAACJCAgABAAAAAAAAAAMAAAAJcHMtMDEuc3ZnAAAACXBzLTAyLnN2ZwAAAAlwcy0wMy5zdmf/////AAAAAgAAAHgQgVlUBZJQAEKEpFiARmUASQgARRoEBUEEUBVaGBGVERBBlQAUEgKQFKVAgFKhQAVWEAUBAERJWFUZJCUEREhBVVIlYEBVVYBhoAiRUVEUpWFmRRRVYJQlZUVFUAZBAaCSEkCGQBBZUmGFEASUmWlRUCopUYEhFAAAAAAA";

const chunks = {
  "ps-01.svg": new URL("./ps-01.svg", import.meta.url).href,
  "ps-02.svg": new URL("./ps-02.svg", import.meta.url).href,
  "ps-03.svg": new URL("./ps-03.svg", import.meta.url).href
};

register('ps', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
