
import { register } from '../core.js';

const lookup = "AAACkIkZAd8YYBoV45VCWDAkdpOFhWJYVzVIczVRaldEMRRjRmJDm5FGJlQUZpfIGBVEOFc1UjM3QyikSCQYRlZYYApqWwaSC5ADWI8CASTuAgarAQMoBZIBEAMyIhsU9BU4AQEGCgMKnAEHLBCHOzWwAhABLwdQBgeoARPwD9YC/lmMBw0IDokBVS0QAwQDKAcIBfICAQPrDIoCAwFkEAFXBAJZAd9mLH6Zk35dEfkhxfuQPuIzIfdlT1ueJi/GmG5FcS7ejaKfKldcuXWD6sAF8ipt2kGtJYMcHan5a4MUTsQEXdb+cOIfnb4Aa0SKTYbXjAIIbUk2PF7xNvDzL+NOEeKVmiNCwNGn8EhPPOYehxSDtMw3wu45EyBKZ7/pqQFHNigli4jInviVDFpngKJSlJKzMINF/9N3RYFGAjvWyEVYFyr9UkectS+OiIz/6+yqJvkpBSTNJIr7Um8mlLNBRu9fuIxzPwsI0zPyY9B3Ib6vdQzmuAd1rm/777/HAjsUOXygHD/sxgpndoEwYXGwaXSbPAIuXQYrFctNrR27O3bnwO6jMmz9kDJR0af0/lah+ENYjWfSBsqzEgb3J3VLV+JIm9M3t3pTYI2n+W6kG9r0VZF/bXFpzv4QsOac0Ixoz7foBC4C9BJTYYCNq6J2HOR4pCwzdC2hjwTyXKw6FBfNvEQnuBFTYXxnHNrP0afnWG++dUTAf4XfC/dRzdKcYaQ6/W96t0sfEqO5q4rd6fodiYY1I1Yym8RGUA7/Ghb1qYCfnBu6c52J2PmvqgI+IT1DrNcid76RE1sTmLYdV+ez2T+F8qMdHVHD212naGXfjptqlQGyRcO5tkzTyhQzU+++b0xCAABBC0WIgCIMAAoAAAAAAwAAAAlwcy0wMS5zdmcAAAAJcHMtMDIuc3ZnAAAACXBzLTAzLnN2Z/////8AAAACAAAAeCRqBREZVACSBgBQZAJZERiWBEUIVQEBIRGQClaUoQVRVIFhRgVEUiFFUaGBASFFgVUlGBZWVVZGVQQAFQUEJloFZJUAJRYJFFhgZYQAQRkBAEQlElFAkSUQCYBFVqglAGQKYEQQRUgGoZJJgZFRSVFERAQGQBUBAAAAAAA=";

const chunks = {
  "ps-01.svg": new URL("./ps-01.svg", import.meta.url).href,
  "ps-02.svg": new URL("./ps-02.svg", import.meta.url).href,
  "ps-03.svg": new URL("./ps-03.svg", import.meta.url).href
};

register('ps', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
