
import { register } from '../core.js';

const lookup = "AAACjYkZAd8YYBoEb+UNWDA3NmNWUxdUNIM3ZBdDhWQ1VKNhN1NYZWRURqdzVWR2VXVXNGV1ZUZ3dBZUNVMpJVZYXRwHQhFlOBMFKQQHEQkCCsgBUAcPBQeEAQkdAh0lAsYFNWsMDrQCVisKDgQEHwYo6iWCBQ5zUgiOAgEfGgXMAhMBAVUjxwECTJcBB78BfQkmOAINAwcFnQMBBJMBOAJZAd9uRtD7cc2wrF050i8+DjMbT9cLXE+e9Dv922G5JZkGfsMz/YcqgxXAMK1HC4luE4N3SjujjLSiOuKQfD8r6jWAXdNEt57aZxInp7n/LxSQ/t3wAkaKxm3+ZpNheha+em/sQaA/iNHEjQIyhbMcR4PeHRJv6O8StilT70v9FAfT4minwAIh+TzHUDdYs7WnW/fYqr5v+J26JDZrCIgzBJ9bVnX/F0Svw0lFRV+NL9F25I2/rrzNWozrb7CKmKoAz1fQ8tY8v+7Adv/X2cxqcINhdfOh51JNaaSrTBrajgU+uIac8jwlu69zqSYIQ+dlrE5e4iZT31ER0zlFa/lTLbldHSM7lJHyxGj67z2+AWCkRBCbp6d4MhTCsqIMKnX3+RO3IaKpmxTObOZNLIAu5jcq00gwNn8cdNJcLqQCdpTW+QzNZ0WGVWdYCuZRJ7iRyAECgeLffwVFd/gbArN8HPVCxoV1lSEGRoMTZW0EXZsexXGJV35tZ0MUWC50ygTKcyAdMsuAq1Gd4/vpImGjJIq4JqPxcal1vvebs4zPjfQh2kH0oZwRHY9S8sDsZ4wc+W93HVYj7pX7n622FxE/Hb4s5x9SYx82jvBX0ciVBk6YgUicOppTKGn+nOmSM4tLt0wICJiCEAFCBEAAKCAAAAAAAwAAAAlwcy0wMS5zdmcAAAAJcHMtMDIuc3ZnAAAACXBzLTAzLnN2Z/////8AAAACAAAAeEQEVkRphECBBQRIFqIWUVAhYUFVQFBIAEERUVQqECVUlZGQgQhJFQAUWoGFVBFRBVqGRGiiQGUEiKQGFhEIQkRQBhUAJAQQWKVFBJRAUpRFECQJEBQZWFFVBQIihAgBVFYkGYGUFUWRVYAoVRRBZEUVIRgGgQFkIQAAAAA=";

const chunks = {
  "ps-01.svg": new URL("./ps-01.svg", import.meta.url).href,
  "ps-02.svg": new URL("./ps-02.svg", import.meta.url).href,
  "ps-03.svg": new URL("./ps-03.svg", import.meta.url).href
};

register('ps', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
