
import { register } from '../core.js';

const lookup = "AAACnokZAeMYYRoxOjMsWDFFNhRiRUJoVnMmdzSJZ1NEdmhpOHCBVsI3YzY0JDVnNVeFODU1JIIzdSdkY1dnVmMEWGhBAUIBBW9UFQEGQAQeMwL7AyUBVv0BEQy5BbwEIhsBIzdXFiXKAboLEDcBbCnbAQMBjIABSwErDgkJAxUCGKsEtAEJAnMgEI0B7QkJEQEgAhMBoAECAVEDLAMWEgGCARESIAkZPNcBAQJZAeNYLzOa71losLqHj/PsmjR4LCNtD8h7EDCUV8bJPmeFlnhkn6iFWmkq4Qlsn3ZLqzzGR91XzHH4ECca6Qns8y0tRJXwFi6iI2dd2JRHR65CdAUNEW0DHxF9fgzfMYHYWDPXyl3kBuPwMuYqQeKrjJyurXGDv0YZRKoYb77ZTUOtoRF9Rv65OMtN223KhS7fcFfPkyKuaocSElk+yWEUFgrb/Xt1j1AOIPc/F6rvE6xVAWdPD5aBuHLC3lopnEQpkJ3i4OHG/8aQB14HQ8zkSwKfu1gFpzEWvyHhpKl865RtrMPTnBspSJMHt2P7kckfcxMOMYju4TyIGAjXhggvX+zFAkjUVWaJ8ewgMMJb5g4MsjGn5u+zKRuFMqFNwrKdnKkHabwIhMqOR6hZSp3MvkU644EpxcCF6zYZVLz+9FFjTuiHHa/BW85xtvILqMTuXvyQsCPgPD2r4ZNunVPqC+tyNTf5fz+56JT32mSsFYWfJfpjgwHP021penRqjbyVSbH295l0q2H2t9FdON0PMjQQsM7Vp5MNC2wYYBeLJEUGFDzNJBmB6ZAoHtJpbKXy1o3Pv3+hcjY6omQ171qjDGR64gsRiI9MMWgbyfASN+kix7bwfLgCy57y+1qR6DLqwZfB/MBNYAAAQAAFBAgACABAAAAAAAADAAAAG2NyeXB0b2N1cnJlbmN5LWNvbG9yLTAxLnN2ZwAAABtjcnlwdG9jdXJyZW5jeS1jb2xvci0wMi5zdmcAAAAbY3J5cHRvY3VycmVuY3ktY29sb3ItMDMuc3Zn/////wAAAAIAAAB5BBSBgBSJFCQVVBUkAgQWIpAUVAVBBFZApVFBlCQQFVWUVGJREEIYBRpWUJQABRRZQoEWQBIGgagaFAEJIIVlQKZkgooEQVWQaYQEppkQYEaFAWkBJGgFVFRVFEgFFFEAUYkhJAKUFVJUBaRVElBRVEkQiUQAGFJQEAAAAAA=";

const chunks = {
  "cryptocurrency-color-01.svg": new URL("./cryptocurrency-color-01.svg", import.meta.url).href,
  "cryptocurrency-color-02.svg": new URL("./cryptocurrency-color-02.svg", import.meta.url).href,
  "cryptocurrency-color-03.svg": new URL("./cryptocurrency-color-03.svg", import.meta.url).href
};

register('cryptocurrency-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
