
import { register } from '../core.js';

const lookup = "AAACmIkZAeMYYRoh8lXpWDF2RmdFhGSFVkRmI3VGYkUmNDWzhTF2ZzdqeDFUF1QzaFd2YkYEOWJJSTWEY1hCMBYGWGIdsAMDA9gDUgQBBSsBOxyWA9cDGAEFoQE1AQEYOUcIHBMbBQFvAfcgArACAiGaAUPaAQ7kHQp0qwMDKw0IEQwCBVYJNFkkLh8J9AcFA3DDAxAuDBsSrgcKA4EBKAILBlaaAQJZAePKMex8rCkuvCecf2THZOpjhO8G5mMaC45TIwdLy1rG1FVJ0yo8FJHj4XKcyX4Qxmoh/TzCMjDxXveM733pNGDYq20bPQkG4sJPETqxLB9xC6cdEOYkpGHCkALhWRCURpWuUUX6wXazGGml3Z+/0iLanxkO6OtOLeqfArfKgTH5TQVXbazb23KugWdbkD7oqk2IwDqVIKheD1r3TRIHRHrzsuuFsFjdKW17R1hZxClH1fB6JFrsxuJF7ilBFvenDamjB0bvCKsVGzJknf5ZXRh0C2rzfy9tVeHMF2ereAmFQg+LnbC2/+GovOkzWIPyuIZoFs8MdCXY8sDgzBG7SGTfztn+79ehVwXPMaecj0SToRkgkJwUZ49Xh8wprYXRfXDsMLKdNgqeQ8a/H6oZYc2oRxHJzoWFSJNf5AFvlpQ/l5ATk+jTB6KuGC417pGaEjfew+tzcd+prL6IPHurvL588DcCKOTjY/SayMp1iG2UhUPW4Qh4hzzytrmDDyMeTGjpNUs++wuwW42/Es+vNjLwOHHwDDEvoZPXh0f7SvbJVA6fcpaP4LcyaV1Q5oH2Kom6xSOZaS3sRGm4DMG5Do1srXQTCCLiXQ2dyTMR/GyU+BduA6L8xTgWwYExZj9sNAEby1pNAAAAxBCBEBISAgiQAAAAAAADAAAAG2NyeXB0b2N1cnJlbmN5LWNvbG9yLTAxLnN2ZwAAABtjcnlwdG9jdXJyZW5jeS1jb2xvci0wMi5zdmcAAAAbY3J5cHRvY3VycmVuY3ktY29sb3ItMDMuc3Zn/////wAAAAIAAAB5EpFWBRAlZJJhREWSCCkEGYZlIJhAIVAERlEFRFElWFQFQgZWESKRlUKgQhFlkkQRVAGUGEVlQBEARRaWRRQhVlBFUhRVQVFUAFASECEaYFBQEQJRGKGRkgGCVGZVggACAaQBEkIRoRQGYKBBVQICUUQFABhFmCUIFQAAAAA=";

const chunks = {
  "cryptocurrency-color-01.svg": new URL("./cryptocurrency-color-01.svg", import.meta.url).href,
  "cryptocurrency-color-02.svg": new URL("./cryptocurrency-color-02.svg", import.meta.url).href,
  "cryptocurrency-color-03.svg": new URL("./cryptocurrency-color-03.svg", import.meta.url).href
};

register('cryptocurrency-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
