
import { register } from '../core.js';

const lookup = "AAAFTokZA+gYyBprgnYbWGRDZFQoVmFEkVInU5YzJZY0YlYpR0dRhkdSpTh3YUpDV3WDNDlVeVVERGVmNTOXZVMkWhJjlCY1REZSKTa1NGR0mISYZFImMkSWNCiBNWZoOYRUpiVHdmNyZJUGc1akBEJDc2MYWNMBDSAOHIEJAjBUaQMF4QQrNQEMBg/7EwIFCQEKoxgHAwKhAaUBCSP9AYMEARQPhQVmDQQDC/8BpQIWfgKNDwIFtQEDIrACAX0QA5YLAQcDrxYlAy8DAhMnBhZueQEGBWTzAxUeBxoZrgk1AlgOoQIPAbMBAwMCAjGnLUAPsgHfZAwGC0MnRscCygcjigHdBPUDBSsaTwEHAgM2hgd4jAciA0cphgEvkx8EBrcBCSEp/QaSAQYFL40BCAVPDcIBAcYBFgc4FgIMkYEBDBYFChcGfKQFAlkD6LBQvwjthFaDzSP9N7Iuo0N9ZhHIA2u2qeUzMRnQQyWpbr7lB3Ov7ZCtD6MMiYXu1RJx0KFE6rmdFdSAsvwZRJ5GMk2fkuWlrNu2vAeEHv34Sqx+ooiQvQd99odtE0nvMKKvaebWAvQNmR+VgwL1ieZMmz2DWYb0hJXpYbeKLRgExPcJo/+5pLau73aV26m2qDpaLqy0NIjVZEoLR0Tj8dRz66Bmp5hVYhsj0Itvw7wdwyRLh2nyvoHqWWaxFTxmMkaXileHjZSlg6HZODbNbEL7JWDC9zCPdqOG/xkLd8w4lTF+qMBv+loDWMoaOT2Jya3pJhY0vNHgvEDfsR1nKNSFhK1qt9IGEaMKKPSehSLeLQPtlWqs+7hNUArw+U6wK8Szb5KmblldLgzutO0gFMcp4aXTYl3N19C5oFbHSawts7Nm1digvJI9mh4+qYmbEdV/hzCglmb7pjwBO/FOwCas1KSn0J17dF/1XqCGu7c2Zrws9XuNNjg0ptqpeiv6+HNtFIbUxaA7p0lHn4t99ZvzUbQgBoiTXzL+EPwsyvXfZqEluieh/8k55fQvPu650HLyLRryDuuDrZO5LAY4Uy9LCWla8hIcIOI8XIx+gD14kWCEWurQQapd3KfHCo5kg5fvo+S+dcs9T+SMhXKJ5SVLR0iA+/7Vz6r0K1xlj33mxAIHiV8T+QMOkEQbR2wXXgyc4wINs9QzOt43yVafkIwYP4fN59USM5vOAGK/ttsYfk1uWlPmGk+nty66erkjshWj9gn8CQZiPbyM+571PZTSEBIU69zt/L/24YCxaLYNVnkPdFcYvvBai1jIMvKviRxRkXvz3RVsf37Y5xRM9ejA+OUT+a7B7Dw9krTz/XTWm4z0bUJejqDOnFg0BRxd9xQ3VilHkR0BfSBffYqTCccBwK0ih11IDDzOMdW8GLrWuD1LGVCe6RO/b69bTB6mqheX3QjA3ZfujlzfnmgGWVJK4wDry2fwx7qJkifp5igG4yMD6G8aHCzBH5K1c1hM5y3o3i2SKJQygMqg7Bj9IZB+Fq1e9AfRgeN8kFp7hpPryJ/mrIfK7+NbU3ZtXcDZVfHK07KoKY0/qyrsoMveJz0VlHzX1e3k+8IjVOqt3K7NhruXeD1N1Hjhj03yBaW0TUa934AGX+vnbHhS7kfaw8x4hDbVL8Dm4JuUvFSLzLR/Z2mj5dIVqfd2jkVgisHihHEPOke01HI7nh9PGnLhefhuATCflLXtJEssx4nGkDdQa/pAO11Rah1R6In0paOrbkPfsr+m+/EF7VVd4Yl6LqAFDcZ9+UVrrPnucL8RN477fP75nhoZovtYGRBEAQCgBCAhAEAAADKAIQAAEWwAgEAgYIQAAAAABQAAACBzdHJlYW1saW5lLWZyZWVoYW5kLWNvbG9yLTAxLnN2ZwAAACBzdHJlYW1saW5lLWZyZWVoYW5kLWNvbG9yLTAyLnN2ZwAAACBzdHJlYW1saW5lLWZyZWVoYW5kLWNvbG9yLTAzLnN2ZwAAACBzdHJlYW1saW5lLWZyZWVoYW5kLWNvbG9yLTA0LnN2ZwAAACBzdHJlYW1saW5lLWZyZWVoYW5kLWNvbG9yLTA1LnN2Z/////8AAAADAAABd+IGIIQWMQM5IRmjARIHJoyiCVw0SpEyiQpBadnESCAWIRqJMMTCbZK4LAixDaSELRhJYgEhbQMEEQKQQNkwRhLHSBMQIdgiiYHITSAWRmKGcCEmUkAULEA0SpoSTdMUgRmXLJFGCUQAbQwxkEIQUoHGaBzHaEwGQRuQDBmWLBohMAMRYtogaNSQRABDbUnGJQgZiFMkLEkkcRy3aFCiJAtChYuUcYBAcQM4cSKmMZq4YcwIKouSSMgmIJlARVFAcBLFMSEEEYSUDASgZckmSgyjCGSwaNsICCRIjOM4iSRDUUOEiEwgMsGQAcqGMQMoMUoiTAEokNgiMNo4hgJGkBRBgQsXTdMEjQG5RQMACuICjlwicWDGIBw4RZAmhFKmIMGEiBCRYAMIElsGYgQgBICAAcwyDtJGBBuCbZBGSAgjBlSEcCCWKEwYIdOkLAzIASAjMQsBcZI4bgpHBgSDLSNCUBNFcZsUQhjDAAwRgEkyAkNCToEUbAAAAAA=";

const chunks = {
  "streamline-freehand-color-01.svg": new URL("./streamline-freehand-color-01.svg", import.meta.url).href,
  "streamline-freehand-color-02.svg": new URL("./streamline-freehand-color-02.svg", import.meta.url).href,
  "streamline-freehand-color-03.svg": new URL("./streamline-freehand-color-03.svg", import.meta.url).href,
  "streamline-freehand-color-04.svg": new URL("./streamline-freehand-color-04.svg", import.meta.url).href,
  "streamline-freehand-color-05.svg": new URL("./streamline-freehand-color-05.svg", import.meta.url).href
};

register('streamline-freehand-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
