
import { register } from '../core.js';

const lookup = "AAABlYkZAR4YOhod8o1LWB2GdHZSFiUzpmKyZ2SXJUhEMnUhJGVCN1R5VlZGU1g9EL0FD9wCL4wDAQVqBgkDU+UJEAGkB8EBEgFzBtIBGcsFBAMEBGCTAQEHGgnfAQIJA44CygM7BxQQeQwBLgJZAR4niLYDcZUk153yw7h6AVDXKOMtv6LaKm+oIBikbQcCHk7waXoPkBX/jqc+9DmS7VJbkPxaqQYYabsIKiwyrVWcf4Xp29iMoLAefre+P7NgIZx4DHusHPk3yE7tJsmDIAEbOXcQxa8XIf3Rf2Hmdab9YO5RQG8uvdN635f6kpN2yeQjFoPuRL77IHaYqfNtLI2fOWxnY4PwUXOv/6NRx4T3xc68HhOE1bZH+KxBh3LPVWHSFb3PnG25SB1X0jZh2V1fmS6OgCa/tYf+p6isiR6+c5skEbUNPGO000JrFPfjtlGbG3OblYwkjcWUBXWtkgaU8nGXSNYeNE7RR8rV4TC9vQ9GLTC6+77N9t0pMpaLVpWwKoki77PeRVCBASUySAAKAUjQBAAAAAAAAAIAAAAOZmVhdGhlci0wMS5zdmcAAAAOZmVhdGhlci0wMi5zdmf/////AAAAAgAAAEgUABFEAFABVAAQBEAAEUFBVAAUFAABQQAAUAAQQABEFFUUQABAQAVABQQAAURAAREQQEAQEBVEAEABARVEBQAEABAABAQAQAAAAAAA";

const chunks = {
  "feather-01.svg": new URL("./feather-01.svg", import.meta.url).href,
  "feather-02.svg": new URL("./feather-02.svg", import.meta.url).href
};

register('feather', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
