
import { register } from '../core.js';

const lookup = "AAACqYkZAfAYZBoBM2utWDJ2YyZYdFmTJDc1WyaSMUVVp7cmJEREI4NEVGNUUldVVwZ4QkZUOaMxR1tXREdXQzVjNVhlKjECBVMCxgcWDCa7AguMDQUmBSWARAcPAgG8CQEaCRIX2gH4DtICsiYoGA4NBwIBAVMSARQJFgUlAgh1DgoaFA+IASoEBwEg1QMD2gEDZxHVgwETjQEsCAkXGZ4CDQMLFwETBQECWQHwcTUBqSl9qp9iIwvIWTr5WzM98lrEx5Eol9PhRfdfVJIEYG0bsgchf/Sm0QGV1d7oQJ8+hYEC30s9pRDRdObpgHQCaXRM991+M890ZtC1Xos1gErYjiEt0bgfTCfeZQbhvvVK8gXVEuByK+oC2omeHXjyALplv4o3hQSSNaurdDz3Gwip5xm724v20MR7FmSTa4dhKJrOB/uGuXemDaBEQTK0F9EhdXPjyXbaBkxDwp3M80/V4m0WIc+8qgran7ZKNqZCrEUXDQBUNZyQcqCI9hfB30QoBYJ9hfMskfPtiTARNyU2O6Geqr9uySAHPDKGQLXPOe50NIyCUDJIUNid/q99mFXdUsrv9qVSUclKz5r9MPT3dwlTvFIFO18paQtsxJH4MyKLmPfnnbOYGr90OVHrrRT4/UYumeBrwnc+kNeo6xOgDVMM06k7J1DXNWJkfeYeE2DjiDO6xZ6n37YH1RR7IRZ7EyNn3pxqXohdYmunY/1UlnPcOcdkiymNoZqHRgAWVLY9fUvanHr81Z9s2cB0d7S4UMX9+USE3CEoEe2kXNXZZ/DINbnDVVankRK/I9yQRvlVhhYTGz+yOGHS6gmm6sHgP9CyUIwaGG2o2vWKYONYL/SXsGDoP7bobwndNuL77Hemc1QGAdmUPmi7eE0AUAgEoCAQCBJJABAAAAAAAAMAAAAMYmFzaWwtMDEuc3ZnAAAADGJhc2lsLTAyLnN2ZwAAAAxiYXNpbC0wMy5zdmf/////AAAAAgAAAHwJBSUGCIIgWZVoIRQFZRIRGFFBUASYWRElFCBBRABJFEhQRkqBJRFFGRgARQRAhWAZEJZQUUAgEJEQVSoVRCUUUUQSlSZEBKKSVlhQQAAEZhIlQhhYJYiIlUUVBklqUAUQhGYlJEVIFZKZRKRJYYZIhZBJEEVIEEZkpGCRAAAAAA==";

const chunks = {
  "basil-01.svg": new URL("./basil-01.svg", import.meta.url).href,
  "basil-02.svg": new URL("./basil-02.svg", import.meta.url).href,
  "basil-03.svg": new URL("./basil-03.svg", import.meta.url).href
};

register('basil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
