
import { register } from '../core.js';

const lookup = "AAACsYkZAfAYZBrdor5YWDI0lZVkZCdlhSklaHNHgxgnZEPGMmZzVxNjI0JUWCTFR1ZER2RFZ1FGVVVUdFIyKYZBV1htBQpWvQMIzw0fKQSfAUkDMKoBQcAE0g0CWbwGFQV4mwIYnAGqAYkBBEIJDBaxlAICAQSoAwkRCwKPAQMCAQQCB8UGTAMKjE1jAVZaBA13CAMdDgOQAbMBC3kFLSoRDQEHBzYEKwj/EQEYZLkCCQJZAfD3PUYplT3Ehv28e+ntbTAzlwGRzwshP6gXAV7V4+x0W6r31UD4zuNF1Z8h+8Vhn2Rzp2UsFmFlc/u5cz4vh+rJRJy2VXcT2s+p37IoFqe0bOamLYBQqsxVgiGI2rtPxRTdnlVgBd0BrZ7PUpxkH7OqKKWyoF9uKY5i9yPfB+qIVM+ow0ypMDVqM6H3E3RKbTuUfSMbBe47dTV0hJopF3jVStGQa6aM9EJWEQkePoUFh0FLizwMcth6UGYaAlJox5lQxLa//UNdht7gjYmMIRvIIcQSPAbQKHQ+oBPQVEoIMmf5uBY1YmvbN54XUr6LEmy6iVBY/ZgnWsDHIh0YQJi/SKtT/QnzXoIGRv5tP/U55vZ01XT5IVBKkfSIyfCafnS1ENW2CwLT3ug3wYCvPyPhpqZLDatgZ1RpNpA6unc5FNp/6H00BHfYGdcAv3SYtvj03UY22fkbKGCSMtl4aZY1kZ/J3NJ9yJKTALzqWeslYwc1v+923IszfeDa08ouRV/aBOey7Uw2MsJynbBxe0TyIBbC9lSaB4alnH2me+j851zc69HB9xqhgbudOWTf4LigVG934uJRDdA9B5cruQbzTN6shSfhYKe1n/IA9YrRDRP2UVMCOziQd4XjCjOK85EJ0URi2TWd17Rri/KkFhGpTQAACKRAhAAIABAABAMAAAAAAwAAAAxiYXNpbC0wMS5zdmcAAAAMYmFzaWwtMDIuc3ZnAAAADGJhc2lsLTAzLnN2Z/////8AAAACAAAAfEioVJBQGoEFQASFCoWCYFAkVqmgUkGoQUEEUBgiJgVYWVJVCJWBBEVhZFUBpZKFAIVUUWYpUFBGkUJElUAGYBVEVEEUVRQkGpRGApFpFGhRBBQARVIUpKZUABGSVhgUAAiEUGmFJVQRCAIVRBlEJABFkQFkRgCCAFlqEBYAAAAA";

const chunks = {
  "basil-01.svg": new URL("./basil-01.svg", import.meta.url).href,
  "basil-02.svg": new URL("./basil-02.svg", import.meta.url).href,
  "basil-03.svg": new URL("./basil-03.svg", import.meta.url).href
};

register('basil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
