
import { register } from '../core.js';

const lookup = "AAACr4kZAfAYZBrMgxFsWDKIQlYmVYSCQ0SCdjWFekQzNIZnZUWUUkNWVkpjEydVIxNlZFglUWJkhFNVdUaGVhSYVlhr7QG7AwYsZRoCFQkP9AIBJgIGHjkCiwZpggEiAzHkA5kQbxgGAg4CFv0J7gIHKCsICg+KBxsFCyIGWDjnAQQFSwiIAQICRwEBBhNBAQtpBwUPERY7EcEEBRcHFYoBFAf+BfAECQbxAcMEBQUCWQHwqdpKTDWMYuPT8j/CZT+lc9FkIkuyap32Q4tQO9sKwMyGE9noXGMdgPRkqkaOUXhzugllIeaHqWAWx3vetAlrKCyHCx/aJ/02DaE9kL9snJY9AGvtutm7htVUAONMcmhxk/fP3kVS1xc17F71Zgc1+Txy314TU/cGStU+icOKN13Q6kvgzz0pWWlAl7DIFJIhMjA1WpHJDPmeCcLVp93dCwF3Fg2YAr/ckNg6/bm2UDa/Bge4RGB0pk+d3JopjTZfrWw1Ru4o/aShRCEofZwNdOpKxBF9VZzFO26FdM8jL+fVfkYa9Z7qG3uMfaYHpqmJheufplTzM+jHNYt0p8HKVKC4UegG3y50YIJtYT8HsjNnxauI+5olGwW2QLJtxJl3+ODJYESoIBEnX3eXIRb2ZGfp3CGYGJEpvzlU4mlU328rhOC2E1B3Vhu1xH3JdNCLetr0LVW5+ICIIVsei3urz0iBiAJFvgSfSvIAEyMy/jTrdggzn9njVdE8N+F1pwX3+UL9BWI51eeYYZEUUK8+ePydfYbTUm1rvIo+tpTV1/DQ0ZH2Urs5U6Xt84IQ+6yVFhJz9+EoAqbS8zA7tUGzBHeQFwGqqBkzqhfykiMBoNr3zn9MFtj0hd3m2rxiUBp0tMigwZoyEp90nt7v4jhY0U0EAABAABAAAgIWEIIAAAAAAAMAAAAMYmFzaWwtMDEuc3ZnAAAADGJhc2lsLTAyLnN2ZwAAAAxiYXNpbC0wMy5zdmf/////AAAAAgAAAHxSFAREoKYVCQYYAoAFUFKGomYVmAIYQUFVBEZZQEEURRWYRIUhJACRYKkSEGAWpKZohBQUZJBEAQagGUZAplSKBUSAAJGSkIlAWAAVVUUVZZBlFYFiUElJJGSCCQBIClIUFFGUVUSBlUhEQAElmhBUGUBEQVRUWUUAaVQRAAAAAA==";

const chunks = {
  "basil-01.svg": new URL("./basil-01.svg", import.meta.url).href,
  "basil-02.svg": new URL("./basil-02.svg", import.meta.url).href,
  "basil-03.svg": new URL("./basil-03.svg", import.meta.url).href
};

register('basil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
