
import { register } from '../core.js';

const lookup = "AAAB24kZAVAYRBr/V+EtWCKXRzJHVDZjczZVJ0QzdXMhh2JjM7V3R0QmdmdJVWRUJEVlWEsslBOuAQgHygEgCQsjAUgFO4YBAhVAOgISDAoDJ6YBA2vwAWbGAQE3BwQvrOoB6gYGXAgMAk8BB6IBMATYBAYCA6gBBiADDxMcqwECWQFQjZLMSov29P2l2m13F/y85U4HHKJYz6zRcrCmOn3khyf0h5ZYjikgOCGf7vnmdLMYHT86yN8253OIbNUtdIgAqi81IWnNbfIz2eyUrtAhkKx7ZzuWGjZ6yH612EehgYxV+a0olP+Osm+afMNkvwE30U/ExcxP/Zq+EltrH2PYVBwGDnacR7mbxKgM4LchG87NET4hyMqwNsA8KzsSyq0JkJ1zugdHuadv10xNIvtrEL4oYBkVRrYRxubiU2gncx+6QAo9HqkOFxPt2BDLUhK3pxR5P41xiQ25pPSKA38Y/6jWRpQf7K+Fv20UuWz4zeMc5L6u4KCR+gLhlUT5+6nXuaNGuXWRQYQKc7lSVfdFeaTBnJs7lV++axBhMXW7rnuzD/5jfjcHUO2lRedQaDSr5+fIvEDzSmLXWyzSiCeHRmAe353BRPFpY3v7KR4CnJKfSRAQAMAEAACCAAAAAAACAAAADHR5cGNuLTAxLnN2ZwAAAAx0eXBjbi0wMi5zdmf/////AAAAAgAAAFQQFQBAFQBBBAFBQUAQUBFVAQBBREQAFUBAUREAQQAVBQRAQFVAEUVVFUABAUUARQQRBABFBRURBABAEAARVBEAQVVUVBQAUAFABRUEBARBABFAAFAAAAAA";

const chunks = {
  "typcn-01.svg": new URL("./typcn-01.svg", import.meta.url).href,
  "typcn-02.svg": new URL("./typcn-02.svg", import.meta.url).href
};

register('typcn', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
