
import { register } from '../core.js';

const lookup = "AAAB1IkZAVAYRBq54iHUWCJkIEV0giRnZmYlRTWjdFc0dlSlZjR1JUM1h5mCNUJjYTljWEQBoAE9CAK8AQG9AQcBEG4CKgk4DSEFDgIC/iAQYwkCHQ4PPEO8BnMwDgIFXxgBAwQOFX8Ubt4OrgkcAQITEDJVoQ0COQJZAVDkjpSQVbdGxDe5YXO/Y9aWpdXguynkHDYo/81GvpbXAry+e3euHCt1B1RAGHaiegkeEnM9/r6z/y86YzG+cufsyNeRrR3S80B9R8xYBp84EHM154hSIlW64qpbuTOJF6epOucnwERgdMSum5T0SnmMfsvlNkRrwyCkpdE/ZLlFqBEZEofKZ+eKvM3uslA7fwFrUMiOKfQncW0ha2AKb9gHHpB7FDxGrQ98aA50bMH7/K/xO/vsHvofEZWSkvlG3y2r2CEO+cxpbBWNyCFp2hTFSrb24+YYEiG37RCNv8ghEOZ5AJwcn5yaxmOwdW39Uh/hYh8a+7lvNu0TaFsNKCxfhQNFO4uETbDB17X3F6OaoHOmkUfNylP0pDT4DH7gGwrZzzeIsz66gT8nh6iV0J3YnazRTN+nuU9H+UFYzm0Cof2cm7lPe6mIrpSsTge58odJDAAIJAAAQEAEAAAAAAIAAAAMdHlwY24tMDEuc3ZnAAAADHR5cGNuLTAyLnN2Z/////8AAAACAAAAVFVFBEREFAEAAFFRQFRARQQVABAUUREVBAREBBFREAUUEFVEAAFERBQBERQAABBAAFQEURARFAABFRBEEAERQAEQBRAUEQQFUVEQABAFRBQREEBAAQAAAAA=";

const chunks = {
  "typcn-01.svg": new URL("./typcn-01.svg", import.meta.url).href,
  "typcn-02.svg": new URL("./typcn-02.svg", import.meta.url).href
};

register('typcn', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
