
import { register } from '../core.js';

const lookup = "AAAB2YkZAVAYRBoOrQF6WCI2NjVFRGNDZWNmSFKlJERkSYVlV3Q0tmVVVSdkY3VxQ3QkWEkCFwQHARQKAw8JFAEPTocBDjysAQHGBQIMDaICBwEGCAzQAdUPFg0XCBXTAQgHPwoGB8YGCh9HHhIFxwIBBwsKGbcCRAYMiQIPAlkBUGyJqManxfZ5wL+nER+/PyA4kgeRGViRa1K8Jx6uSsFtbCGQ17XzbchNxI08+LxEAcwQA4jgDVBF+3OpnJBttm++AqR10bMK52kSYNiVBjf8yG86+6whq6VojYisByGqPr7ZEHff/ZIPPVKcNkCWyrlMejrOKaa5N2Afc7MXItr3y2OtuXPkoohrsEfPH4X6dGH/RuMT9ISK1R7tLaUcChg21pzEM2hKh64CfBh5T+z9uRefodDSX+75myudHEa3zdg7J7knW3OHvo7lceZbRn7NlEfNKLoavjT/O2etmhQSlIywHHudn4sM+Zq5KIchsg7yHTE/0UD+VU97qVSjyFCVTufIWBvM5ym7acF7lERV+w6uEgD034EJ4X3KuX8VLBSoB2PslvTD4DUh59jia3RioDakjlN+HptGEXW6RzvtY/FkckG313bmRS+v5BD510kBAEAAAAAgkAgAAAAAAgAAAAx0eXBjbi0wMS5zdmcAAAAMdHlwY24tMDIuc3Zn/////wAAAAIAAABUBFAUAFUQAQQEQUQQQUQAQVAQRAAUAFAVBABVFVBAEQAARQAQBFQFRQAERQEBAFFAARRURQAFQUEAVBBAQQAFBFQUBERVAUURQVBQVEAQQQBBBRRBAAAAAA==";

const chunks = {
  "typcn-01.svg": new URL("./typcn-01.svg", import.meta.url).href,
  "typcn-02.svg": new URL("./typcn-02.svg", import.meta.url).href
};

register('typcn', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
