
import { register } from '../core.js';

const lookup = "AAABs4kZATIYPhqfbZgvWB8yVEaUJ5Y3I1UoZSZ6hSVmhkN2M6NEZSkwVVUxZmQoWEUCBhEiBxHICNwBAgaAA2UCBQIILo4CB2UcAa4P5QQPpwMCAgqlAg2uAQIJL4IBAgMD1gwEEQwskAsEBiEEBQENCQNI4AECWQEyCQ2UrLWvJTVBos/z0FDsZCx+v7C3oZm9iaRsK53P2bz0Zdo5GkfcbJvhSnFQEWesGwfdPQPTw/+H2s0mKP2KkfYw7t1XDPE31jLvw6GLLdpb2z2mYCrXXBFpDTJDNMDan91ojANEiLvtovctgeeXHq5AN99AnAuo+/vUDxZpdLCVARs8eQ7f3TeJNpcgWwyUHri3e1zDfjv/xZ9HFSmVuAsOq2ldx4Ok7xOOIzDDsyTEl79GPbEEmcF8mJTFeqV5gh2mJFRFvgo77nuPGlu69Is42b/pbOr0vi0XoOATZD+Ydy3V9TkohZaM5Y2qOO1zNKBE5UREM1YHX+tfivvRBYL+ops6be0A4SLHNPldnXuDAgpwY4FXKoEskU1kF8VpQ/xpbxQ6/uNrkKzuMXHKrwJZSAEACAAAAEMgAAAAAAIAAAANc3Vid2F5LTAxLnN2ZwAAAA1zdWJ3YXktMDIuc3Zn/////wAAAAIAAABNBBEAFABQBQAQEAAFREQAQFAAQBUBAQAEEQVAVFRBFQBQERQEFRAQEQUAARAAAUEFEEQBQQFFBABAAREQEAABFAFAVQRVERQBEABQAQAAAAAA";

const chunks = {
  "subway-01.svg": new URL("./subway-01.svg", import.meta.url).href,
  "subway-02.svg": new URL("./subway-02.svg", import.meta.url).href
};

register('subway', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
