
import { register } from '../core.js';

const lookup = "AAABq4kZATAYPRo5aI//WB9ZOFhXRhclRTVBRIc1JTVFVkOHlkJKRnZyBFdkNlUHWD8QCrMHA7sCDbQCB+wBGK0BAy0BSAICETzuAQIBEwsPGQwBBXX9Awj2BCqZDAY5BDLNAf4BAj8UAZ4BswEFBEUCWQEwGr3X7CFkaWDW0iW+9xtk83awB4RDRyBbgYwD3ZDVHR5TFmxtEqid9JzrIh6UczbwR1NzDb2taeNHNTeto0g/SCRN8n4iT6y+1NYLmBttSWaV2ylarD4JEaOFN3AFD8XdTfV42qDSYmdMbN7VGP7Gjn3lhQTK3Ig05IqVtpDor3/y6GxHMujkzmsYvyjKnetfMLZYyujxKomERqzQhjMUUOzPPH1O0n10Kr9ZNQRRR4vXPw3QQdHCtC6b0DCuZ12/XwDPuXZnFR2qHM9ddf11HRSnlWB8rbynwyQhx0qzeyEQKtE4LGwmpdt8e+TBG15sCnC63WsYAA+hvLy/bTfFeQcqjFfrlTGsVrgzBbRzjJCAtUdQIFMyYCfWUMGNAAHSxv47u1p7rZfk4nz1coy9QUgAKAY4AAEJAgAAAAACAAAAEG1kaS1saWdodC0wMS5zdmcAAAAQbWRpLWxpZ2h0LTAyLnN2Z/////8AAAACAAAATBVRAABUEAAVBUEUFFVBAUBABAFBAAAVABQAAURFAEEQFVEEAEBAQABQFVAAARAQAQBUABAQAABEAFBAQAQBVEEFEBAAVBQEBFAEFQAAAAAA";

const chunks = {
  "mdi-light-01.svg": new URL("./mdi-light-01.svg", import.meta.url).href,
  "mdi-light-02.svg": new URL("./mdi-light-02.svg", import.meta.url).href
};

register('mdi-light', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
