
import { register } from '../core.js';

const lookup = "AAABr4kZATAYPRq4CtiqWB8WVCWpU0WDV6QoU1Y0RHVENpRjdGZkdihjhEZDdFECWENbBAElA4IUiWACCVAND7UB4AENA+cSlgQBBxs5AgECDwxRAhUjAQHZBAKeAQQELQIGdhGGAYIDAnADyANFBQUHEyoHAlkBMLDYPT0SM7msJyRBO+MBk5m1HvTsFUNvObWWsEbuNFEpHa3kadmSJ5rPxEORhzu3f6zwrXbn77vNEgcUQUDhz2zOtbjIgU4MIU7vwSi/lcPVUAdn2QcVd/86AZ0H/DFkczu1DsPteliMMUKPE6ls0K8M9G8DrKNf7OodmEwd/nPEvQ+VjRgbiZ/w4xy1nMW3qRvwq0w29KF+OL4Da8niRUNOz7ph05lRI6zKzfIsC6Cm5x5S0GkXXC0W3nqVnRKA6W+CMll+FtD7Dx20Hh2SI3WO1wcyR2LwQ4O+KlKYMM9lYbV52gzrQUQOPkGUN3wNlf6+p76iERQxyjVK8p+kWBkhTnm5beH6hANxOAc42qfcA3UhnPdzWdNo4bdgyWIgjacHqBndh0dtxiSh6D4Lmx1IAgAABAAAARQAAAAAAgAAAAllbC0wMS5zdmcAAAAJZWwtMDIuc3Zn/////wAAAAIAAABMQAAAEQFRFQEEBQAUFBAFBAQFRAAQERARBEFBQQREAFBBFAFAAFBAAEFAREABAARFAURARABURAABUAFAAAQVAFBQEQQBQRFQEAFRAAAAAAA=";

const chunks = {
  "el-01.svg": new URL("./el-01.svg", import.meta.url).href,
  "el-02.svg": new URL("./el-02.svg", import.meta.url).href
};

register('el', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
