
import { register } from '../core.js';

const lookup = "AAABqIkZATAYPRqEBvEtWB81JYY1lFRlWmpTdWNHVREpeWdEJjRCeJQVR2NlYzMCWDwJBAF9bxABpQIeCwWEHgq9IQwBAh8eCikBBww34g6CAwaeARgCAgwBBAUXcgMC3QEYJRMBRweFAgQ8BQMCWQEw4VK1b4fjFrVA6ZhsB89+bRLuza0RA/Aht5/sz9CSdavTDnon2h3D4eodjdwtWAcbWRnBGSG5/KyZMo9DsE5D8ANpByRx+kGYvjExmp2/rSk4RyDZJ9VMtYLNMzfPDMUD5zkHSgeV13/ZOonyvRh1HXecEjtktANn768okh6TqbVCtWUNog/EPsbsfDIeu43kCzWh/4TOBztRo064pzSMC8/avm+f8PRBc5Sg9yGpYedsoRNBD1AVw8oUHpE9OwFgc9CoygFhtx3E/pV5R22+gEwWDH49yW8+YhTQF1iV65X+3ocSBySOX2jyUjD0IzEjrNNOrLqWGxUs6O+nrCprp77dnMg4m51itzhpRtiBprUOXO0dWUP7g04dDEWZQ3NEQfSk8OPiHOE2ucmwdnp5UUgEBQCwAAQCBAAAAAACAAAACWVsLTAxLnN2ZwAAAAllbC0wMi5zdmf/////AAAAAgAAAExQBAQARRUAFARBEAAAEEBBARQEEVBAAABEABABEUFVVAQQBRQUERQQABRBVBQAEQRQFAAQRBEBBAQBFQQUVAQQBBAFFBAQAEAAAAQQAAAAAA==";

const chunks = {
  "el-01.svg": new URL("./el-01.svg", import.meta.url).href,
  "el-02.svg": new URL("./el-02.svg", import.meta.url).href
};

register('el', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
