
import { register } from '../core.js';

const lookup = "AAABq4kZATAYPRqfZ/bSWB8zFTN0kjRUVDhhOCdUNmaZRKZTYmSEMzY1VVl2Q8YGWD9vCQIERs4BBAkFIQGRAgMb9QEJGwEEFYEBAXFd7gzsAg8VwyABEQJ8LAYNNAoHOQUEARE01AQJIXYEAgSrdBACWQEwsB07Q5Xra7VR7zK0J3y4+3ZiWR1Mp5Q9HmEMKr5fAeKSQQcYFvQ6ShKBzx4HHQ8e1RVF8OOn2lnKqcPEYECmzqMLaR01uxUhOGy1IRJG06yPjZXyvUEjA7+HYm/+pOlsmLcOh8rwJELoeRfcrKkUUe73dXnq9KKdrAGRThnZ2ZUtulDD8mFxmMEWQ4m5gzcDOHMZ4cYDtyR3zTlvKNBpjAcwMckzz+e+em3aIY7PTkcn4Rzs0G+STsTNTGjsXLCcQYREZRIDI7XF3q/Tt/AbQ6jQf88xq5l6oT7I/lKsvgvXOwwRRw0HySwHNDhB4RM2nfwgB5nYDBTnoL5SDmd1KT2tofSaD+ONMpb6pztOczG5WJ//WJzw7W0dtUOC3RubfpWfgO9ztR21B63kZJM+fkgLQQQAAgAAAAAAAAACAAAACWVsLTAxLnN2ZwAAAAllbC0wMi5zdmf/////AAAAAgAAAEwQEQBAAAAFABFBBAAEEUUQAQUQEQRVEBAABQEERUBABAAFQAABFVFBEEAAAABUQBEUARRVAQABAEAAABQVAEEVVUAUAAFQEAQAFRVFAAAAAA==";

const chunks = {
  "el-01.svg": new URL("./el-01.svg", import.meta.url).href,
  "el-02.svg": new URL("./el-02.svg", import.meta.url).href
};

register('el', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
