
import { register } from '../core.js';

const lookup = "AAACA4kZAXIYShpdxAuNWCWJQYUnU4ZGNQN1QYdTJCW1ijKmVGBjJ5RBcxaDVEiZYVc2dWM1WE3uDO8DBRyZAWMBAwlDnQMhCToFB+MBCV4MAQgDGwYSizV/5QEFEt8CBw0ICNgBxQQCCcIECDNHAZcCCgFvAaIJDgg2nAEYARwBmgERAQJZAXIM9HWVBEVisKBlgFOIKZgKUBdQfnJgkbb15g9ZhB/TK+ozvIKNeodH457dXwdzq8c/FEqlTm5sEIeJXbwQ5ncFbIK9RQZFxxloaXyo+1n4kJ3yR3GbRkQ1ju1m3NK7a8NhurHvLvQuH+uJjcAwhVlREN3f8RldupX0cKkS7b47ZyEMOoS6+n3StuityzdcqsWDdRk8r/cSp7CMfstN8vmAng5Yjmxjo/2TDGF0JyvQ+D1vWq58qoxZjdXVeS9rwCU/iZe/l6rvZ9bXTtOQa+NCiRGuvStdvzem4nbu2l8lZ4Fpc6fom4i1ZJ5IYwC68up+3T9Ucn7t7l/+IlQ5QwtZuYLaBAoB7nN1NwvUuDQ9h6ydKqbVYRv0u4dwFvO9zsV8P44CDHo0gTCBSkH45osHdDB9hSpaFYPKj3E3a2hkNRQPa+yi8aRs5RlHtZ3TORpKQFCItEdsKuGsgpW/cdUo3lryFV8vHifeHR21XmLEhdHfSgQAFggEASVAEAAAAAAAAgAAAAtvb3VpLTAxLnN2ZwAAAAtvb3VpLTAyLnN2Z/////8AAAACAAAAXUQVAFQAEFFUEEEVBVEABBVAAUERURFBFFEVQVVREQVRQFEBURUVQBQBQBEBREUAFUQQFRFFABEAFQEQFQAFVBEVBAEAQEUARAUFAVAUAAVQFBBRFFEAABFUQFEAAQAAAAA=";

const chunks = {
  "ooui-01.svg": new URL("./ooui-01.svg", import.meta.url).href,
  "ooui-02.svg": new URL("./ooui-02.svg", import.meta.url).href
};

register('ooui', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
