
import { register } from '../core.js';

const lookup = "AAACA4kZAXIYShpBoFvGWCUndGhRVmtzRJSUU1ZUpWZXlHg2IWg0ZjRYVVNTMZFRJDVYNXJxWE0LDboC4QQSDhsNxJ4BGwaOAgQIDuICCTMFLw8CFwPmGgehAbsBBwzWB4oBGWICpAEGCAMuKQgGmwEbM0AOBAIFtwIREkLsAQsVBWycAQJZAXKCyo7D1dYGMCKXKjc3axKH3WPTZ72J7I2urqpneqb+ufgRiDU9wD+HnUNh4Wsex18u8kC1aYKgO4+xgSpxWeb0uqoKnjewYeZd78sPGctsbK0ZWjNm3euoIavvHe1HgY3y6BWJ/XHyP2C0OliN7bVBY+oWSjSCjGww3rC+DyVZU5PllT3xWnyX+x0LEGxiOWSJ3egOjkaLtrsu9O16lS9oFwJ9X6UvXbinUUJ+4oJrpD+i3ptE+IeEXGQ1qV9Fx4Xj1dS8pmeFB/qedQTxb2mBtVBz9dyFGVByAJHzHzAHcSkQJ1CVcBQVTXOnfnDE31T0vIkM1doao1m6+XknKgFHWcBfNxSEtp29jN9s0zl1VF0Q0msLH70bWu5eK0WdfUormLvuStCe0vRrv473c4M8KGJ2EvJZ5u6Ar3VorD+bDEeQrNUMdONOiE5+2tErunwMuoMFv2UKd0cl07+Ih6qQdEg0fhnORXLFYep8gPgE127FSkIAEADAABCVQgEAAAAAAgAAAAtvb3VpLTAxLnN2ZwAAAAtvb3VpLTAyLnN2Z/////8AAAACAAAAXQRVAQABBERUVBQQAUVABVAUEFQABFAQFBQRAAFAAAURBRQVEAFRVUEQBQRUQQEEBEVRBBVVARVUFQEAQREEFBFFBBEVVBQAVQUQERVUBRQAARAUEQVAUVAEAUVUBAAAAAA=";

const chunks = {
  "ooui-01.svg": new URL("./ooui-01.svg", import.meta.url).href,
  "ooui-02.svg": new URL("./ooui-02.svg", import.meta.url).href
};

register('ooui', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
