
import { register } from '../core.js';

const lookup = "AAACBokZAXIYShpabWGUWCVllTajc3RnNhQ0JkAlSnhHRFinVHZ0ZFBIU0SWcqN0QjNENVQZWFAOBwiqAkwB7gNrCJ0BugEKQx0FBlUBCzYBsmMBsAH2AVIYAgKhASqVAvIGDAsiCAGZAgYUA20MBAkMBzmiEx6KFSusBQcCAQgZCggBAhXxCAJZAXKFaGenP5XSglqur8vfJ04WvFEZ7WzXBiqiNZ3mGXw6eocev35zTZ59vVBa+0a2idN6OYgpjpDDiWneQgQ5kPh8/Yjq7VAdL/SYgAoUIQxY47s19Crd76jugazKtiUlRbo/vXxrzvK/YA+OgkMZXVw/M7p+aHcrH49rh2JTVHIw9Ufly6qkuIcu1WeIBRReWW/SOxcVhSJhjBLyazfsMKlF0GVdXwxIcb65cgDtL+ae1bWsEGu7DPILsNpH3d3voGcr5pfaR1lfAhnF/uPVl0d1+N/yY7G86J3UhxWEH2zhuoGmbGJfEKqrpY0/NO6CUMcnjH4HfWFsN3ZKQVoPB78Lrvl5cYNxkWF+ga2VaWbHQI08+vG63KfTcA430040Co5ZGyiL3r3A63MMgMR0dD1dBNVzdYPAiYm1pjdKhGvq4mQSsOhZ9D1sK1mq95tfxW5182SVRZ6C0Y0aLlQd7rQwhRCdEfT4k3ABmypjSqO18dZESkCBQgAAQAAFAAIAAAAAAgAAAAtvb3VpLTAxLnN2ZwAAAAtvb3VpLTAyLnN2Z/////8AAAACAAAAXQRFFBUUFBAAAFBFFFVEBEFBVAFAFRUQEFQUAUAEVRFVVUEEQEUUFEQAFREQEUAABEQFVVEQBUBABQQFAFEFQRUEUQABAEVRUEFQAQBVFEQARAVQEBBAEEBBFQVRBQAAAAA=";

const chunks = {
  "ooui-01.svg": new URL("./ooui-01.svg", import.meta.url).href,
  "ooui-02.svg": new URL("./ooui-02.svg", import.meta.url).href
};

register('ooui', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
