
import { register } from '../core.js';

const lookup = "AAACGokZAYMYThoxHn+oWCeJQ2ZVMzVaVmMDQ0N0R1NnY4R1VEV1VkdDVWUmVXRVRHeGgmQyVTZYUVrOBBBoGA4zAgMiC6QrMqIBIgsaAgIGBZUDyQEBAQNhJwUjCUAc6QEFDCAhKgW2ARioASEPEQgIdFgDBwQLUQsDAw+EAk0TkwNKB0MEFQZRBAJZAYN/6vs4v2aGa5NzEmAgl5U/QSpogpWVaQ8FaXwPAf6/EUIWZYEbdRAWFwcw0qyIXja61Y4ta1XKYaM+ShygA3NO5BmYfuu7etYK+VG6CTshXhdL8tZj93+Flatq1iwFHmzMDUL9kpAlzo8iqaZZjLajP2yCHqWObL+cvhiBabKsz5vPt/PXz5ZiUjAXj8NRDZ/+pBfISUiFvmDl/b2K0+66KuS7Fp8V7OYCdMY5oFJy/eqL5r918sSxl0bMcvLMRz1VuQkQ8kVs+5zs0dDlvqcZMJaNaI+tVDqbXIy0B6/E6yaVHAMiSYv2MdNQ6GUvsPL0QGSzsy5RWFXrZ73Fxbl3PsEv0Y8U4/21O6Ezbaepkg4ZXl+xy5Dm77CPcr5AB5itrJWoma/JwlsM5qyOHpQEep0Q233twVxRHDI78FYfttu22W0fBTmpbIddQYUV4T0vqcHi7YJ7SsXJkkRVBayvqQKecmCdCY4PiHqBZFDiQjMcFuRJw3Yy/g6i219YTyGDLJBKBAAsAAAAAQAQAQAAAAACAAAAFmhlcm9pY29ucy1zb2xpZC0wMS5zdmcAAAAWaGVyb2ljb25zLXNvbGlkLTAyLnN2Z/////8AAAACAAAAYVBBAQAFEUQQAQVUBUUFVFBBVAARFFBBAVQRUFAEVRUUEAEVQAAQARAEUUEBUAFBUBQBBRVRUEBUABAEEVVRUERRFVUUEUBUVRUEERRQVFQBURQEVUQAUAQVVAUBBQBBBAEAAAAA";

const chunks = {
  "heroicons-solid-01.svg": new URL("./heroicons-solid-01.svg", import.meta.url).href,
  "heroicons-solid-02.svg": new URL("./heroicons-solid-02.svg", import.meta.url).href
};

register('heroicons-solid', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
