
import { register } from '../core.js';

const lookup = "AAACGYkZAYMYThrMbh/fWCfFYySWBmZGU1N1ZzR4ikMUdZaEYjY3YyR1ZhUUVUE1Q3ZjRVVFN3ZYUA6LOwLsAQ1zwxB2ES0eBQMCAgcBFQcXGgrcBJ0EmUCKAwoHBy4DIaoBB5YBAhdsRBIDOxZLcpsBEAYdXgYbAh4NogIBGA8GHhwYAxC0Aa0BAlkBg51+u7nDD45eBVwUEFLFWMWM0j7M22qilkXTHNfLZJBBmPKVXzIfOXJsRFCjzwWOtnNcYLYxvpa9B+QiqGLrrBkfHtYuXiH9q70v5RYF01VYzzoWgqwe7Id/j8XRYbbyPU9J2+gQnoMJRwSsB76vp0tsd5NRRhzlgaEZjwOIUX0ctOsmCRCl82eVnEmbOYp1UK+OdUJo5rMsMiVoKvIJyO3W7e+b/vevL/IXQKxKTqYwVRaXP2CLuW2PMIx6iLHya3/9qZVycsQFVBX+2zvqbA2QgaDB5OLCgny6AswPOFWp2Tb+lW2pj3rwsVkzt/Z0qVYO6z1pnbo++ywRxNUO7o5CvpASW0iZyWzOv0Gnn10KHrq+MNEX5F4q9LvJwY8bQi9k4pdJPxXM+S2cFzvPreZypMGSleOSv8OFZpKCaam1SiIPUtDm1hisc2UcrWAZ5mxRF1X9a7AHaQIWs787oDO/IGUMQOqVdiFjeoXhmHsBo4FfhuzKlIX7DQPGsLKLjZ9R/UogAgCAAMKgRAAIAAAAAAIAAAAWaGVyb2ljb25zLXNvbGlkLTAxLnN2ZwAAABZoZXJvaWNvbnMtc29saWQtMDIuc3Zn/////wAAAAIAAABhVBQVFRQBVAQAUEUUAAAEEAAAAUAEVEBUEFRBVVUQAUFFRQUREFVFBQURUFQQBAVBEQFBQVAFFAUBBUFBQEVBFQUBUAVQQARUBRBUUQBVRFQBVFVEQFREQQERUQUAUQBFEQAAAAA=";

const chunks = {
  "heroicons-solid-01.svg": new URL("./heroicons-solid-01.svg", import.meta.url).href,
  "heroicons-solid-02.svg": new URL("./heroicons-solid-02.svg", import.meta.url).href
};

register('heroicons-solid', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
