
import { register } from '../core.js';

const lookup = "AAAEKYkZAw0YnRrXaseaWE8zVTRjNjZ0aHUlVmSEV3OHYjMmdThUZEMnVlRSdFhUgkV1UIJEVGNHOGFodYZWJjUjN4dWVnV1Fkc2SEmFVUN2hHNCpGFYSjJUcyRBd0YDWKQMFxsPBCLAAQECAQ7GAsAMxAFDcCY7AggdCoAExgE1B3r0AqsDLwEEBUJgogIGCgMVQQqpAQIfFx0aUZECcBMXIvUIBAMaRzICkgEGBQgRBAg9HCwJEvELOwbKARRvMRMBBwMHAnjxAoMBBwOFARgEowMndq0BbxMhBPkDFJkCBkbkDwUbAQN4CgMtXAICjwIJogYTvgEFAwMKBqYCCA+TAmMgAwJZAw2JliYxIgXTejkaB1t539M/TeJrdQe+0awGE62vG+bUecU+tP9NuZCOBzVb56ckQmXh6oTL4REdvcokCqp7V/BpR5al2oTaU8Pt5kJQyqVlMMXevuyAjhXirNElnkLNsKXSjPz3bQDrG0GSJGP/kodd560mS0Zns852sDgZeQmj9DMZGm0xTKxZzigAK5zx1+PKdTnq8hutZka9Fhyghqp5c+2/ujoE3dN5pBwlNphu2l5ec3OTcnUc8dwNz9aYlkHpQu6xRX+ccp+CmKKnrOvXyjW4IATF5x4F0YKSh5Bfxp/Hrtcb1ro3FCxCDJxuWb+5UWHQg2wxczYMvxjcMHgXjQmDjv2j/jYBWV3ZqO6HCENs7SNTNmRyi9UNV3e60D33ZImJQM0qc5Q5xdwNJZJ0gmqGmKzhxYhxm2uKqXozJOKxWIQvQe23ln497jXCXF3e3p4qWHNPNxTwO1s61hvllubrc9ZkAuLPSl/ourQlCzy3ur0sexjzCqvcIvfhDT7mUddy4U9qLLSFmxDvnf9F8H+VDUW5DxtCNtpcFQMtrOAZuo+Z5P4YSakOFSX8gF9zCwR+em7zJr4Tcan92al9XPQqvVCXB0z21hdWBENYnVjJVeJguiJFit4mfc5r5pPC90C5T//tEVbQnFh0uyB3E9zjXZs/50JmO6y7m5IYAWypxMQ7LOhV8d6VxUXnlMfme/ORXwpUB7sbOyiSot0aTCy03g8nI6ekNL+BjvDXpeRXem7DYFgW38zA0j6YBkEH1RG67o8Hlr7MKwzMx14ZJbFQqJz8B3P8fytTqhoM+vUhEH/IbmnPM3nunl295tCfAwrz9PPy+tfIShVI0WS4OkdeHSkGg3yA3jZPWBoCeSo3u1uHvpxwJw9P97mj3RwHo1I/LJS98s8Lc4WloxgSo6ABVHvxQHfUy5xpAb1LfgDabrifco5dLoClgAIh+YUkD+gcwCMuw3otuyGMmONdIDW2eAyQ4+rMP2nLcJtKbKbJawH3ai5ir+HXWCCxq5LiFzTCRyS89PAFt+UkVAUACAAhgEBBEAAEIAiAAAAkAWQQAAAAAAQAAAARZ3Jhdml0eS11aS0wMS5zdmcAAAARZ3Jhdml0eS11aS0wMi5zdmcAAAARZ3Jhdml0eS11aS0wMy5zdmcAAAARZ3Jhdml0eS11aS0wNC5zdmf/////AAAAAwAAASVbskmRJABapkWLJGAThESLEEzIsEnKAkjZsiCKECFSFETbgiVJgElZEAkAMGAZNC1KEElIIERIJgUDEE2JIETbJCDKlExQkGwDMG0DIkiSMgjBgEDDMikJMEBCFElTJkxbpgWIgiyChkgTMgwANgUCFCkDggBTkgwBEGgSlgQKpiVKtk0RJkkYpgBBEgCREAXbsETDJCwTpmEKAChBliiSIgybpmRYJm1IgEwLhiEDIigBtGiIhG3QNCTDEGnThknakgABoCWapkTZMCmQECnZsgkLBABYhCQbpiSJhk3JBg3IIiUQkgGBtEwDtEXbMAFQBGVLECFQgiTCIAAKoASCNGQBNGkKskyRFgFLIkSSFCTDsgwTBgGQpGQRNgwZlGDDNGnBJAAAAAA=";

const chunks = {
  "gravity-ui-01.svg": new URL("./gravity-ui-01.svg", import.meta.url).href,
  "gravity-ui-02.svg": new URL("./gravity-ui-02.svg", import.meta.url).href,
  "gravity-ui-03.svg": new URL("./gravity-ui-03.svg", import.meta.url).href,
  "gravity-ui-04.svg": new URL("./gravity-ui-04.svg", import.meta.url).href
};

register('gravity-ui', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
