
import { register } from '../core.js';

const lookup = "AAAB+okZAW8YShrLbeesWCU2aENkF5NjZDJTVGMjdIl0RaQyqAYlRnpSRTNXWTNURmaGRWZDWEdYpQNtAgIBZNYBAa4DAhALAwMdCSQB0AEJBeYI+gICBQM3mQkC8QKiInMBCAWEBQkBQgkDTcMBpQMSAxVTBBE8RgU6AigQEwJZAW+MJbIT5bmdVFx5KnlthIZwRZwAcoetvyLfCdv8As1+GZFbyyLDp8fKlSzk5y2pC3gWQ65NPbNbHB2ix33aUfT97hdDA9zc+f7YKD9FDLMHhgKcCgYjacNw1mwu2k6quTbiqPeihkp81D+8+23Mb1DX3D+5tw1xVNyv/KHfl+bQi2ljAZyTUM6X23ED5JV61VsjdRBq8NkVXHk5slWtXHwEVD5/83OeYpAT9jKgPGV/eyRghdEQM0MarkwcyFK/AoZbrVnynf8nSO1CXJRlTBS6u6FpmGnDdk+i1N6yAPPYC2gq9E0CYjZdMaOH6i7lqqwJU38f9xnmQaJtfovCdp/0THofQuZXSlBySovowAvCfq6VuylsWoWCSKWF2CK/XVGlpNTQFwzPxKDWq0eTO5pcfq/Ensbc8ypz1Hwdwx64uLTecncxjeyEMiZYGaOqsvOeQETknzXaqMJo6/lQk+RfagUhQjDFPG9L0Af1JVaSSgIiAUMQBhEECAEAAAAAAgAAAApnaXMtMDEuc3ZnAAAACmdpcy0wMi5zdmf/////AAAAAgAAAFxFVREAEEBEVQFBQBFRBVERUBVFBQAAAABQEBFVVURQARERAAAERUFBBAAURBQBAAAVRVFFUEUAUAUQREBEEVAAEQRFRAQREVQUVQQEFARAFQVEBAQUFFVFVEBEAQAAAAA=";

const chunks = {
  "gis-01.svg": new URL("./gis-01.svg", import.meta.url).href,
  "gis-02.svg": new URL("./gis-02.svg", import.meta.url).href
};

register('gis', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
