
import { register } from '../core.js';

const lookup = "AAACBIkZAW8YShoHJNXSWCWmREVVd0wjk5VlQmFWQ1NHM1dDNIYjdHCHSHdWUhZnNUVYZzFDWFFL0jUZGE8BEhT3Am/OXBsBAb8LIqEIBmYSngEZAQVAzQQKAQTjARQIHQIGjQHFCwXiA50DsQOgB5oBD1txPwM/tQFyCBEDgQEB0QUa/wECBBcCWQFvJcNsbELcT0jF/HxoIzwTdVSGBbddoUpy5sS5UFxt8yJd88jfktRbxNet8GXn3L+NKltRqZgxWlu5AlcZrQKqxuIDp/dZUIXOHPdHOYstfwBQTuoMh8Ncoionz3C8atzfTBkHM4wJ1A0fMZNQhXF2oq3mefL5lbiEC3/HNtkoXJwfeVOyeZ5N1R5LAJXzsrI29Lnkl3PMF0Wi9OzaLE3DGqTQFYeRpVFiaApIw9hE64ZbQ0I1wgdlAUq0F66/baNC/EOzJt6giz+TPwJpIp7uBGKTkN6uVIR8C5SfCVx/1Lv7yrNYsot4y+UkuJ47laVfAimvYH7cJdaXqwtjaeZvfnKsIcLHqFYwaXs8cVLknUB+of/R1hRM5HDQnB3bb66GaRDA9hBUMhn0qkqqmgMcdjLQ2uT96K8ianz5FvMqXEW/qHKCutt6BqJ6PT+Fu9idI5yjQaDabe0uLlV+5YZMnx0+9f7NfXPYd9TCDBPcQ0oAIFAKAEwQCMAAAAAAAAIAAAAKZ2lzLTAxLnN2ZwAAAApnaXMtMDIuc3Zn/////wAAAAIAAABcEVVEUFAFVAAAQFVFAQERAUBVBEVQFBBQAQERRQRBQRUVEEEAAERAEAURURVFUBQBUAFEQQRBRREVABBBQRURUFQBBVARAUAEQUUVBAEUUAQQAVBBEEQQERVFQAQAAAAA";

const chunks = {
  "gis-01.svg": new URL("./gis-01.svg", import.meta.url).href,
  "gis-02.svg": new URL("./gis-02.svg", import.meta.url).href
};

register('gis', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
