
import { register } from '../core.js';

const lookup = "AAACAYkZAW8YShoovZHMWCVWByUjU1Q1VWZHRyRwGlRmVVVWqEciI1qXJDZ3I3gkR5haZhQ1WE4wLAwkAggBARgCCA4tHy8jNQcbBwGzAdkLCA4OGwENJiHrAgb6DesVrgERAgHeOzfkAmQDhQECIdABCAJ58gEKagLwBK4B/gsrFEkkLgcCWQFvreTDVVsCIpKiHCKaW0qyewnc3uYQ5pO5w0TI+W2ofVrfofkLbS4cqXJceWWyxymdlxVvac4sXS5xRWA2akglS0MdBEL35YW5edBN81LGtyQ+SuxBHtS7As9yowXUvOt8rqDEb0VH2pdpAYaEdjygojyl9hBfuu3WQo2eaZ1D8DLL3LSVHQn813zqGeT0SHNQ9FQxsgtKeEOEzdQDx0wZHxmLTEB3kTYj2IvFnMOv9IyQnt4mF/uv2J8naq01hm0HaKLYVuU/2Yb34r+/v9wWwvI9W3I/0P3kn4eq/CLfXOQzuztOfHaGcwaquJ4qcAKsmFRCf1yni1EoLSofF7gAwHp5Xeiz2yqzrmIHC3raXFFM1Dlw22MNA6F+zCGVWQD+DNWUMYLmE6SrWMKFJdyq55UKnKWynGzRfk9/fgz/7lDKaYcwE6Nx3BSi8yMC2n9s801XGn5iW8PQrlPEXD+TwvNQVFCoMvV11q2Fk2VouUoIIEAJABQIIIAAAAAAAAIAAAAKZ2lzLTAxLnN2ZwAAAApnaXMtMDIuc3Zn/////wAAAAIAAABcUQARRAVQRRBVAEREUAEQFBRVBRABAVVRUVEEAFBVRVEUQQQEAUFFVEAUBEBQVEABERQRFBQAQBAQABBRAUBFAVBRQBQBAFAVEVRQVQAQRQUFUAAAFEFQBFRQUAUAAAAA";

const chunks = {
  "gis-01.svg": new URL("./gis-01.svg", import.meta.url).href,
  "gis-02.svg": new URL("./gis-02.svg", import.meta.url).href
};

register('gis', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
