
import { register } from '../core.js';

const lookup = "AAADcYkZAokYgho8iiSCWEGmVaZYYoVTd3YnhRZltTSUFyZUYVRGY3RGdDFSdlE5dUdEJ1dDtSV7VEFCRVRycUNGZUVRSHNWNGZnciJYQmcoVViBKOUeGCUN4UL5CDYGTwc5Kn8QY38CDbkJCj0UF6UQAgjzAUaWAQFAUgEGFgEHBBS7BI0DBAYDAwgeDWyQCAEVBsUBAwdKASkfAwIb2S9B7kH1ARAdCgEgBgwfAj8ZJWMGMStCBQjMBhgPgQECNi8CCQcRJwOZAg4BCUfNAswCBCkOAlkCiXPQqeHYxbdAgme/mRs9EtEHdaG3dSYJDOy8RnBHLLT0wyjRx/KoNnZgcyneOv+n2nHiDyKlI3+IQkj1C4uEkAGbrkWc7Rtzfmr4p7ZXxyk9KmxsioWi9DCpKGfA7XCkg5D5vOdH3jEmCclGVd4/0ny7ty6469lLC8v9KXqa8u98vxJRSPKWoH/FbVDP0lPKLq+lE/drks4or2O6GJzyL53kk7vkPt+cFmhe4epvgsYePBrxm2YmTuMfxqeiXBZXqVb+RCqmjzuVjloSo/zdzBWK+hLQnTO9g/Y4/aWpBs/85G+nuKaw7Cpv2Lmcizw5H3rih2JhmDIUbKe9JobQWA235LL+z0PajEQeTjnJgwBd5D8zveh435vg61Pm9ruHmecRaAmu97yW8KISdpK5/UbOjPtw5n43EPI8OFcVD1OdgWXxdnYMJ0QDDr7CS0GVZRGVEOKHPLcdi3shrAhh6AU51IvhHxejla3OLHivkUF7YPYkpAPWd2aeO0HXIrkY5UXd8L0wQ1rttI++5nHxoB2p+SqOX1EZ8cbEyskHIDXmjg055wkR5nAK7VHJUuvv5o+jnta//Wmrnkf5Ym/TPmv6UMK2g1gnnZShVvJ/161pHhstCP6p576+suk+rAoVkss7SMjvH4HQNPfghNYf1zBw6HqjLlCRD23DGsqP4x0VVIO9asIxzznfHT3fvCsOEaOlbcS7EY/7s0B+e0DJYcJtdfH4X7nJDQEsJWmFrDaGU07yHh37h6eC+hCAGQFY2UtXJCh/gRseAb+YPsGl6/J+IbVzBUM1pG3zwNfuo6zXpTY/u+x3mgZIMVHQHwQAYEJuZG4GF0HBA7qWrH5hB2ck6cSfSG3GVyFRAAOAEFIAUAQEIBRQQACwAAAAAAAABAAAAAlmYS0wMS5zdmcAAAAJZmEtMDIuc3ZnAAAACWZhLTAzLnN2ZwAAAAlmYS0wNC5zdmf/////AAAAAwAAAPSIlE1QFiiCAChREAiSBCmCBgXIlCARAC1REiUIlCSCACjKAGmZECQSkigRECEIkgEQAgCBAESKJAFboEERFAlJMEGKJERJFEmAoGSKFA1IMAlQBEAQgCFCoCiRFAQSJESAAiFDkGAKIAUJEiESFAiLMGWJBEFRoGCKJkBagkgAlAhQNEUJAghIBAEIEERAAmRABEAJACAQAiERJClSokSBMkXIAEAJEgXCgkTIEE1KACXBAgBSkiQJlkVIAgBQFCUalAACFmRKFCmKhkFYpEAIMmVIJG0QEEFSFECQgECSBEFQpCSCJEWRAgCIEgWCEmTRJiQAAAAAAA==";

const chunks = {
  "fa-01.svg": new URL("./fa-01.svg", import.meta.url).href,
  "fa-02.svg": new URL("./fa-02.svg", import.meta.url).href,
  "fa-03.svg": new URL("./fa-03.svg", import.meta.url).href,
  "fa-04.svg": new URL("./fa-04.svg", import.meta.url).href
};

register('fa', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
