
import { register } from '../core.js';

const lookup = "AAADeokZAokYghpqRvWEWEFUeDJ0eWUVhScxNHIiRFeBVlmReHODM7VWVVZmZFl0QSVjU3VlgzgkRHKUYlk1VkJ0JVM0WXRSJWKCpRZKNmeHRViKCAXMBPwBAgJmnAXDAh+EAUDBBtwBAwECAZMEEDQTpgahARPTBB2lB4UIzwEGU+gCCQwE8Q9BGxkUzwEUKtUBFHYZAwc9AzkChQEBA02MAgwQAQSOAwQBFBKlARCECzSDEQwCKx8BBgpgDREFAgKjCQoCTgEUBgE98QUb+DEUxiMUWZoBYzr4AhcDAlkCiWLl0OHGMAO/qQegOQBGgnXhMzXQCcHHaY/vsyIglY9sakFswihBjAk9vq/9futr5I7YVXbnofPsvKD66/K4hamvp/+9w+8BnMCjc8pGnR37+Vz3AJ1LuUgd+SpntvHSRlHRTvRqKgW0FRkz5GC1kCyuCPZIxppFh6WnS9ZR3ZvXozdTBmV2m0jAnhC+G1Io7ZVT5zatZamnIYt/rbLqJjDgcLdAnYspFAwu4zWZju3OvMnwNi+pH2s77no+AY/99Sk/LKw0kujav6in5L0NPLui5iQwtjq7bb5319+lwsWVJ7t/5vHoQ4/k7UGdHQtE6MmrDtmaozkmIc+/gRE4fznpJv0qFaUidVapowmcxobfeKQeWLycb3P3Fg8fmNa5bVBXPBNf/hFQ/MxkIyQXtD1HDAr3cMlpxNFFHSi4XhskQAOfbBhXJYM53uu9hScaQCsfjKlm47r+B3wOFqzL34pjgz6HkgGWc9bxMbxvhHBwKvZ40KTwe99+DRGmiBIb5F8RAeYPFU7yU6MmofJ8hrK5Zr1aWnbykwPJNs7Ggu8/FyHe+rqsrsQ/TghuH5S3/r9tizyAGKVUgyyvKIcG+tKnEst+3lcaBUTyG+cVpH6BBxlgQ9cJcWfTYtD5YGc7Vp7XSIPQ8aUESLsdEoPtWKMQ9JKs9nOHt3p2YZDUf25hyR4xp0ePw+zH6z6BHwuO4hJRolMGODnEmx6mbRCVe2ht/T34d3vgz4LsDZ5XO6WKhMHpkT6Y1x6iSw+st9i+nOEpmUfyemj7UUJx3c/KLhI8b71dlkKwlkRp2fK5wjLx5ou3+8XyQ3VBfmEuLWHCCuK7bTGRzlAf+OL8ylfJz3AR2h5v5ljm58hREGAMSxAEAEACIEQICACFCAAAAAAABAAAAAlmYS0wMS5zdmcAAAAJZmEtMDIuc3ZnAAAACWZhLTAzLnN2ZwAAAAlmYS0wNC5zdmf/////AAAAAwAAAPQaEkkKgGgCIASJoEkKkkTIkihKFgmCEgCAJEQQNEVIMECRFAFKgEiBAA1ZkkSSICgBkiAJgCGAAikBJgCRMgiRtAjSAAFSAABREgXRBCkBIiRJlAVQEClApCxQFAUAIEVKgAiAJGySEEQAIgRSJASZEgQBhEQChCjSlGAYsARIJCHCBARbMiFBtAmIgkASFEUYMgWIsgiRAkCJEiQSlGgJEgCAAkiINEWREgVCAimKIGFKhmWLkgQRBCQSBGAREgSTkEhSNEiBgEQRAAlIogGIAATCFEhAJCRBokQKhEASJgySpkQBsghQECkBggCSEEECpAQBAAAAAA==";

const chunks = {
  "fa-01.svg": new URL("./fa-01.svg", import.meta.url).href,
  "fa-02.svg": new URL("./fa-02.svg", import.meta.url).href,
  "fa-03.svg": new URL("./fa-03.svg", import.meta.url).href,
  "fa-04.svg": new URL("./fa-04.svg", import.meta.url).href
};

register('fa', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
