
import { register } from '../core.js';

const lookup = "AAACTokZAawYVhquH9XUWCtUSjRhZUUXJDIxckdEZFlzNEZXYkIzUpNSSraWVkSHdIlEZko4JER0VhiUWFcBFIgNAgYEBEcdCAsOAgEMExMIChsTgwU9D+oBCwzRAQvOAgMCDwIIFJUJEfggCjfHDQHKBRE9a8MFB5IBkQMeDQovI7k5B6YKCgoJCARD9wIyiwUUswYCWQGsRxCST0bFMLSfedYxojI2s2mtGMFKi1o3/gvI1Er23eYm7MuY3bWoVvLyP1UMQiocz/Nj3l+YVIXO0AKFi9Wn0bdlS4Pe/PcCwXQHyPBqNHOI0TOabOaHjeuTAFo2FTLuiCHKSSPZys4Y1giJnY30EszVn+QlNksXb9DOdbmMNCiFf7rFMQsm+TC1ZK1RFmsaApIBug4LWxrZ1fgrnY1Hxa7cJGwUEw5v14u9AvIOz4SBiIR1oHQoSAecaozmvmk7SsZ8ANWlzjX1e4wLD2oNhHG/JYzO/T4Quco/1NPNFTQ0G3aUZ93+hLFsu2QK+VTB6BusAWCvSHVgfIHxlQotzL6LOMV14bThHUcRHcGwlOfoDe/W9MWBqr42nisiD75QZTquPcabdubV+y1yOCSoqVYh8s8YKljH15iVYBL1cQgkvKYUaQPEsEaIw88FC+e+NoHccyPYer2H869U30CjsBR+v36huRKplI7Yij52T+fQ4UZZTXVRPl3mtMQ1hNtCyAbsLaCmUsAzQ4S/Wl9OlRZtp8GgYE2fLCfwIIx0p+njRAl1SAsDkrsVUO1LQCEWBMBQAQwACAgAAAAAAwAAAA9wZXBpY29ucy0wMS5zdmcAAAAPcGVwaWNvbnMtMDIuc3ZnAAAAD3BlcGljb25zLTAzLnN2Z/////8AAAACAAAAa4UACFERFRFVBQAQAVUIhQREUBVGWUVURBVBQRWSJYIRUQQQFAFUVhRBYQWEUFBVAVUEEEQABVVERQABSARQBARZFRZQVRBCUlBVBmERFARYEQAEBBBEYAFUVUFAABSQhQVAVUARFGUUWQGQAAAAAA==";

const chunks = {
  "pepicons-01.svg": new URL("./pepicons-01.svg", import.meta.url).href,
  "pepicons-02.svg": new URL("./pepicons-02.svg", import.meta.url).href,
  "pepicons-03.svg": new URL("./pepicons-03.svg", import.meta.url).href
};

register('pepicons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
