
import { register } from '../core.js';

const lookup = "AAAFSokZA+gYyBoITqIPWGQWUhJFpXeGSJVUKkRGZWg1clZ4aEM0V1WJVFJnUziFZiZpMiZnVUVjNJZXUlRFtaRKCFUjMSVaUhdEdTZDJVM0VFglBSVWJxNGR1N3OEZ0c0RnZFUUZZRUVpU3FmVzV3ZmVkRTWM8EARIBNAUg/RklyAEcdckDAfoPCggiAQgwAhYaowQnCwEsZiKHAaUBtQYdAQcHCWEKFDuUBjgOAgG5AhgGCgIELrUBJ18lAawBEgQRA9kBPAMDBAwBRAUEPaAH+gEKAgwncA1a0RQN+wfuEgfWCDIDAgEDGQH9CxYTbSAMogJzCQYiAQYGBwkVqAcNBAUIEG5JBYgBBjAECRjJASKLAoABAwJS1gMEAhp0BxcTExQYPwPXAxgHflc4yQwsAnYvOgOGAp4ESCMMCSQCGAkIAyUCWQPo+/3NMIMUPaNu7lbLDA0WSw/+UMdYRcB/4VZhjKqe/TP5A2imyZ9Qy7HLa8Z62IMSVqwTsi2qK3RQ5fAwIbOi3J6cW3uzq6oYdzjpo3JT4/pbZ5fE+fwpoHg6P1GucBgyX2uR638fVRsXKnjWp459nRtMWZRmcjcDl7C2u/lSPHbBl3VwHKx/5LqXaomQaSuD/OkxH/zyQ1mn4T2GpJiFc1Copm0QCT7EPlTHu+FNzWwkaQEDV9qllVx6FVdr4JsqAjGmGoU7kG0W+mLOJjOdQeM3ERMB47L2msrcVxThrxqOE7W2/hOxCN75Cp71kWiBb6EJ2Heqq7B5HqiE+wsxtMgQ2JYqlLKMuJK6N1aTijR5blOcGLk0pxtfmRiUT2ZgDg+sql1pj3jz1Lje5VR18fLMSqnZNZnd74L9bfGOFpRPnR9Ul2wkhrTyKcfBli+s2dYfjAxo9VNmqR6Gjlj0HZNDjmHwfvwS3Tfem89mzDvTwlipzyXSNYj3iSlNv0ZWyo+WTxsot/smhAax7aY57bYJGtyipM4/os7r76XGUj0UzXWKMYZQbdqmKiRNMVzh6UGpbEV079WDAaVOaodTRnrOK8eHxbegrxPyImfop/3ZoC1NgkPaPR2k5myB5LDQvd5DCdDfTnz3A2xKiBHJgfTykaf/T88aPby+D/edaZ7UGJg/6Uav41Aenf0k8vVBENWgoVlYeIVNdnz8+PdEcRkfevZxQDot6NQIWuRSIeVMkXGD0Itmpx2MZmKP/QBdM1jXKjEwX5Vrtgxv9M3VcDDJF3iokdEx4WukXNQhl5ZeghUswOogyBDTwgmcQFYJNVZVDlCWjuWWkmDsobn6Um7TgLqQYCl65FdPdr64RKp4dt49xMKiTwxlOC/nrPCye4rBPM/evHfX1TcsTx9PUUuABqw2yksCynWmiquJEAykplGEST1chyULTdr3EaxwEZJProUOwPLFuMnP5nZVRHmqGQp2v7V8+bm0O3ThC6lcwgJLxPQiCgrU2u9qY3zkCQ2xwKgUGHhG4gTxBQhNWWcd5gGrqvJZb1pgy+uSuslJ4owiqCY/hSp06IpeQw/6rxIBAxuulq9PEMLhDd8TLQCI8/NZ6XtgIgf0DLLaqnLG3OthezW8JGo5bOIhBhvnfB3/RlG1p3I9hP25aB3l3RU88niRfM7nc7O+ubBsgt+fvpzN3hZuAZhuZRzjPE2pju1KA28XSVjJiHJ+0fg3XNcA+gEI5xzU52hXIz7fnatBAoNU2bB9++/yKtLC/6NLHqv5HGb73WltP7oxGUNTyVzWe2Vzf+agGDn2I4u5cC6As7zTyzXdElgZIgAhAAEAIAAQAAAECEGKCKDCAEIAAoAAAAAAAAAFAAAAHHN0cmVhbWxpbmUtZmxleC1jb2xvci0wMS5zdmcAAAAcc3RyZWFtbGluZS1mbGV4LWNvbG9yLTAyLnN2ZwAAABxzdHJlYW1saW5lLWZsZXgtY29sb3ItMDMuc3ZnAAAAHHN0cmVhbWxpbmUtZmxleC1jb2xvci0wNC5zdmcAAAAcc3RyZWFtbGluZS1mbGV4LWNvbG9yLTA1LnN2Z/////8AAAADAAABdww3Bhk2UtgkLRiTRSO0UNmicUmmYFIgaCNGMguChNgCBdQEAOHEJcFIgASzBeIgReA4SklCEoowJYKSiMnEbMiWZQCVhaIgLmQARSIIcRwmSCC2LCMzUeEABtEgEpzCMFzCERTIcSEEZGTAcctILBIBJVAGjsEyihyIDAS3KQGncBwHiCQmMmSSUcIEMhAUYFIkcKOQIAEVTZMgREnAJCATgBKZSBS0AZEAcFAmQKFEaAo4USSAZFAgItqUSRDBZcvGUIAQAgyUEVwYYGCwAJy0jSEUEQI3CBQoYUgARsQCghCzCNySbIJATEuIhJsgLRmBUFM0YtmyYRPCQYQmSkOoKGCoQaIgYIAyamJCQAkgZIK4MEjEkCLFTQghCkhICpO0jFAmZNI0kcCoZJgiaAOSKBI1IOPIkcs2LkTEiNQ2aOGAkVi0SZsWItikhRtGAiJEcAiJbRqhhUAoRVkgjBOlMAoULCIFTBOkMWMYjImWgNEkMEGEBQAAAAA=";

const chunks = {
  "streamline-flex-color-01.svg": new URL("./streamline-flex-color-01.svg", import.meta.url).href,
  "streamline-flex-color-02.svg": new URL("./streamline-flex-color-02.svg", import.meta.url).href,
  "streamline-flex-color-03.svg": new URL("./streamline-flex-color-03.svg", import.meta.url).href,
  "streamline-flex-color-04.svg": new URL("./streamline-flex-color-04.svg", import.meta.url).href,
  "streamline-flex-color-05.svg": new URL("./streamline-flex-color-05.svg", import.meta.url).href
};

register('streamline-flex-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
