
import { register } from '../core.js';

const lookup = "AAAEmIkZA18YrRqQljA+WFdJVnVSVTZZNUNElYc0QllkKCODVCSWYWiGJjQjWGpYFEJjZiNSdXREWZRpVUZENVloJqZGIlRYaUgSFlWTRjFkNTBmR1dFZAaSg2RFhoUoVTZ0VFUaQQdYt5cCIi1UHCIPCixXApECAxQDAhIGFCDlC44BCAIEAawFDAJUGQYBuAMFEgoE+wHbASj0Ap4BAyRIAQUGCgPVATXQDg+NAgQOCAG8AQ04AwIWAxcGsQMeAfUGCAmnArYDJTMbdRYCDQoF1AgIjwx8AQHkDSMLAQotAhPnAgtbEhoQHAHLECABAQUWFwIFHldyBAQOEwQNUyOLAwHeDwxVB2OjAQ6AAdsCDg/NAgID4AELLiUl7RYDNwJZA1+X+6wJbcEV7MJNCfPPAWzG4jIK8gkWLLaBPGaXTM6/o29uySsIahM+vSz9V/orsgyRTYEBINUF9xOawkH2n9DyUIVJtetfYOtj4Tf8GNvTfXcuMUZhvqhTumfBJMt1JO8THAgb06Uc7BwiDMl4kefkYO7iFvAbvX2kaQGeFRo6U9dghzpl0mASh42h7IrFFzJbs9sa/2KcWzjIAnMD1N/OTtbN7uK7uKL2sGgMEEXZGfB2mqjDURTBI+Ie/cyg8M79hVpF1xQ5SV7clibaz+uOK8jNghROH6Hw+HgBQlZMKXj5iPfUDEcclA0HRoMGW+AHgsRlF47MD6kq8YfClUaQnC5sCnlU4wn0FOWM+qklw+8aIzAGiaAHbhP5nZu/hmkyJHiN68w99/cc3ktAu2nP1D+26qUDVYJ+k5GiM3+1t1Sj8d8t1kCmj8c4Q5oVh4ySp3DJQ4cEck4AO2qo5wZHasy2Gne9Fr6n7ar7u4rcgxMEiIytUlbrNNcQxk08rvQMnSSVFYqL5Tmz3TKm+sljGXP470qtFxRUbPud9n0skoJej1LVnGybUHy91lpsdOMu6XHKWbIKFi6XYdDrLW3XAMZ2Mo2FMOU8vOMXuHtLZ8M1wQG1ZR418P3uO9dX8yqzicx129KViKzF/yS/9g9P4Huvecu9tTbVgsqNdtzH2cNw46ElmUs77EutTDg6JkbnZv+5P0oVZskm40Oqf/HnFI/bXrOX9R3gtRw0NnUEjACovik8qqVWufY2kXC5IYqpS+kFpVYHN/57yzVHlFqGtmhXqh+46nfqjrZQnXaQbN3RfddJm8cWC61MPdfjd2VBY/JZsPWx6o9/Nmibh6cz+CLa3BRPOtYXgJU1+Pw1hKDvC17wcqshn9M1c8iOZWsn2Cee++JEG+UArdWlERTbkOoVL1nsIAQVBaUPehE6x5jKB3HE56lujzTxS9SSX3a7PJZeBaZEmSmPuZZZ3gtEb4eCNW3jN3E4mz/Y1wEfV8BVyx/Ps3U9M1pgaAoYbr3oGc6iOxin6zHlpXAg2iUWze2qN2gXGMdDbI/BqTDvdy7+LMZwggMg4IIwIfCH/B26/36oO4+IaBBlZDJ4ULebsb9t6OhsRLgmT7fUncdVDJE4t/ncnWnKVLvOAHjRP1ZAAAABChAAgEEAAAACAiwQBICBIAAGAAAAAAUAAAAXcWxlbWVudGluZS1pY29ucy0wMS5zdmcAAAAXcWxlbWVudGluZS1pY29ucy0wMi5zdmcAAAAXcWxlbWVudGluZS1pY29ucy0wMy5zdmcAAAAXcWxlbWVudGluZS1pY29ucy0wNC5zdmcAAAAXcWxlbWVudGluZS1pY29ucy0wNS5zdmf/////AAAAAwAAAUQQA0gMQimTlGlLoghBlClBkIwTliAANGFIgGlaokSLkGFZsEEAoogMJkjbNk0RwGBaQmCEAmWRuIxLpAxDkmhUsCwJgCARx3GLkEngMAjBtg0aoQEDCUxYAinYlgmKpg0KESGKQo2TNmlRhmDAkE0KJEIjRE1RkgDCpgiChimStCzQhC1asFFaghAIxggYsQGIoiyaIARToAVDtkyAxG3KGDBIICJCogDYBILDpm1RFCSBooVckmnLkg2SlkEAljCCEkSCAiAJgkHIhGkABm0QoUlLIATSpClDtgWQAgkZIEgLwgjKgiDhREoYAUgCmA3QgAjBGCAiIiYYoAHYpG3ThESRMkmJsimItgVLpmzBACnJiGTbMAjbAIRRCCiLJI7AiCWbSG6aomWLwoFSgAWIJjFRQmUaBE5askGSoAFaIIyDAAkAAAAA";

const chunks = {
  "qlementine-icons-01.svg": new URL("./qlementine-icons-01.svg", import.meta.url).href,
  "qlementine-icons-02.svg": new URL("./qlementine-icons-02.svg", import.meta.url).href,
  "qlementine-icons-03.svg": new URL("./qlementine-icons-03.svg", import.meta.url).href,
  "qlementine-icons-04.svg": new URL("./qlementine-icons-04.svg", import.meta.url).href,
  "qlementine-icons-05.svg": new URL("./qlementine-icons-05.svg", import.meta.url).href
};

register('qlementine-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
