
import { register } from '../core.js';

const lookup = "AAAFR4kZA+gYyBrLf/nGWGRWEnQlM2hUSHYSQxgIZCWIJSVEGGJjZohWNGWGY2VJE0FVZYhVQ0hnRTZyY2aFQkdFVEZHpXZGGIdXRiVlSTVRIqJUtGVGaWNGlEZVSFVyV2RUc1akVBFUUmcjN3IWhTRFhUuHWMwSFAKpAQYCCDFHAy3vAgUaDAECCp0EtQIHBR3lA9AICRoCAQT2ATgFURND7wWfAWRDCQEJPFRwcRwFgwkBAwcBIB5O+ASZBIgBBQ+uAwo4OhBppAEkhwENVWcBEswBAwoYJeQCowEFD5UPcigapwLnAZ0C1AIbRRABAjSJGQIEIgbDFgEOCbs5CAsjAtUEOQUJIiUB7gQMJBjmAisNCSIYFgkyFzUMuwJ9CQiuYAQYEysBJ/oBBwEBnwEFKzXmBQQCIAEy5AGrWQpo4QECWQPoJZ9wfmz8VShJxEjtIkFUmCR8e7G7crX601jHKvdWoC58Oe4F41gXUWyLBG5BWwgF9oCwwReiA97H1fC9/HO3rGuqAXNpIO90Ei2qsk8lFvW76lTSMAROQxIZSw4m5UmROZio17yoOfvYTw6NQJs0HbnpVaCQbq5ZvWGaXIPrw4gJGi2wegG+wc0kWV8OFysjW0BGdhZbMlvMKfYKeFB3WPN4W/shkaygLkvzcL2K6WPEl+Q0LEwSCdChJC41yUM3p5LG0MYUXjna8WWu01WhAYIW84XMFkw75qwVwfzbVIZXNruXB8xOr/wtQQU9HQNI+zAbXSG4rHo6hfnDsX6EZxSA5V3Cl3Lgdwjcvmvi/KDrwBv8jreJuDZKWXK5Zh82fKomN3D1L9c/fEJ81cwMlB0cDeX5JEFUithNs6ecQ/0bbuuevJtWug9GCwB7aIzBNM8H53IOkBQekSvUvDV6ZQvzIqLaxGEM6+Hd16zqXOJMUcP3tDJxKpbocmFphjc5SYw5e1O9ZInCdb/NenWaJ1a4VNIQT44o0q1PO/FplMWOnWe3WBZ1fOXi9DuoEM9Qsc2lj6vBmfGCb8bpUlyvF5WwGnAhO1yD+kCsp3kFLT+PTc5gqk2Fsqq3e7wm/3ks/oIhmDnc3Xr6ujkAVsQlaVZGCOD2/9ALlsq4yhULQzi63pBwnO5mCscfhWls2G3280sRHYctnMjfjMc+2ar81FDyNMSWClHjiFsqD/5Lh2AtT7BfRYKMN3DVMc+qt3FNsrVVTjfHIJlMlLBTyWKY3As9yvG2eA40ZZeLqFzmGfcjj6zO91ekTpl7PoDYBkFtMd5zhtMC0Nwb+empg3/GI/KocBKCBzq+x1GSYAasT4pwdjnYSU3u7cUTheIsAYPHkM8lf1mA19+5BSkS1WraAFdaTR0D9enjRGy/GILl8jDLWtbcE8/VgWOqXF8Q3Qk1LVK2QZJD9oj2cUNIt+a1Plm4zdjNd4/kTziUhzB7pE8Us0/SbCDfbNZPaMrbL2+MyBMomjP99O3wWZCB+mHnIv/mO+KbLleu+9mzq1A61jcZ8rhkpuE+Wp9b6mEwchB4yoX83E/DhplzHdEqpKzs+ebHNp0T9d6SPhvhICXQDkuzBYcVKf3yLaqEz4c0y2uxYVPhMQELnan5Wa9qoM0biruMQ7C5E3gXl/5lRmZcxT1SjwSGe7P0MABJEenxpuKVsdTUji6AxiKWV3vXqhTnqM/alKesrgIWBDR0lR1OnDOoUvM4eTkH60vXzrwrzX6E9SD9ZWfKnGypQGkTL9kDvIXLyTmeHqg9PASRKrijUqkkqQbroiGFPVgZDAKIIoIBAIEBBFkAJKAAUQYAIBAAMAAZAAAAAAAFAAAAHXN0cmVhbWxpbmUtcGx1bXAtY29sb3ItMDEuc3ZnAAAAHXN0cmVhbWxpbmUtcGx1bXAtY29sb3ItMDIuc3ZnAAAAHXN0cmVhbWxpbmUtcGx1bXAtY29sb3ItMDMuc3ZnAAAAHXN0cmVhbWxpbmUtcGx1bXAtY29sb3ItMDQuc3ZnAAAAHXN0cmVhbWxpbmUtcGx1bXAtY29sb3ItMDUuc3Zn/////wAAAAMAAAF3ARgiETQMQ5Ix40QIgAZBUiBhCEYmgRgRkqZpSShikUYKAAeCy5BBnMIJQRRmyCIFkqBAYbRlADZJCiBqiwgi4qSE2TJhYEIkiBhiELchE8lJIEUhiwAk5DgBEjlkAoAs07JJgbaMGjJhTAiAJEkAFLGIIQNKiUQJ2JhoUDIRDEAGojSJI5dxAqGMogCNADCRyQYqWcQx0LiRCzVy44BklMRoiEYpICVp3MCFTERRzEYNzDgCkxRB0MAsHEYII5VAEaNxi8IsQCKKDKBIzBIEAjVuEiFqw5BoozCRWLZBYsRE4iguAKkp3LKNyYZwEQYsBAKOILINBJAxJKkQWUJsCZdJoxQAgZBJkyKCDDBgUwgmIRWEUxBtIocA4BJAnKglFCEkCZVx0rgMSxIygDIFwcgRhDZCW5YRIhlFJAQh0rBhTICJZBZow4KEwbglIRFgAsAgCshsnCKGETEAkTQSjIIQkghNycYs2iiBTAIIAwRhBKdNmjBwAAAAAA==";

const chunks = {
  "streamline-plump-color-01.svg": new URL("./streamline-plump-color-01.svg", import.meta.url).href,
  "streamline-plump-color-02.svg": new URL("./streamline-plump-color-02.svg", import.meta.url).href,
  "streamline-plump-color-03.svg": new URL("./streamline-plump-color-03.svg", import.meta.url).href,
  "streamline-plump-color-04.svg": new URL("./streamline-plump-color-04.svg", import.meta.url).href,
  "streamline-plump-color-05.svg": new URL("./streamline-plump-color-05.svg", import.meta.url).href
};

register('streamline-plump-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
