
import { register } from '../core.js';

const lookup = "AAAFTokZA+gYyBovwweyWGS0RkVGVEZSMWJyuGRYNUVldVRVd3V3RFNyiHiHVTVBhjV2UmaDc3OTZSRFZXRDUiNlOCQ1NUtzdTk1JkNEJHJWUkQ2lCt2dkhSRCWHQod4GiOmRTJVclh1ZJhUI3QQIYgyUmhlWNMClg5DBSMnHgEBAwwCCwh3nwKqaQtc/QUrFwYCERATBDkHD1gORikRCAMWCwUUAYACrwGeBfAGmAHSBPQCKgkSCyzTCmMCVpYCAX4riwEILwIwAqECDx1BATUVDbICBwMBAzALqgEIIgQNAh0H0lgBAgMJY+QGAjMBDwwIAgHBB4ABDgQCCgnTAQQD0gLkZwHVAdUDKocCiQYMKAQJBgNxTQ+kAfUD/gKSAZ8OAgIF4CoeCQQcB2i1BiwQ0wIKGuUPuwwFCgEExAIB+AMfAwtuElMjAlkD6OX3A9IJx8gtbMqFiDpWz11L+4F1pmw01D5PlWEazyMCe+2fa4N5glAAEAv09wWAF+LrnTlbKcMR0FdfQJe6+nvu8nt5ZtzVrATDQB3tJoJDT3hpCxd3kFU6EmuXu6klh67YG3D7RSnvkqt7sTMWbndPb1qPYDBghWXS9gIu1IcgDwyEAeQSFKhCc4apBxsSaTeogsp6QQVbBsHMqvwJZDigJGlwC+bX9ZnSMj1WUoTh6dDMDMf8ygjGpIcsqqrG4VwSx2NO2Tg04jFGcJ3jgdc+AcLTOx3/aGxLL3Jh3hgWxwv2QWyRKrjBjKnp2x4ht3wALJxaik6KqLcOdumvs6wbXNFj04JJJEPEHXrl0Dq+nrGR1gZPNaIBUtRLEG+7I4zWT0HdXTs5ItgbeM54SQWZazZ8DhaiglH/coY2lyfxVDe4EVZpDvC/jM/MIZSxOSu124wDLVmrMSAdUEHaCNwFqhOFvJhNvvSKSc+UBcpDxLhGV/aqTanOS1EL59w0qJIEuFGLgEhw8uZscnZY8Q9D5KDcp3LhsM1UuC0d1z/HMHusNapqUKw+e/ZqfPEXjzkQT+MzfwEquax1fpfX1z2F/IaOTxce3bcvKDlVCUZ3rXHrT1YEcmWaLjTHSVTApzIotzD8KrIKz1adbJYG7cnzrmUlTpa8Q0PrMeXnu+uwqFxs4PeLYTnN6QXNwXqOy42FMHtO3x/0LiIhp+LxNGD9huaoIDZhHYo3zjRPJRXzItoVCqwgkD01VVNYtZY59RNL0JAhuZykqrPsW+AS/i1Nmom+olywN+PDMIibE/LIZ7Xex4L7S1TYgDZ8lJfNFUwTlVy6UldSca5P++pwFvCATLAO8z6babkuz8oKhGevlCTWWbsbV09NRC0EA3RJee7z5Zg93wH2ZhYjGbbo7qcWxoD11d6GzbMuoeub1fFisMc501mqicZZV6mSVErijoX+XL+s3Yz6ko/y9aH61LzaxFkhyVHrTA6c8lPDX3ot9pyoaeZMo4jFU+n8kI4kJdiYW+JcuEP1xnCZfKqxuZH/O7x83gQDK27qQJnB+UBN2ZXLDWVVKVD9WxTE3D3l2LZZ0OZoc/x7ZJyWLC07mqy8N7cIzBefXlugkKiFKBDLOBqzGzSUB1muC3/3cy/qcMrXsQCH80aRxRSDniLPTmZyB369E987FKRzcC0r+bPhrPyYsIW6oPx16X4w2KZtJGVBg/lth0j+xDlBwec/qqwqr3p4jGegN70czTk8j02DGQfz/UhbH9m3Ob1YDo+40j75brzC/dxYX1qyJWF4GVK9xXRhKrQTHRRx4ib5ssmlzdom1SDVAPpYGQBYBQAAIAAYIAEMFAAALBAAAAGBQASAHAUAAAAABQAAAB1zdHJlYW1saW5lLXBsdW1wLWNvbG9yLTAxLnN2ZwAAAB1zdHJlYW1saW5lLXBsdW1wLWNvbG9yLTAyLnN2ZwAAAB1zdHJlYW1saW5lLXBsdW1wLWNvbG9yLTAzLnN2ZwAAAB1zdHJlYW1saW5lLXBsdW1wLWNvbG9yLTA0LnN2ZwAAAB1zdHJlYW1saW5lLXBsdW1wLWNvbG9yLTA1LnN2Z/////8AAAADAAABd4OGkSRDhhQTbNMijUsGIgpACpKGMJyCcdQQbQwVCktCBYumZQNIUWECUCMxjRwiDVIygJw0bAM1SVPChYkmYqQILQCmEcIQEsiIMAxAKMmmScrIYEAUTsoikcSgKANBhUmIQIkUiQC1aZHAJOCGTAzFZFIwDKFARohASso4YoyEIFs4YZqQCEKycRIEaiOHgeIogAA3CJokiBkGiGDGcWQibhsgiNk4YEiyCQEZLZkGTAQTDWIoDhEDaQuRgdCIbJCmMUEkcRmXJSHEKRgkEtxCEksQZhTFQAmDSBElUFtGgFA0kmIwUQzBBEomTYQ2JBQmJhO1bBoXTgmRBRs1JhhAiFoAIQo0ZAQWIhuxZJwiJhhAaAoFQVAAiNQiDJjIMQAWUYEQglCWJBM4ROLIbcOmLYmkKWKkgaOgAAKhDBojIkwiJBkDioQ4hMQ0iJkmBCCyMEO0jQRHYQFBCgvDKGREjiAnARkZMAAYZAAGbJgmKBAnQgEyKAAAAAA=";

const chunks = {
  "streamline-plump-color-01.svg": new URL("./streamline-plump-color-01.svg", import.meta.url).href,
  "streamline-plump-color-02.svg": new URL("./streamline-plump-color-02.svg", import.meta.url).href,
  "streamline-plump-color-03.svg": new URL("./streamline-plump-color-03.svg", import.meta.url).href,
  "streamline-plump-color-04.svg": new URL("./streamline-plump-color-04.svg", import.meta.url).href,
  "streamline-plump-color-05.svg": new URL("./streamline-plump-color-05.svg", import.meta.url).href
};

register('streamline-plump-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
