
import { register } from '../core.js';

const lookup = "AAAFT4kZA+gYyBpL+t30WGQoZGQ1ZUc4Q2dXdYXDNzNmEWU1eEM0hKZWRCdXSDVoEmRVZkclVlU3VWhxNVY2saGUdFQ4lTSjY1VHZ6NDUicjKmeFQmczc1hGY0ZDYyKiRjeTUkZlUkMndjU2NVI7hFNxVThGWNT9AwECGAEJAwEDD4kBGKEDAQEFwwIjyAEGJrMCMeMDCspYcgUUNCVEIgyGBAQGCQQIHdMBOoQQFAgLD40EAxPLBQ8VAZUEXwkXDy4p1gIECCMLChKLAgQ0C9oCC2MQXTMXAuktlyULlgEPEwEQ5AUCH/UDBQXjWQcvIx1DAgckBfICBAcdrwELtQJjTsYGBykFDALDBNYCLrIBBgdHEAEJBAFkAwKhMTEJMALQCRCDARQGPxgDAxYBH6cDHQRgAjUFAoUBvUQI7wQFDeoBDgjcBwwIBwJZA+g5BW2Mb7J+IF0XrA2GjrQruGx7/ASqRPktUOObOSPVUobY3ht8/SrVwyUYrJ0IQGk6Nyrpo1twH7yeSTtB3RY9uFmJJHH0G2jiL4AZgzeE507Q3hQi64KVRmGqx4DrAZc3Wf16DjT6j840mWzzqC0Lt23HoPvxeY+7QE8FS0AbCbIa0x0AraruXPaXXPSo1jBD3BY5ylplN0x2Jtftn3CUw5xOQJCPC8cWugDy6YKYPumAORKM5qzFwWx5sKawwZ7Uzem9qBEvVFSOZyqcQxNwLbuuKozv2T5DY2zrFJ0EHd3y12lz7jLZjgv1hvt3HVAt0qzYe7fVMhe66/cuAztPoq92Kd9IftYA8+Wu880dljW2d+S52AVe2muL/tV734VyFBB6uD7iV2X5+k6gdEPPaaLnoO6SZlJZQZJ3JMRWMfEbGfM2dU1gQ/9YX409ZCibnFQIXKzokak49Qc4X9QtrzCwVWzD4JBTCXD84ajezaT+ddM5f99rXzl7mJdDsQNZ62HCQyWREy8BIzp7x0LgqTBgqf/n15Ets0w+TqrEOOJWEiwLUIqC/CEH6TbPrFaaXHIUyc3VJTu8OT6Qijm4mD1NsLkzxvrKLfLOv/3wolBBhlf7B4hx+yQr0tFXVTQ0NE+Dg69JvayYIngp04eCPWQFEW/j/PZ/CyJ81+oStYcfcqVL0PZP28+VHjxUEh4hUUFMuHPHwXzc2jBJJldSYlinLrP+lAOq4ZTLNXs2RU28IQHQhG5LtQT9T1eCszpwCOVGIGaU1DYopBZbP3q8vbcKn1vqDsWAx/waWfVcacaseGCkG3yU2Kd8qM+zzlZ0SGtxYb65TVEdmbvxQfNwkCbG8lsXqvlZSCX8zGw9qxub7CQghQ6gS4UzLnoocIlayrmsAvbmysumhjAuqKoTbvTS2oDZNTvIeAOB3Jnmvs94BnO3xuMgO+JVOcC4viphyMGF4VRjs0uWD5YKl0lGfL2nDxYLUgFOZmHlbs/iKXJh0NiaDu2qc/fc9QcQx7otsFtyNIdKMRC34r+rJ4XmU3JNVntPeLztOVu7XE/laXUlBpHCVZIEeklPlRDhtoici9Yi9gIUFqBsABMjp7hMFRXXLPmP82gFy6zMzJkZUZZb8FpGxPdnUQbxF0HF2B3EqJJT1HBcgmoK9gEMx+s3ylmI/IWaDoRltWpYnROFZbFdsU80WP+HkK6Pg2k3gQUujIzD/NKxsWdPecbkzdCFxJeofsmc2w7dK8Eht+Yh5RwEFaG8ivHc1zEsIPLpZbIwCRLN2ofN3LD3DB1NUk/5EySpjD+KqqqpyvXP6qGO+jneF0uuyXvMWBkAAAAYAwCAwAECkFAACACkUhAABBQEAAgBAAAAAAUAAAAdc3RyZWFtbGluZS1wbHVtcC1jb2xvci0wMS5zdmcAAAAdc3RyZWFtbGluZS1wbHVtcC1jb2xvci0wMi5zdmcAAAAdc3RyZWFtbGluZS1wbHVtcC1jb2xvci0wMy5zdmcAAAAdc3RyZWFtbGluZS1wbHVtcC1jb2xvci0wNC5zdmcAAAAdc3RyZWFtbGluZS1wbHVtcC1jb2xvci0wNS5zdmf/////AAAAAwAAAXfLlAVBqEHSxEQhskWIuG0gRkDaNDFkRIIKqFACQY5RQG0gmSXbOAEMIwxhNHHhxmDYpnAIJJKRECrakIikEgyLGCQARowjMAITgECghA1TGIGiRCYAIirTICHKtkAbGE0bAkxgxiBKBgjSho0EJ3AEEWEjJFAQxGDElinglImTEIGUQIgCAY0UAiTYEHDYNCIUR1ALyFHLBoyiloQUFIbUQAbYhiAKSGrYEjBkFmTbJmZUmEXIhEDAskmLQBDBCIUAFWBKxEXjxE2YFEgjEDIMx1AapCAktGQAx0iMJgokgHFSFIAjlmgQFo2DOC6JEoFhBHJRBC4ZM4WcJC5SEEJIJErEEm0MNHKIBkGaOIGgoFEIAEYglShBNoUgMySThEGctCUTxUybGCkSki3ZmAXKGFASGQJIEgEhhk0bKUGTAGXcAlCRoAhbIogcCC5MpJAhR2gBmZAJshEhspDbOEmgGIEEOEgZBpIEgiXAtAGcomQjEiTLSDAAAAAA";

const chunks = {
  "streamline-plump-color-01.svg": new URL("./streamline-plump-color-01.svg", import.meta.url).href,
  "streamline-plump-color-02.svg": new URL("./streamline-plump-color-02.svg", import.meta.url).href,
  "streamline-plump-color-03.svg": new URL("./streamline-plump-color-03.svg", import.meta.url).href,
  "streamline-plump-color-04.svg": new URL("./streamline-plump-color-04.svg", import.meta.url).href,
  "streamline-plump-color-05.svg": new URL("./streamline-plump-color-05.svg", import.meta.url).href
};

register('streamline-plump-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
