
import { register } from '../core.js';

const lookup = "AAABmokZASoYPBqLXWYFWB5WY2VENVK2ZVVoUoRCdTV2mWMkRFZSY0OGI1hUFlZYNV0RHjAdBQFxAQg7DQQLDBwOAQsHBDtYHgMRC5EBVwM4AQsDRiMPIQUVHNgKAYgFARITSSYRAlkBKlrNSB4IexTqpQV9m6weViABK7IOMdWBljhWhPfnbKJ9xQPpBEFO88wbI16dYHLfc1g5dhDwB1xjFWyGnwEHtm9g6LuBEbe5y1GVlcI+rC9QUZ1fF9clHEFTx2G4EfH3i8uhFoKJOAdEmHGP6Sw6PCpKOteRoBFAvbZjQyq+111nZPLX83Dza1hC3A1+Hu5t82B/alQUHP/j9Qt6oH/L6Lkz8HstZn/AUL8Nva3v+KP7pP7Sh1xr73G+i0eVUxvynqmIjwmXTclx5v1+QhUkEZ2DSO+HVfyRgPY1yZubeypjp+SLzs15JI4upZF4EdmsmaOXgml4b9k87Iwm6VkPMOU1HteG5lVYo3nGS52TvTuOwuSftpoZuI2Dxsj2ykHTiasR3IEYrVuHnb1IBERAASAUCAIAAAAAAgAAAAp1aW0tMDEuc3ZnAAAACnVpbS0wMi5zdmf/////AAAAAgAAAEtQEBAEAAUQEBEABFEAQBBUAAFBQUBAEEFUAEAUAEAAVBRAUAEBBBQQABFFUQVQABAFBBABAFAARQABQBAARUQBBAABQBFEAEARVAUAAAAA";

const chunks = {
  "uim-01.svg": new URL("./uim-01.svg", import.meta.url).href,
  "uim-02.svg": new URL("./uim-02.svg", import.meta.url).href
};

register('uim', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
