
import { register } from '../core.js';

const lookup = "AAAFT4kZA+gYyBqPyOfPWGRkZDRiIpU0WEYog2V1Emg0V3ZoFzM3hUJENWNTJTFWNSYoNFOpQjc2olWHkoh1pVFINzdoFGRkd3Y2NSaWp2dGVWd1d2VTdkmjRpJUUTIUQ0FYVwNXNEgGRCdUdCpSREV0lGRpWNQhVQxGMgGfAQEr/QIMkAEHHwONBAOjCAXSAQcwAvwDWQUDmwMDKlBJGIwBAgZZIJ0BBQcGAwICwAIbXgMB7AEHGgINCwYHAQm9CNkDAglDEHgCAuQKAQabAdcGAeUDSmYdlQEIYggdBqoCAh0JJ0gQEmgFdjkKGj2LAgIjAgtoywE2twsRuQEDAz0PTa8BAyXaAdMBCQ9IAagB8AsCqCCZAgG+AgMMAgQKAijhARygAQMCJAkIAfYDAQ4CKwQRCEDfLAEBKQMDBhYS4QUS9gMJaqACZAJZA+jU61POSTS/N67xFCOhXjgk331fxuP8Z1gJZjemPqmtBWiDABEHWTqiTzCf5iegiVrOgKalfbVEVtvdyVre93GHcgNRwyBmk6Bdqh2UsvJZGPTVTOYd5abrqKaM0BybkPyG1p6/MVrgN0roIEvhP7x0k5veowcVUWBmFHdGk8eXv47dtWZ7tmEQo7DQDbm9Grv5oLSdiNaxfisVULzMozTQR3a4LEOsn27b+0rERJ/1NNB7tGoYK8OqrKJ5W29TdnO/pWbmeKMBPYC2g7N4Xo7V+w9LOMfog5udAu6yPz2FX9e8TQ3U/pT1TF+UvV4Us7mG7o6sujihBaep+7nL8q+okiM0UpLqwfuEvhmAdtR9LM1V48xNwZTQhxOqwljS0kSvlsYGWn1M1b4Qf4Ol7VDfQa4t8OUcoGnls7lzKuPAkMhQHp9sCdqZiSY2EVUVbTbjJh9oiqxPbun00J6h/9FHcm77Zz2BKeQ8ePmbL7fz+c5sMbmjCXz2JGKJsu6Vb3gVien7FhpGnJ/WqUOM1Czzshq2ffV2NnqAyi0CN7q85I097c1A3GwotB3qWJAchkxmHIHL76CLcgKJEnEfEh0RT/TsCu2VMvvm7FoDp/ffPAYX3vldPSlsE03tGbiJ+vpi4VgB+dwtqyUswAENo8rDcg3bPSZSo1YjqY4KkMKsVIfnLaCOYISg/zvic5ueozA6gNP6h9TfpJJ9Yu2+e62MwPQHLoNCWjbUdK2N0Auj47yFayXEsfgjhlYD3X7xFl3TrJcOSpH0AOeJL48RMuXxrVPKEi/A9ryME6n1fn5tR7LRTSHBXoXmkkuL5+ga9boBTVSKhzAy7IjvGkuQtgYK+3qHCD0StNVZzF2Kk6vA5W7zPDv4z5LVXCcV6X+L9X7t3GYHhiWPDAbU7hpRg4zA+VJDvCjVrfCKpbS+SP0G8m18oGnEhNTYkLBXv8kLrRQ7hOotGNVc/8e/XC7J/X96YPjHpJxHaRtW6msDhYmXGP5Qy2lWrNAeiJQYzT4YuoR4DPQJB8gzlcepF2qJD+YuJSdtvyjoSBX7mnMEp6VLRPL8D25Z1f28Ba6SoDnKe62NKeX4Og5DOSxAYvSHoaArFC0frxv0njxfPaeLIMrVDOH1tNo3gDxv0uv/4cCY7VdRyPe3I949RTtvfZXNa+1w8eWeh3nydTIIAk4eICJq4e8T6eNdnq/fZ6ibWsXZ5wy3XSuEtp7uTuTH36e8dEK7fvIFLu89ormXtvAZIoBG7tfBeWQz4wNvOqbgt4nYkawyRYyU/fxd/lnZm+bNtOswMZX3GY+EZFUuKIlll7NNPUniwV+SsZFbWBlAIggIgEhABAoAAEAAAoAAAARRJYGACQAAAAAAAAUAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wMS5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wMi5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wMy5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wNC5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wNS5zdmf/////AAAAAwAAAXcZJA1BFExbAikAwgBJGI0IEIEalWFaCIxDJijKhHALomzLQoBhtoiItowEQg0ghUDkyIkkEipbEAojEUZZAEgRtCTEBmJaoBHJBg1akgXSRICaAoZRNpHgQEEgMTETI0EUB25DNGLCRm0UhkgEBQohJmTAEmqaomhUFkrZkmVkRJKDpA0UwSwIk2AJQWBRIjACBwDgMjHUGIWQNmLbKAnMlgwQCECKJDGTQDEBsCXSFJBgsE3ksARhmCSjJArAFEiLyCmgMJHcQmEAKXHARk0bR5AYokRENoQbB43SyDAiKEALRWEhQSgJOSkklXBMEIWDAkKjACXUJoEgtykERIojJizKFgAIOWkMAQSSIlHQKCDbAg0BsFCCtjEYQxBKNhLLSAoIoQhQpCmZMjJaMoETsoxionBkBi2SIFHMtAjYQhAkM4YBJ5CKoC3EmIUTmZFcQGIZA0QJiQkhMSgIFI0LJoSTBAlTpEzhkGFERgxghCmIuE3hBgAAAAAA";

const chunks = {
  "streamline-freehand-01.svg": new URL("./streamline-freehand-01.svg", import.meta.url).href,
  "streamline-freehand-02.svg": new URL("./streamline-freehand-02.svg", import.meta.url).href,
  "streamline-freehand-03.svg": new URL("./streamline-freehand-03.svg", import.meta.url).href,
  "streamline-freehand-04.svg": new URL("./streamline-freehand-04.svg", import.meta.url).href,
  "streamline-freehand-05.svg": new URL("./streamline-freehand-05.svg", import.meta.url).href
};

register('streamline-freehand', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
