
import { register } from '../core.js';

const lookup = "AAAFR4kZA+gYyBphXwCwWGQCV1UmSjU1VnZ3NGJ1ZJdUEjZVZXhTZnVyl1NTWCJHRWUCd0GlRnJIVVd1aUR2hWuIVSeXVmh1KWdkNmRUFEUlZSFTRTVUUWRmNkWEREQyR1QzhqYiYisqVbdmJSpWMSMxUlWDWMwIIQcTnwEBtQoDQxcjVgOGAbUDDQG8AQOHAgcCqgKMAwM7AQI8BX+/CMABAmk5aRF9PSDiDwUIV/AGKwIB+QIFEiAIHAKxA58BGiDMHkEJYL4BEgIOhgEgIaIEc30DDFItO+AGjQpz4AFPHw9mAni7CiYmzARREGOMCFqDAQGyAocBAQGFAQMzDgoWBRUiEBkNEQgPPxEHCBQZAgEDqwYDBAcCBXUCFw8EXqcByQGoCgEy90ynCRofEdoHMGMLAYgmAXMIBQJQGAIBwAECWQPoOK+g3xO8rRJHvE1f40OcEkf0l+Hozea0pTyH1Ls65cIfi+E9h7829xM0wKduhnRdkSAnl4nUc4ybtD3Nf2apdSVGPeA7yp9J9K8PaxRuoy4a6KVwfpt7lNCA0dXrikuSg4kXo9u8iobhHhT7qV9WekfVUsFmGQaBLYMftxBSDSZpFCxvx5JR7fvv/3m/vp0JsjLmSzti38TtOM6hEJQCmmAmbJdq0f21n9RM6BIK32YsVNVWoFCftsNnup+RGT89aIBJGAxWb5sno3RmetzAzEOWPdTy0C2H1gdmWa1pJ0Pj1wB45o4F7vT1UPUydlpuM9YcGrl7XjbH1fddocfJfTe8SLS3duM6WMQt9iN0MnOULF0xvsPPBgEx+8aANtIJqAiHYAPs9XLBwKDd+u60NKyojquHTSuyro0OsXqVYNuEi7EPBfjpidVoxJ6n+9PpgC5tOp4dZPi5wW+nczeJDaaP9vMc0CmpX/Vu9YymnpuVA45tXNCsPcuJiy3f5GzmT8dZIx7H2KNEIOsdM43sVUrDfqnmg3t3jJP5kH8D4+rzUTL6jpswmDgRjodEh/uQy6L+VmJL+JTyrFhN2UaglbkVibrrs1kaCVmslALn+6wvt5475Shi7RoPv7lZLkqiirtAPP8NHCO8ql3Uq69Q3t/xWqoU9YNanP8X8j33AkJh3vEb67O6N4CIG+f9LOAdX+mv7XHJgVrdyrTUiobVDJk2/kSyR71SUEWSXfEY4urOQhOUFI9+eRaPEeS8ktbs/woV+bYFKwGjmwd8dqA/HLLqhAB9W4CJQd/eiKAZaryX/VMDtlOxlbdr0LrwEbBFf36gxpLuPAHNiWwuTFulV1y8kMAGpgY5hoVPytmsEk8kv+W2zhHBl4t44z3yrH0354zhpYYVMK7mv3GJeZJvJVMFSwmEqWzM3K6Eod59WAPt8jF+NAYZ+tqV5BiiLSOeo1bjwSrCo8C2boUehHgHyPROKF7aaf2toDCI0OLK0J89+134OoxlPlovFdNiyM35rQT5o03u1H6/aTz8zS1Dmxoo1T5m7ulM4znlGBjo5YWz7ZOQs6jxv/ROre+wXu6y5vv5MGY914nLptzK8N0H/gee9F08h1XnoNKkIL2hkJNtwO8KfZDwqSzvzLm+nvXIhIm1MkSAcrQvGq2nbRW5+1EBSijtDYRkHXNeIiEC7bhGJnLlVC5VCCVI9BN4WGc7UfnzDPx44dTFDm+RIlfH2/yl0ksWrVp8gynl6iDyaiX0tnv31X1A1fynXLTYX0xyZ6CsI6q8TYxrfY2+NKaFpBiTgx+STbjQKwsrnVo3o3bJDAskKcA9FVgZAypAAEYAQQBIEAAAAIAAiBwSIBAEpgDQAwAAAAAFAAAAGnN0cmVhbWxpbmUtZnJlZWhhbmQtMDEuc3ZnAAAAGnN0cmVhbWxpbmUtZnJlZWhhbmQtMDIuc3ZnAAAAGnN0cmVhbWxpbmUtZnJlZWhhbmQtMDMuc3ZnAAAAGnN0cmVhbWxpbmUtZnJlZWhhbmQtMDQuc3ZnAAAAGnN0cmVhbWxpbmUtZnJlZWhhbmQtMDUuc3Zn/////wAAAAMAAAF3ojaJATmCGTdlEpVhIrmFSSZSWzZqGwQsgbQoQxQGQgIwEkkEg5QRDJmNEAcMQsZQEBKGYiQB4UhGU0RtWcBpECKOFMBh06IEghgwEgCIgRJKzIYRGIMNSkiSIJVRxEAC0CiJ06YlHEFI3LiFC6aJSjZSEEGSWAJAg4QECrhtApUoEgZsFEBSibQJAgMCzLhwAEWA0qQJSJCI47ZxGhOGI7lMHMRpUgaBjLhpGCdxyRQEyUJhiMJEiCYIJKcBGzVIAjRwiwiGHDYFDKZA2pJxJBhpEiAwYDIQALdw5DBB4SIgwDSBE7AB2YKIWwKRjAaEW6Bk3AKJiiCSSjiNWTQhkRQoxEgmkQIuCUFNwkJhJCYkiYARgBaGJEFpTLBx2SZOyBhRycYsSghSXIYlI5BhIkEIioJEipBR4gImIwQFQYQgzBSJ0AIMAgFBApJIA4RxocJkFAQAYbggGDBNpBAuJJENEwJSGhJiCQRwiBBtURQmwRRygbKJAAAAAA==";

const chunks = {
  "streamline-freehand-01.svg": new URL("./streamline-freehand-01.svg", import.meta.url).href,
  "streamline-freehand-02.svg": new URL("./streamline-freehand-02.svg", import.meta.url).href,
  "streamline-freehand-03.svg": new URL("./streamline-freehand-03.svg", import.meta.url).href,
  "streamline-freehand-04.svg": new URL("./streamline-freehand-04.svg", import.meta.url).href,
  "streamline-freehand-05.svg": new URL("./streamline-freehand-05.svg", import.meta.url).href
};

register('streamline-freehand', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
