
import { register } from '../core.js';

const lookup = "AAAFTIkZA+gYyBrID7qJWGREhaJ0clZHgjNCQ0NENGQzsEVVVzeHQyV5cTIyQUXHd0MVVFdWckpHZiU0M3VDVENTVkJWZ4JVQ0UIV5uCJ3dEOmSESUlmZ1WUaaREdnQkU5YxmAMkeEhmI1JnZUozlzVSUWZlWNEp7gGVKRWcAgH5AQYFqAILzwkCAgwDCxAiCwEfAwStVjsCHQkjEQkDb90FBA8eAYgDhQExCAEDBhOaArM8GFICDRENLqQBEjsRC6QLBkd/RgsLCAMMrgEgAQMGFgEBHQkDAgIoDQQoAbgDOx4CDSG/ASca6yqdBhybAQG6ARsKCLAOBBotB6YH5yAJ/wsGJwzuAdUBCBcL6gShAhwBvgoEabIBCSAODzPOArESAWcVBwNtlQSMARYxFQOWARMZBhvdAhQGAZEBswQKAhYjNhXRAQJZA+igrSOzCYNCbG42brd2PXJ+N0kmoHKLsYBHG5XJCdDwIq/Ve46KDNCFkmoynjTaiSsgwzpst/J2JjNNWOpGWXjsSNXuTfGDA4rUspympvLV0KJaV4MrXUKMqxXx5oCykk7KMloDwKn3iO/ca9DWjrawbTQAJyOLGtcftcGjuW1aLHyhS6utc2gNprxQiQZrE9TJ7RI9+Q1SlOntk+cy4ym/iqJ/vNqGMdFGWEMV4edWclL+NzMW+OSw7xuf/BP7WaACZw/jL6qeyCbkwMLm+8DNx32F9fOSm6r6MAUG+9vBXXsuqMCJ9OF5zy2jftvln52+t8oYCoXQ7tmQZNVmZiuOso/p0BqsifyXzYlEf1F7ViqgCPRYpSEDGINsqk30VG6s+UDl9aB7w5SQd4mNJbSpN6b7abX5/VT79DdOjdI/vm0MF466u60HjUOAH94NiYigmZUg5bTT9Ost8bwgdZA/NK3Xvz2EVgql3cCGGm2nEF0+PDe5kHEH1EvfHvmE9ucxsn0FKNMcYKObhIDwWgRq7t4DCReHAfuHBcR2lCkRr6/irL6bE7+Il4xZXvjIb71nqYyg9VEYDqVZ33Pu4j2X7Rk4RO991BJNlcb/p13IieVnSgiQzb8BfrNevAwyAfc540eR5kwoGovARhrbS3J5PdSX7dKhlMEdLKMjYVq0rUyK33HqrdW6JUT71ebNlFo4kzaE95tm+ueGEHoUg85R9DJ0L/0jt5/erdB+KP31/6eoaYz8Vf2/DLzl5g+MVZCuHF0BBs66PV0HYnaRTdGzVU+imMBdbnj5429TO1B63BK0gfOAo5U5BdUthlxfPgs9Jb8cAq/M0psuJMTrcMceb/vWtAsYLcXJ9/PtvE9kwd8w5sIiyh5ehys9x/q2LKMs7raV66xAHEW5X2Y8dPlqmmb07awsrP9LX+FXCeyStvi4Uz2sHadQeInjzPWjvGl5NPAUjOjLACQwPWymfWhe1vLU2EQCept+aby7RzZboxaSfVxKLV/s9eMlnzbyuf4NyztgH4dcOy0Znu4Rur+sGtCP/u0xykPHjqDtvvGJqW8YrpOED5fkw7SbxxgVKehm+zs6g/JaA6hIbmWRlEyg6n3f4UoU6KRWnpJ+YOnU9qmPPYTjFRkV64CWOKM6GS5iYs1Bs0P8TToRywZ0X8SltqmefUWHB8pbgZ/eCt1Paycdnfg8UunotHxzPLE8iXOnrse9L9+kHYBH2ZKgueUgnkny4C5iBwIS3cYouc4u5VPcnOGhMJNWoRF/TNil/xRRUFgVnoaHtouEWbjU9BNvJ8zvh2YUI9UGS7HVeLIOvMHm4Id4her1WBkVQFEQAQAUCQiECEAAAAoBAACAIMQABoAMAAAAAAUAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wMS5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wMi5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wMy5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wNC5zdmcAAAAac3RyZWFtbGluZS1mcmVlaGFuZC0wNS5zdmf/////AAAAAwAAAXchxihMMiiINkIRA0UAB3FYJImLInFiBmYKGEwipokjEWkih4BhkiTBRopJqCGaKGDhACXRMmEAsWwMFDAgFoLZlojEEEVQpGxCmIVckEFgJAQBQk2TEDBSmEgMgkmAAIzBEmkbMAHKtEAas1GSImobtyQIuUkTMQEMs3DKNE4QRGwbmCThNEyZooyhGEnjMI4DlhGCgAUEIGIJpIXQsomcEIDBmGQcIHLMxEUBOVIREoYYBA7TBkiYpCwkFoUkpQziBoqJGIKiNG4hwSTjFA0QBnDbtmgcpCUQKFEhBy7AGGokqTACMmIAAQ7kMoSMtDAQqQUiCErhtpCkppDkNJDMAIrjBjDgRAQJgEHBNiIispCJRGhMsgHAgkGAAFEKsFEjFm4axUyjFgahKESitDBYAHEIxwAbKSILAWEklRFjhogEFAKMAJKLhEjjSEbIQA4RsGREIgoLsSEKIEWTMlFcAkHTmADiAEEjpG0CJyRiAElakASLBDEAAAAA";

const chunks = {
  "streamline-freehand-01.svg": new URL("./streamline-freehand-01.svg", import.meta.url).href,
  "streamline-freehand-02.svg": new URL("./streamline-freehand-02.svg", import.meta.url).href,
  "streamline-freehand-03.svg": new URL("./streamline-freehand-03.svg", import.meta.url).href,
  "streamline-freehand-04.svg": new URL("./streamline-freehand-04.svg", import.meta.url).href,
  "streamline-freehand-05.svg": new URL("./streamline-freehand-05.svg", import.meta.url).href
};

register('streamline-freehand', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
