
import { register } from '../core.js';

const lookup = "AAADJ4kZAk4YdhpuN115WDtUhFY1UylWYmZVN0RmNkQ2klRFlEijWTRWJVZEM2lEcylFRRaUVgZUgZR2NmNWJZdFmCgiNCM0pWZUWFh6EwQLrAIQBhQECA/JAloEAVIePxktGQELCEebAUUGDgeFAQbnCVEFAwvFBFYKBrALhgMEFQMdBT4BEAMFAbAaBRwIogHRAgELBgISuxNxAQoEKmGLD2yCAQEBIxkWBgGaAvcEC+wDyxSjBAEJAwwTAgSXBjNxOwPRBQwCWQJO/tFZ0nLCofnSeJBhszM9542RSePyq+7VIrF71XcqwkbT7TolwzDRQsuJpwnb4Cz5QZ9hg4jRqFfutv556OYziV2LmPoGX8RQwScDiyfnHxhUqkAdZqXhAo1JPYhn7Bmo+hYt6LsZ8yNw/uJNeebyAtzfHzoyyhGM1vw9VQLTU8jBD7EjEtOxf5uci6Td9DEK1Qg7lATYkBFP6vlV6WkafudmJqXohDPdU0is+TGWD/QCrOGvekSJiNiluX2TsNYsH40RyAHS1m6Wjx0bIKmqUuwmXHPm6RAWhMi5uFj1H0/vv1IB2eeF+FXEo52fFV19RZDoU2BlAVuvHMj978Byw7W8cOEYnOSkMn8LAZ8LBf2FbpRDwDptoflirNfadgPbOBaC5mTQFPXpu//DPWTkkGkfC45n/rsJvzujq1GwWZUktbau6sG+nRmRppQcYSI/gxyhWyE2ts92b6FF3bNIT4faPDwie10udylbtJ5q1wqk1TcawLOOhv7YKAtMp3TaiWwz165FnRVoQigsgpU/lv45noxnNu63KWQZmevxx8wv1aSM/72TkIErs+k8Qs40Bn7xagUlaUswXZToK82L1nqAhWSV6xydEvidlFfEHtX82zkFuUfIpvnzDcvRo9PtXSClWIOa9LYtGbengNTUQw+bQrykSv3bZfSVeTQTcKTWT12KXG4dfG5CL7teo9ZvcUrBXohQJtyYG7+wQkGSMxz3xWKAKNa+4T/EpZYzpxJH4T31+EdoIoSyBnQNCDE/UlbZfhhP6nmBL4u4JJNPAAgAAAUAgEGIIQUBoQgAAAAAAAMAAAAPbWFya2V0ZXEtMDEuc3ZnAAAAD21hcmtldGVxLTAyLnN2ZwAAAA9tYXJrZXRlcS0wMy5zdmf/////AAAAAgAAAJSFYBqIWIURAVUgSmgaoSloAhQmqGUUpiphRBEWZEUpIUlhpAlFZiJYZWYEoCEoqYBhJaKkQFIYlCphIGGhYSEqYCkVYRFApoICChEqSUFZZElEQVAEmqaoRVGKWhKapglEgFaKYoaoipWZESKEBVARYaGRaBEFaEkKBomFlBRlQAWlEZGmhqaAYkUVqBqIYIEIWhAAAAAAAA==";

const chunks = {
  "marketeq-01.svg": new URL("./marketeq-01.svg", import.meta.url).href,
  "marketeq-02.svg": new URL("./marketeq-02.svg", import.meta.url).href,
  "marketeq-03.svg": new URL("./marketeq-03.svg", import.meta.url).href
};

register('marketeq', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
