
import { register } from '../core.js';

const lookup = "AAAC8IkZAiMYbhqm5tzRWDdmZJRGVJZFVEuTQYQld0R0JDQ0eUMjliJFdXJkVzdLZWRUV4NHRCJkMjdrU2VTRCdJc0N1Ykg1WHM1pAEUB6wCzwIUFgxYzxkVAwgVkSkutwMRDuoBFgEK1gIBBA6vAQkCCwkJAfMENQQUEbMIBAEZywFaATezAhAgAegVFkYJBAwbBBwC6AmlAQIEBwERAQK2AwaMYWAGSyscEg5BlAkM9gEBDSpQa9IEDAQBAlkCI3GlIr7vIoMo6cwdq/RhFHLdWdciSFUD3Rm5XzPwriat6bZzHi4cSDKJYTHTyji20CD0y+IfERGrikfvKnXpKiWOvmPOwrD/yJh+OUAkrrAyk7e5S72DCqgvN4beHWkvEYlTkOHx5DvpEH6pnblVaodT2DQbnacGsLY0DFzFRor/Vcu5YBj9TuxWIJ8t2vLR/8/VdsT3gPnHqYoXQ8lzV4GHzVqXDwOEDsvuwh42kFvMATmwcjQwXWkyno3mueVRE4C5wKzWTDtbLplVRwKYEqNqlOw80bGxmbw599Jpfs+knSq6fxRsyw+TB/K7bitWitZB+lfml7FiTMc1VR/XdEK8a5C/ljY91/AdD9YhNR0CbWUXr2/LQKCWVI3fnO9dsH3zCwJNH7u562yLujhe1gRcj+0MyhQDGoGvv/6bNE57LeYbW8/8V9E7Al07jDrh5iaVo+RuHTVCAb/jJ9JxzEW/gVcQ0R0MyWBsTdO6VBRCU3w9GKK4m2Gc1yRxMbvS8DJbsbHbcQUOsjY0zoeplOlABYnYgiqIde4P8OhOBfJgzWP2fEmslGIvWEUdPp0CDy1Trr+cQxsuqxH9LTIaq/StG5zPEReVLeV4cEmQ60NVP74ixXPSgWCcE2+4V61cvc5zvfa1YbymJKw4CeyG0IluYeptN6zzjb25BYy+npvmkBiHPAcz5xfiBfwYYKeb1UbzZtCtMtaJjDB6X3swbXPihEBOCAAUAADMECAAoACUBAEAAAAAAwAAAA9wcm9pY29ucy0wMS5zdmcAAAAPcHJvaWNvbnMtMDIuc3ZnAAAAD3Byb2ljb25zLTAzLnN2Z/////8AAAACAAAAiVgUGQGgKYQGlWFBSgYCFkFEoopoohGUBKEYpqBRRFRICFRUWQWmAokZoBmFgiBYqqQUUJIaJAGIaJFIJCkEQppVZARpIBACREWYhoGQBFWRJYgJUVJRRoVBFiJBkBASWQRVoUpqplElRFCmUUFSWGaaABioApYlUFCmSQGREZiQkUYmZEFAEWYYAAAAAA==";

const chunks = {
  "proicons-01.svg": new URL("./proicons-01.svg", import.meta.url).href,
  "proicons-02.svg": new URL("./proicons-02.svg", import.meta.url).href,
  "proicons-03.svg": new URL("./proicons-03.svg", import.meta.url).href
};

register('proicons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
