
import { register } from '../core.js';

const lookup = "AAACa4kZAcIYWhrzbuBVWC05STNINkgyVlWHQkUkFlVkV0YzhjaUaXVnRGQTgkOFWYYXYodkFDI1gnZ5U0NYW6kMA6cECggBbAkxAtIGAgOzARYDDE7RAQ8SBR0EByYOCBoLkAEdARGeAyQHC7MlhwcGDHvJAhcGEwUCBQcIAxNokwMPYukFmwMDEe8BlQoLDQECAW4vT5cFcioCWQHC/AEyrAHLQ+bG4XEH1B0vYM6X6De0FSzstdza4rVFy1+03z939N6VQWx7NYbJ/jIJGMugAyecKuchfqoXSiytYghVpfN6JqCCNneyuXAPWL7P8VdgxpYMCmTGUCr0drqR/rup6s2otYKVviYSYRzAMZK9t88SnyHOJxtsVlRGjICMyXS+E4/dcto1bXrAHwm4b3B0GWboF/GDs+6CVRaCuC+tM8vGaR6F5KbfawEZ7XTXTuXbkbnfXwVSEFHRcFnQbPTMvmvLyMrAgr4ohzV7a+R1yyD9izO6Q3H2PokPgPl+pvKdRP+pSGeyu02+GE5yYXBxhTq4ZAeKrEKG6cNev1cLhFXCHkS/iqW28DTZU+L0a01E/VSPadaNuxj28jd2A/7JrpYn6sG+g6wBmCUif8JMaWI2B2G8AnvTW9Wr1op2z+qBUfHZlEgKrALyMOKUVKeYwHJpBvJ7xBioAanRq63oEwQxu2d9Z6WL7f9v9Vh/ERvMHI/yLK/XxL/FZRcpSwWsqd0aE19fMUe9Y2Hs1QfvHVrVa2wg1swH2NkUBn5LYG/rYXljqj8lE/gPVnvZPj6HMuw/gBBrmB30ZWZ9FD6gTAAQEAgwAMAACKxAAwAAAAADAAAADHBpeGVsLTAxLnN2ZwAAAAxwaXhlbC0wMi5zdmcAAAAMcGl4ZWwtMDMuc3Zn/////wAAAAIAAABxEFRYARBUVZgVQUAECkEJRQZUBQBEKEERFVlZAlpVBQQQZURUYAEARCAAAFFRIFhBBFVBVBBQAQVGFCkhCRBURBBIEQWGQYgZFQQgRVFJRAAQQWQRkUKhVARkRViUVFAkgUUEWGFRkVUEZYUkRSBhVAEAAAAA";

const chunks = {
  "pixel-01.svg": new URL("./pixel-01.svg", import.meta.url).href,
  "pixel-02.svg": new URL("./pixel-02.svg", import.meta.url).href,
  "pixel-03.svg": new URL("./pixel-03.svg", import.meta.url).href
};

register('pixel', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
