
import { register } from '../core.js';

const lookup = "AAACbIkZAcIYWhpV4cBeWC1VInVlZYV5RWVZIjRHRkc3NGNFREs4VWZ0MlNndVVoQTZmMiU6M1hHI2UlSndYXD0YAwJyTggKOxSnAf0FA0UDDGr3Bg0HCOQDKAMNBAULAwQFBhEIhBUOlwILFAUfHQt6AQQDCc0BYQjUAR8KkQgnBigFPgFtAusIAYoCDJQBAgswlwEh7C0TB9IBAlkBwkaVHIyP3nr5ll4HIKwxxL70GMriFbvE1bzoYNpfyb5w18x/UajNcM6sSz9fj03+MxhyPj6MdoNYdqaPxhrbewLyjYAn7AnLR3vLCevifSrflKkWRUQKYixvZxth7nJWvosHQVUv5ylC6Mns5ocydA8FYxL8qQpUW51LcYV6pWDtrRlf/msEs34dtaygHDKlNgPJAb5ikqi7SNHdfl/kIt3AcU4qliFIN1fx8rr9uB1MplCYfp+sD7135BS4bye4wMbXD1j0xQco9CerddE1EIPGf/BxvhPoaYKHTUSGGPJtZvSVILppcNZrv8thwGy/HR5vtZhr7LQxaRPLZVoGkaquqSapQ/XW9HSEPqCCe4mqmCGBY1mGZfKKr2ZO+NQ29uWcL1WKEYL2NT8eaxIXyz53zFZhrYqnbPGrtsJXxs8ygM4wC1Hx2e174cAbt4sB/dmyCHZ0rQcl32S5cGwBJTcXA2m+LJSRYdYTE/9Uz9VS/7Xq/tUYvci0YMw62KxUwUqgaweA86W+uYUUgsvCU3nZZAJD03IxDOoQ2QEX4u978n27NDUZJjNnAd9r6VW/P0TaLAbQZ2zql4IFH2HDz9y7skwEADAKAgAAQBgKIgAAAAAAAwAAAAxwaXhlbC0wMS5zdmcAAAAMcGl4ZWwtMDIuc3ZnAAAADHBpeGVsLTAzLnN2Z/////8AAAACAAAAcQEREkFaWVElWWYWURoAAAVJEBFVlVRYFBhEUVAYQhFQZIEkVAFpVIAARGAlgQEQVkBRFRUAVIEZVUGVkFAVUEFURVUUBUSRVkEEJGEBQFBAAkVqASFSBBASgQCUQWAAEhEAEEFUkFFAVJEhEFAFREUIAAAAAA==";

const chunks = {
  "pixel-01.svg": new URL("./pixel-01.svg", import.meta.url).href,
  "pixel-02.svg": new URL("./pixel-02.svg", import.meta.url).href,
  "pixel-03.svg": new URL("./pixel-03.svg", import.meta.url).href
};

register('pixel', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
