
import { register } from '../core.js';

const lookup = "AAACcokZAcIYWhpUtR3FWC2XVUUjVWQ1WFdGZJZkWIc6wlNoMUEkUlVDg0RDV1RTaCVVhVo1IYhFNiZWJ0VYYrgBSQUYBwQGFx4OOArjAxwGAhQEB4gBA4EMAooBogQPhAGEDssHBAPCaAHcAUUBBgQCAQcJMwECA2oFCAMDnAICDAcDGgxBEAE6C8gE8SYQEgUCDdoDOggbDwIDIjACkQEOAlkBwod0SxeK32/ZNr/xvVg2hvnCVTfGGDVycpVgRFO7xk2pSGN9yAY6gxfqgpYvvhWsw0YDqZa9y/8yqUTWeRgKe6wFYrXCkTNrayGFoK1hIv4q1Ak1MtUCCbqLzswov/4QtIL4gge64gdOJRjyt2B0qNd38XBnZpioUuFHg6km0H2uA75XpWHeFFbNu5h1WwFvisxf3cl2NGe+YNPBXx7y12lalD5h2sBYoIxORMrf7MAS9jFDBrTkpvFWJ+Ydfz4cY6aPSj8+HT+r2bhwZ2KFre2yD8uCdMsae2z2E+LRLDH0HXbJKdZwxpgBzgcyjYC72K3Ra+fJelT88CyHEkxXGy+1Ue8PxLgYirsB6Fnsy1++Fm1L9HFhM7n1VGFInY+C69zPd8snuBOl6h7k6nBsEELsqmz0rNZrP1QIgcbZ7tu+tYYnq+JFJb8buUNyAn57Kv0mC/OscV4Tka/VlQQ38kFpp8ssj2XEUdU1IPKXAQUHab6ywBfMVWQKtjGAhCFxbH6+Zc//EfR+GWRf3YyUH6yqMBPaoJ/pB3v99GkUvPJV7X+LGWucASDP6Huza6Vm/j5v2cB66FAcgIlND+XfxZIMdkyAIAAARAEAAAIECAAAAAAAAwAAAAxwaXhlbC0wMS5zdmcAAAAMcGl4ZWwtMDIuc3ZnAAAADHBpeGVsLTAzLnN2Z/////8AAAACAAAAcZRkBRUUlgRCUAAgVBVGWpZUWAFRAVVEFUkFSSWApUIVCBEVQVAUQBSFSUhWUUGVhBUZYEFQUgGFAABhikQURBAEBBEkQRgBBZFFSEBBUAgQVVkRCAVEUFBRUIRAJUgUBVGVhJABRBIVRUEQUBEERIECAAAAAA==";

const chunks = {
  "pixel-01.svg": new URL("./pixel-01.svg", import.meta.url).href,
  "pixel-02.svg": new URL("./pixel-02.svg", import.meta.url).href,
  "pixel-03.svg": new URL("./pixel-03.svg", import.meta.url).href
};

register('pixel', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
