
import { register } from '../core.js';

const lookup = "AAAB5okZAVwYRhqUYl4xWCMqeEWERjCFVyRohXaEJ0M1VkUidVVlJ1ZVVERzImRbNGVURVhJsxABlgbiAQwDA+oBTwIMBS01BTxIA9gFQsgCAYsBDQEJGA4LNzoDFwEElgIFKicGJgEOAxUNBVoRCYECJgOubwICBCMvAjcWBAJZAVyVtbq094Mox/mKtjJBaRQHUrdiBRTiIRSqbIiPSPkDt+y/B+iDjj4/JFNt8pJp170Kxhn+E27rpnOB/WgnRaNF2uoFpcvDiv6sTftoy3sLDGucR5B4+jTIO5v1n8+PO3W8FKni3nJvCXGDL5IYfVOLG8JFBH9wq7v7Elf5f+VINhvF+UDmoJCw0hUMsGtvJHNuqdxSTG1JoKdfxQEa2nrKs02YQ0DJMk33m+9Yw49v4dpbf+VHA5ezUCu8rUHdLNEQy/OVdttMl+swEyvGLGXmd6ilHk6U6e2BuEBPrmjOFr0sHiIVHeUXrM/5ZxyvuFx5tJVsRPMMONp+vuOWnQJUYCg6pTmHosT0CzQnoEMhoY8i+TgRWaZ7kDJZ8Jia8l7eUelnKoAqB2rKItDpFPdF2fL4g0IzbIJdZ8G88ObcvRsqRFrn8MC1RiWSgr6Bw7qFnVmDfKy55KsKIxtJAAwCACAAQAMAAAAAAAIAAAAJbHMtMDEuc3ZnAAAACWxzLTAyLnN2Z/////8AAAACAAAAVwQFBUABEAQFURBARURFUBBUUEBAAAVBBFBBUAAUAURAABBFRUQVAAAAEQARUFRAARBBAQBUVABRBARQFERRRBFEQUFURFEEVVVAABFEQAVUVAQQBAVEQQAAAAA=";

const chunks = {
  "ls-01.svg": new URL("./ls-01.svg", import.meta.url).href,
  "ls-02.svg": new URL("./ls-02.svg", import.meta.url).href
};

register('ls', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
