
import { register } from '../core.js';

const lookup = "AAAB6IkZAVwYRhrJDcwsWCNWKEV2VzN1J0JyaBRIIUFkOUakUlhWRTSDaVZkZIS0M2KUYlhLCm3wAgkLKPYBcg8FCCcGFQEDigGZAj8L8AEICwyFAaUFCgcBB9sBAoYFL6YCayIQEgcJS6YLlgEFAgQGAxYTvQQhsAED9gGDDgIDAlkBXAPPlKL3+05w2qM7uJAHRI77SF3+NCV9uoEju6zjZ7wkvjlo8pe48wzGeWyL0gTa8Mh2ynOqnKXr7DDpBZhoxTjb0AwsCrf52YHochHpR+sUrMNgUUBNB59F71+Pben0Z1oiUihJCxVcmI+8WK3ky5ZURqUypeYBbMupeIIWphSDG6BqQ0Wb8H8bxLdn3IMnq/JCtuIybwcqOyLDTG60ztc6beF8lbDFF/cqQEMDoJ0QyeUrq4FQFZUbTPmvvan9j7peNPq1g942wWlZtGnGb4ALrmvtw/4sc/V7lb1F5cC1RPn5LxuS+flsZQUZkkFiRxrzW7lNWY9/OOfis2vHISvymz7RvwoUJyqnDKhBg8uKM/BIyrOXFG5/3M8eg5ChQKBSU2gee5qmvBxN6kWIgr4hAjJ6dyhPJBgT9x0sE+USflPdnXWSWbDe2oeskMLmvW8Uigk/hfhx2lfmIkkIgIQcQAAAgAUAAAAAAgAAAAlscy0wMS5zdmcAAAAJbHMtMDIuc3Zn/////wAAAAIAAABXEAEUFFAAQAVEVRABRBARRAAQRBFAUABVEREFRVABVAVBQUQBAVEUEAAEEAFAAVQVRFREFFQUBEBRFBEBAEAREBFAUEEURUAVRFBAAAUEVFBBBAFUUQQAAAAAAA==";

const chunks = {
  "ls-01.svg": new URL("./ls-01.svg", import.meta.url).href,
  "ls-02.svg": new URL("./ls-02.svg", import.meta.url).href
};

register('ls', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
