
import { register } from '../core.js';

const lookup = "AAAB6IkZAVwYRhreT+BCWCNyA2a1ZiRWdTJkNDU7VFdEUyNaR0U1GnRTRDNRWmWIcpY5VVhLAbkCA5UBERGBFBt3AwMRFxgEAwoBAQL/BgMOHI4BKAQHClLJBwMnBQ0GEgLGAgTkAgMaCQMCDMwlFgMfzgH7AQGnAzOGCK8CBAMEAlkBXNcSM+PQbwxZQSyPkCoRDJpATZJuAgc0vHPw7Ve9XoWgoOcWNgP+TE3ax/nsaLwokOKpZX4h5d21cWmcfB1vWfmW8OJQ3ls5yqtsb7AhMqBDG4s/FK8Bt0VG2uvFekwlo1KDIvcoUs8LFX06ppXJy7aQJ1QHs5XZK0/6wWdRec/rKgxEHBtHGq6sgjtA3LcvcuYrf0VBRZsEdp2lxLjRrDiDs4EwlR66FFyn+Hjm2mxCZ2cs+V9TsG7Dw0O+FB5grBky/rWdImvyuPnG6Vr0OIHDaCO+5QfplCxOU9uDpsjyvY4F+aWDF9J3bfDvMvu5a5KtCYrAg8tq/ehNJKjFqZ9pv6LlxkA0qqsqcN4T+0VtRF3kSI8buoqbj/P5G0m8IstZtNy7J4ilf3NYaJjzdfdIE6HhyguH9xBHewXCewNsFL0K2o+09RSX6gqCO4EVYpJ/zvIYl5iA5j4k6UkICCEADCBIAAAAAAAAAgAAAAlscy0wMS5zdmcAAAAJbHMtMDIuc3Zn/////wAAAAIAAABXRBQARBEFEBVQFFABRQEABQURQAUBAQBAAQVBAEUAREEVQBQQQAFVUQQAQBBVQBQEUFRUVQRVAEUQRQQBVQAFUQEAQQEVQFQEUEAFQBFAEFEEAAUAVRRFAAAAAA==";

const chunks = {
  "ls-01.svg": new URL("./ls-01.svg", import.meta.url).href,
  "ls-02.svg": new URL("./ls-02.svg", import.meta.url).href
};

register('ls', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
