
import { register } from '../core.js';

const lookup = "AAACQIkZAZ4YUxoVerM2WCpSw2lXNjNFMlWVVVRDRFVEZDJUJTh3BaplcwJVZWFjU2VrRIZCc6dlpANYWBwC2R3DCzZ6AQQFBAUCAhwFDqoPLBoMFgMBBQwWEQ4EKAUXNQ6zCgS/ASsKpwTOCB4/AWMBGQkEDwkCaAsUFk2sDYECEiE4kgMBAwbqBMECoQMRNgOJEgECWQGepmeT/iJ4pZt35svHOH7yD5hKVFobf2A9YXBhp9WBd0A3S2f05l4ZH1V4FTQYVGwYlM/Et1HK7mD31+J2eDPth/LLbaYGq1zf71Yt9phRsOuYU2hCTn4d2zBWX2mMiklKTjGjJWzg2nY7VESVb356Gd1BxFCSn2yLA0xin78kjb7lwrdflffV0Soe7KKZ10faOxflnY5EcabO4fcw6PWfp8vX0hh/1H6SBQJ3erOX8KxITL/XCTEm4sNJwqU2vb8isNczR2GE17lPwPM6vusq+vdo9ZNvYPBbB2ushNB7GqSMtrpmuFOe0sZ2XwZvh3FwXWXClGlrbLsqCSBHMnVYwfxnkpp4yM9XWQ5lj4KPgZPpUjslFsEJblxS6lKk5lgVR2dCTimX7r6pecyLeomYzGqEg1TabfQSjHBSg4uCtmuAxRR2tYlGvegsDp0LKVKhk4ttG1MBLG1zTkAeheVAh9Q38h71YgANXhhdeboZFr/OcuK/f0ct9AZq0grBmCyRuVRz24y/16JHuxujyMCMzlDO4/l2tOk5WOe/h5dbSwEKQACEICAEAAAAAAAAAAMAAAAOcGFqYW1hcy0wMS5zdmcAAAAOcGFqYW1hcy0wMi5zdmcAAAAOcGFqYW1hcy0wMy5zdmf/////AAAAAgAAAGhQURUQUQEVQAYQURBRREARQCBUFEFUWhRQBRBFFQVEIQVAFFQAAEQBVFVRgRVRAVFERABUWEFBQZFBQlAgQBRVBVBBAFUEWAEFBFBQGQQEQFBFUWUUVBFUVBEAEARBEVAAUVEGRBVFBQAAAAA=";

const chunks = {
  "pajamas-01.svg": new URL("./pajamas-01.svg", import.meta.url).href,
  "pajamas-02.svg": new URL("./pajamas-02.svg", import.meta.url).href,
  "pajamas-03.svg": new URL("./pajamas-03.svg", import.meta.url).href
};

register('pajamas', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
