
import { register } from '../core.js';

const lookup = "AAACPokZAZ4YUxrzd4yeWCpEVXdlUnVXaXmTQnMjJpV0ckSYc1dGVVR3NCc2g0QzYnZnZUIgRVYXVQNYVgEeIE89IDABHBIQ3wEMgQRV5A1aBI4DA+EDAU4CE6sH/wMBiAEEGs4BzRL5AR4UFAUBGhALgwG8Aw4CZRoMClINAgIBBhE8swKrASseAQcFCgUQCgsFAlkBnuY9YtfizsRY+Y6+uw52GW5SD2nySx69159Hfhdh95NEuMZ20l3wTssJxFNAUkeL1+gLWzPf6uVbtnkgcaZMGcpfLYxoWIRsvdXvO6TOumcNv6cxkXK5R37b6+AaGKbCb6Fsg22KQGZ4LKL1cFXy8oGYJZNUaGF4TlTPwSK/akfS122+OsdtT4cqazll7rf1vtCE14lOb4t/SF1/Z6cfCkk7A1gWIrSstdptAJ/3pVBppdpELf5xwmxzB4s3Tniw6ZiiX1LRlVKzBmDCks6PyLnzjaNCMHAsCXrtdhujv4fBxTar4p1H9CqpG+wY5iY4jOudlXdBUUL2YlOS1OJrnl7u9Kaa6Alrc2/BLI9+ggYZemF6z1HVStT3g79TtgFKBUfj12VeMWCwv1BWkimbXMtJV/y6iWoGHRV2mMwWu8sbrJQqdaSLduWTO2CAVIQl179UM5jd2xT60ueY5XdsMlmfGIGXX1yMtzCTwECHKVLpmYfAhcwSZ+F7JJf3Z3fwcJQOeYx4zkw3VOY0yNrDlx4VjPUCvx5WRn70Whh/gksCAFBBQAAgQECDAAAAAAADAAAADnBhamFtYXMtMDEuc3ZnAAAADnBhamFtYXMtMDIuc3ZnAAAADnBhamFtYXMtMDMuc3Zn/////wAAAAIAAABoAFBBFUBRFFBZAERGFURQRJEIUARBQREQQSVRERUUUFQBRAAARVQRAFBFVERAQVVQhVEgYFhVFVEEQRRFQUEQBRAFQVBEQQREAQBRBRVQUVBCQRBUBFFFVEFIQlAQURBFAZQQRRAlVQAAAAAA";

const chunks = {
  "pajamas-01.svg": new URL("./pajamas-01.svg", import.meta.url).href,
  "pajamas-02.svg": new URL("./pajamas-02.svg", import.meta.url).href,
  "pajamas-03.svg": new URL("./pajamas-03.svg", import.meta.url).href
};

register('pajamas', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
