
import { register } from '../core.js';

const lookup = "AAABwIkZAUEYQRpJrfGWWCFTlVZid2d2VCZncTNUY2ZYIiQoJVkzaUN4d2c2FSJGJwRYQAFeLK4KCSurAURy8gKcASpNBwP3AxgTAwMPDT1TWI0CEgIG+AcBAuoIXwIBoQeNAQYRLSxRPQxbJSQBAQgDAgMCWQFBMR72GTW4q1RpJEgqWMtHkEBhoO0CUW3LCZySZ/I/cT5xGyXutSr2PU6te1nMKv7muoMZFVVsuRe+HGlj7YRvr5gdHaybUNTPVkT5GLu3p7loJhzna2A5LpSVbUGifPGsVrbnJiZfqdOVUk7tMvJTIKOCr95YESp1WZXDHyy5jyWfh3tiPHNHP+2pNgET8y+mjnnOQzDlo07IA9XBCgwig7Zh8zQ6MJaCXXJdn6/mv0tbJHjTPF1lLJvsB2eagewjHWxYJb8R8HppjNdI9L5pmzQs8RJs52mJ8CLiwwHSFXGKSRipHpIVJEPAmLi7TtwU2xyZI3dZenaj3sK70UK+AymshL6rVRIyfsIgbB0cZV2lc4ZizoWheDqwv5ZSwpsUJ93diWAMyvCnnPBlRwH6vYAg/n97Gza9WuY6UKrWYVGHSUBAEgQqAIAKAAAAAAACAAAAE21ldGVvci1pY29ucy0wMS5zdmcAAAATbWV0ZW9yLWljb25zLTAyLnN2Z/////8AAAACAAAAURBUUEBBBUABVREVEAAEEEBBEARBQAEAUQABUEEBAFRFQVBVQAQEAQBAAQEEEAFUABAFQFFEAREBQEEFQAQBEQEVUQVBAVEEFUAAARAAFARBAQAAAAA=";

const chunks = {
  "meteor-icons-01.svg": new URL("./meteor-icons-01.svg", import.meta.url).href,
  "meteor-icons-02.svg": new URL("./meteor-icons-02.svg", import.meta.url).href
};

register('meteor-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
