
import { register } from '../core.js';

const lookup = "AAABtYkZATkYPxq2P88uWCCWdBdldRYUk1ZmWURmJFhUg0VGNoZpRCdXQhUhUnRiCVg/OZYCvwNZAxUPImYKBMcFJiwCAvwFHwEjDAPnBQICGwZBFAQEFCECkAH/BwkhDAy/As4BBQgJAgIcAr0BKekCAlkBOTFtVb6Kor5S5BLQ4VUmO0fGbPo7HWB5uVhbXVHmjMS/t084G6G22oHwjO3fVrNFhu8CeoVCoHY2bZi3MCGv2rZOCEvP8njtacOnZba/WwtNNbsHyyzVJHIqfGT+GIGmoBd+JUQcnntgDY5HQ2GLpz5G8ITtrEFCAbkKaX45/ugV98Wrl60A7ynd8wO2jCaOAtwsz/7R8mknDsSHIBGdQ2bEWLr00rrED+QMae/wNgYYqZ96a7Fa3xijH5BTvSRnDBRV8qc2uwfT5uQkDzsblmw3sOBRuxYDc5K4ARMeHp2puSUsj+rm7MmtQgTWrBjzW3DwgdAXrc4ngPTmX3MecdWA3uYZIcU0mK/AgFAg/0J2JCHOvUH3uWmD3D+cqXMVUIKoouxfqRx0vjX5VTGVlWDeE7CHrBInBRNIJCiACACAZBAAAAAAAgAAAAxwcmltZS0wMS5zdmcAAAAMcHJpbWUtMDIuc3Zn/////wAAAAIAAABPAEBFFBAVVRVBAAAERBEAFAQFUAQBABARRABBARABQVBUFBAAAAFBVEVBAFEFEBRQFBEQEARBQFUAAQARBQQEQAQABQRABAEBBERQARQEAAAAAAA=";

const chunks = {
  "prime-01.svg": new URL("./prime-01.svg", import.meta.url).href,
  "prime-02.svg": new URL("./prime-02.svg", import.meta.url).href
};

register('prime', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
