
import { register } from '../core.js';

const lookup = "AAABtYkZATkYPxodwdGXWCBUZVInNXVAdRWEVCZXaDZVODVmZ0GYVIVjgnQoUjZECVg/AQkPETq4AwMRAxkbDSP9BA0CgwMKJ6MBAREDQnECFhCbBQ4CVUHbAxAE+QP5CgQLAX6vAYwCBSSICQEPBAJ8AlkBOXrObdU+oCadNE/wWjamO7lO5PoLlvDFxCeMIaGnn9okdmBCuanwrc8Mc2Q14GmX8pwsVotBGWU2FWFV3LC2Fxt6u/9VOAPeQqLDuebWmPmAHQGzbWnm3QJ7ydW6r8aFjlMqMbbaRqvmzuS+nqx0DQetRQ+s0vQmHMRfB4QWu7ppsIKY/lURQ4cEeVtDLCAFFSWAW9GV9FATMIPEGIYnN79yJAb3UpUk0BhHfmD+GCFptxvvcXCS6L278qy9uYd2saeptv7fUXi2URhrH0FYgZ0/YGlsWO05jOoD78V+zzG4juyMD8QkHlUIJ6ffZvM7j6nhHOaQIIG306lnoIE2DK1CDuwSF97Qr76iTTUKAcvcfO1s5IoA7ROjO0IhFB7Av4CoRPdz8hMs5lvzAkspUF0SR3Nf8B4l775IEBACIAIBhRgAAAAAAgAAAAxwcmltZS0wMS5zdmcAAAAMcHJpbWUtMDIuc3Zn/////wAAAAIAAABPQFAAFBABABQFBRBQAFAEQVAQEBARQAARUBAEFUAFUAABEVRAUEQUAFAREAQQUQUABBBFRABBRQFAAUEFRUUUUERAQAAABBAUFBEAQAEFAAAAAAA=";

const chunks = {
  "prime-01.svg": new URL("./prime-01.svg", import.meta.url).href,
  "prime-02.svg": new URL("./prime-02.svg", import.meta.url).href
};

register('prime', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
