
import { register } from '../core.js';

const lookup = "AAAFRIkZA+YYyBpfmFj6WGQzh0hiYzcTZGdYNFM0RXNGIrcZJVJURmZUQzdVd1RjNzQmgjV3dCU3pTMjVnNIdEdFZjJmSDNVs1ZzVXJZRyZBVjiEOkMTkkNIKYYzSTpWMyhItjGmhSEzhFdYpWRkczY1RzeWWMsBAyQ/hAwJKwIiNgsEFAgyRaoBCQ0BEwYdCANIPwEBBaII7QcDCgxfJA1aCggClAIkQHpjBwIdCgccPwIGNwFRkQMLYxeeAeBEBQJbCgVtoAcHBPEEGSUFUyUJWQ6sAgoFAQwUAvYpuQEBAbcCKzdK7gghvgMGWgYNKYwCAoUO1QoBAgIFAvEEGQesBLMFHqMBAcwECPYCBk4JCASKAwFBAR3NbAfxAfwBI/4CBgMT8A72AQwHBQ+mBgkPHh8KAg8DIQEfCB0IhgHIAgJZA+aK40fL8PBcSqzJ1afO4lN4VEjuj6RnsPuHjihA0viw1ne1u75Sw7cBKRbB+mwjJ4L6gJzwGh/Xr+VBjb+Jq+06tZCBvnvpF6o1Unj33oHR+RTxmvKHH9X+LI70fl1Mq1jjP79U7T53ou/aHPUCytsuxdfN6vwzgjQCRSzibm7KJoZOGLrxvk1oO9k1Ek/EuikKcfgN7MRnhEy+ALe7cAAHAlQpI6cwhxUbiRKeBqnzctMqajTjuBtWNaHuHfS0Jx+UmXj1iwgJdaPT9XUWS5WUn2mkfQRvZmzdiRvTcxHChBXTL9xJ+NkPOXbJ8YkdOPRI8VvaW28RPQ3TknbJsCqqQHn9AIuXqHRyoPZwcRlTwaw6S3+mA3yCoVy0fDL+pRJTpR4caOCgVQ5rJh2DoyQUrACv+eux+q/BLkDhxwTHmNcd8L4xbKc8GCVmnhnDlpAjwxG7CVo46VkXNHvho56AeBsv1g1LhqRxRgP4s4ycORT9nPJeFHIUjYWysfl8NUMjrlNCY5t2se6KTT4zHYx7CvmcRyhAHbtwnx3XMxem/Scr+EflTAXx9aLM9fARh+1OfLH05vGVQae3T+et5nSCyg4ylB64H949Mgthwpqyw6fPQpX4DhhTgYVvQ9qntZcSNRPGy2oNtY5vwXvBJF1rV2jf5FgMKPLTpaQX0giO4LKDZwX07F7k3hkgcy+pAJW16UNVbFSM1sneRIAIaDVzQR8zPlQ8L2B2f8XhrX0in1uhb8b1V3DLYGkAzD3mVcTY985crqNs9adEmTW/KmzF1jb3MKchHUsIh9pu4FsL00D13TLrO24uYKnT2AP2ZnaSCOD2/EVf41VDidQ8xJMWwpJA8gDKYPYoIIoxhCPMFcIkaS08KxMBRJxgU7zi55SD2nObvbGIRNIuketoO7pGlErBvFqr99RVGJA+lZBN9ShKv9laM3cU1Mlo7XZ3E55KM5dGPbL+E0wsdXmNArylcWJc6PYmqQsyPs2UadvFGLjev+VffWyRAWGv4zVGuhDs1fjFXsuHs6dLMfa5eCrOCYtFKZPSjnXR3SJBDuMiC1LVDoPDEKSmR/z/kQ+6LaGV56hxX/fuMLYdQcDfHf25V7xycS2FJfvKBN3SBoLOVseDArm9hNq2UsWfl7HkIKzWr3eyKOz8mTGIJDIYhD4bhgCQbXTGCJ90mAloLdL4qyfzBcDIP4tDR8/lBvaSOR4TUaOLI0lBCsC4oIJtwv77EHvOTrzxhnEMYnK34GIqtLMquEak0IMGW3pTexwWXwNIJqbgeqWFJNVD50vBPbAHQjeTBXqNZ2uPfMftHKj4szpVzDK5N1gZQCBgAOIgIhASoCVAEABAYBAISgBAMAAAAAAAAAAFAAAAIHN0cmVhbWxpbmUtdWx0aW1hdGUtY29sb3ItMDEuc3ZnAAAAIHN0cmVhbWxpbmUtdWx0aW1hdGUtY29sb3ItMDIuc3ZnAAAAIHN0cmVhbWxpbmUtdWx0aW1hdGUtY29sb3ItMDMuc3ZnAAAAIHN0cmVhbWxpbmUtdWx0aW1hdGUtY29sb3ItMDQuc3ZnAAAAIHN0cmVhbWxpbmUtdWx0aW1hdGUtY29sb3ItMDUuc3Zn/////wAAAAMAAAF3CEchRBiFE4kkUShMo6SR4QYxiJYt2sAgHLRB47BRDMKRmygwgERoGsCEwDBxIhNgEBIm2gYxS0JIy4CB3DBMgjQy3KZBIhVBGiYwFLMFQSAi0SJiXCiFizREWCJCEjQMiiQOW4AxmQYoIcExJJcp2qZAkZSFI4UlCgEiwZgEUJhpozBNGhMQXABlkQJNHARkADkw40JhybRpQygQoRgJ4yAKyEQSA4QB5BBG0EhqoxZglJCJUoBs4JgIHAZRSxIS0AABHCIFoZIFSBJIWKgsw4QNIBkCYTQxHDZxGjARGzUoQpgIYURkjKJx4QKO06YFG8gMGRZxAEgMYAZyJBMM1AQRAzMFWiaJVIgBDMaMCZVEoMgkC6kNREYxTJgEIyYBDECSicYFCEWJIghGgSBwUihICEOQEyQM0wSFQzJKjDZICiVJEJMtSRZICUAkWiImAYNsobSJIbcAWhZC2raREseJ4AAMwkSOAEktEIRERCISwoRg0gQCAAAAAA==";

const chunks = {
  "streamline-ultimate-color-01.svg": new URL("./streamline-ultimate-color-01.svg", import.meta.url).href,
  "streamline-ultimate-color-02.svg": new URL("./streamline-ultimate-color-02.svg", import.meta.url).href,
  "streamline-ultimate-color-03.svg": new URL("./streamline-ultimate-color-03.svg", import.meta.url).href,
  "streamline-ultimate-color-04.svg": new URL("./streamline-ultimate-color-04.svg", import.meta.url).href,
  "streamline-ultimate-color-05.svg": new URL("./streamline-ultimate-color-05.svg", import.meta.url).href
};

register('streamline-ultimate-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
