
import { register } from '../core.js';

const lookup = "AAAFQIkZA+YYyBr88jj6WGRFWWYoZlYjZ1VUMnRzVTaGVXQ1VYQ7WWN0SCZFM3SDMzd1IicoYXM1VDZDNXZyMoAjREJJUXk4MmVnJyVnhUR1ZXSGdVZUWEE3Y2VkMoZGNmVWJUczlGRpRChiVWZmV1lZRXN0WMdXAvgTDbwBoAIvsQEHhwEOAT1cDVoKRwcG+QHFAQEROAhQvgEeBAYUCAIRBQGkAtgfApUnEQwbCBGPAQMyAgoaAgbrAQSdAQKhAQQTEAEwaIwBEBMUCRcMEwhFCgnRBwEQAwLnARUvcKoC0AgMAQJeFXYeJA8BVRKuAjoHBzcHHMwCjgGoBQIuqwEBDxKBAQNSBDYmSBBLEBHXAX0BOQIJEBQbQwYECwxZC4wmQCMl0gYBXAkUPTIiMRg+uAc7egcWAgJxAusFAlkD5gZ7U0P2eIb4dHZ9hjrbC27CytOvMH1ZXVNmtbyOrR1Kf2t7l/DSgZ+mHxROmSJKgnCCVLcb2jMYV7CDJJ76LjWJuLBThMcYHXez/fV8nB6vW29FhzH3ikMQd7l3IRI+VNPB2pSPbk4s5nYjJkOlh7+lBqGH0WDt0XCc/0G6444qNxPa7gkAHeY1zJUunBv0BVUTMjzBHGt29XJLw00EZ/Ht6fbCMrl6tXOYQPVoqelvAqxgiWhj7tZ6cgIAL2ZF7LJ6xg1Srhx30D7kPpKv8aLs03WRJr7gREj1vhFcDY4AEynyW0/iifBydEaAQTWpMwBgRA7z8e1sxc7xQw7DFTXS8gctQeMQaMsxrwIxp0GRPAP0qMZfHypUdkA9x6CTsh3f7olGVTBT/h5w9Q7z516EYHHV2NrNlWrw/lq+CC/VNb/A0qNv8tUX2rOO+hcKKKeDxBSA97wD5bf4y0nTpSNyMqTun4VCe2z0EV/TpzWG4H+NHAYpwaCQxawVwsSePkdiy6bruvbB7YmC/WHDDuN8u5wokPafQzPWb2yolt2qiCqLPaOAg8v47IL+54QgyUrKsJGvU4NXxKsqMrHj9E3CfveX5AwI3ptMOfLZ48nCj2ze/A3ZpvwdjHBd17+FzA8SuIRuzG6nTONLO/xaFI1oed4kNEFICAEZgVuz5XPlsh8+R5kKtexa1vUW9aOUwNfMcaDG9kU9ZwX4sfgUqXT5sCAjseFfpwmy4Of0pL5KXLgrU1WffDTJYpIYh2kiciQf4Ys0HgWtN0Q9S4y8eAK7yvb6IrlcxUC9jR97q9xfCGvfs+A+yOhxc3FIR0teB6iUhW3dQBeyzlH4ilgY+LkLUqeszZ/dKM/rVC4mQs5BQIUAFt5MV3zDdfmSOD/l5m8d/SlcCMEkus9pLTvEcXMnMyozJ40891S8t7VVmmfr+ZRPR+D1q6m1lGx1obsjEa7ip+SjzmgyJKzK2fb4GygsAXjSpC3HFfBGsYcL11v11hTXNnnwxbSkth2haJeDJ9N4v1IRCdWC3iUAArS/aRcWdB2jNRNhHcUue2fbng4AkDkw8SPTD44bkjKautSDRiVC7UPFKHFeFpPD56GKPVJiG/e48ZXUTDvqbIimL9VTujoQBkAs2oueA/vBaNIcPIu3WNZ3+7TvFNJLyapVohhxBJgJx2kDi9gMOZz+zrybeDVmmUYm1LiBI0nhK0sp/E7JpFtHKqcaEggYIJMNpRPxAIeVl3yrMgGVOr1tBLGM6fgFErY44pUKGfuUP91Ve8F1gi3K4GylJxmnwFb9+XYxsZAoVgukM77TTWC7anZ9RJAvhoQdWBmAEBABAAAAgZCGMXQSAaAABMAEASASEAAAAAAAAAUAAAAgc3RyZWFtbGluZS11bHRpbWF0ZS1jb2xvci0wMS5zdmcAAAAgc3RyZWFtbGluZS11bHRpbWF0ZS1jb2xvci0wMi5zdmcAAAAgc3RyZWFtbGluZS11bHRpbWF0ZS1jb2xvci0wMy5zdmcAAAAgc3RyZWFtbGluZS11bHRpbWF0ZS1jb2xvci0wNC5zdmcAAAAgc3RyZWFtbGluZS11bHRpbWF0ZS1jb2xvci0wNS5zdmf/////AAAAAwAAAXcTBQJcoogYiE3bQgTAODKblCiYpmhcwkkYiEEillEiEWAICUEcwYAjNmoEx0hTRonIFkjbSEGZNC6cMgScNkgcEU3KhBGYRpAgwwGgNo2auAQagIiLAlIUglFJyIxApCmhhAFEuHGhiCgjwwUTNzEgIoAKyIzhJg1SJAbMECQTpCVkEAUhGHEMt4HbIE1ISCnZGCwYRQGgtlEBkwRZkhAZSGBJgI2jpkgkCCHRQgKKpHHShEwah2VjhJFJMCAYBEkZCJAQQE4jg3CDBgzKlDEMJSgcSGjQEmKZpgQEki3CMGwYM3EEQIFMQIDbwEWikGAQFYTkNg2RNgyioITURhIkhUihAjITMlAZBCZUEiwQxoxhkiDjQmbUKGaTRoERBClRwoRMKABEJFEkJSKaJnGLiEEggATMQkoZJwACh2SJJmqTEi4CslCRoixbAECREgAQB5CDxGUToC0KxCUUQUTLEgkEs0QLgQhIwEGcJEFCqGVUuA2DGAAAAAAA";

const chunks = {
  "streamline-ultimate-color-01.svg": new URL("./streamline-ultimate-color-01.svg", import.meta.url).href,
  "streamline-ultimate-color-02.svg": new URL("./streamline-ultimate-color-02.svg", import.meta.url).href,
  "streamline-ultimate-color-03.svg": new URL("./streamline-ultimate-color-03.svg", import.meta.url).href,
  "streamline-ultimate-color-04.svg": new URL("./streamline-ultimate-color-04.svg", import.meta.url).href,
  "streamline-ultimate-color-05.svg": new URL("./streamline-ultimate-color-05.svg", import.meta.url).href
};

register('streamline-ultimate-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
