
import { register } from '../core.js';

const lookup = "AAACCYkZAXUYSxrkIQLHWCZGQnU4Q4lmNZdEhUJlNkZXJiGDJEZVZGJJIYVzZDJlSHFDZXaFClhPNAQDBzWDARUEAxiFGqkBhwFuAQMcqwIMDSYoAQ4iOREGHgNGBwQB+QQYRQg5EQHeAakB0wgNBiYEzAECbwFLRJMDAcQBCwMhDhpI0wHqEgJZAXUUTuQPyhDaW+jBPbUvKEd4edJBksUrj2muPpqzqSBV/ZmDZvVB2QAoryf5IJsmDdCZ+qG7wnzD58905aCcHU2P8pP35JjjQFUflFmh+/PIoydpgQoiB4EmuTvT850OJ+cTMuSO86x5ZXzvp73dP0EneMbKb+8PyoLBDo8NM1qZUtZJ7UJNRjnKxzaMvlYnQtOHpIIIKr9KrS8C2c9wBiGctXnKFwNBotOcaUBWHdP9xXhKYyYBcHCXfJywd2B6ApH01+tClwfRiysqv7wI3EtgEeyuAGCNZ5rhTZNw4oYcFCFhE+8d/0zlgTirWdAJAQCy6GmG6saPDloXRSpShojQci/k9KiLDrkx1iHZtHXnLkuV3lS7SXxHJDgBoRGerAXkgY/eOR3GspspDcy8tE/4OejdIVtmRfPlJKyblagDbtSu6JBNdSTeL/+YEGoSdAen1yjCqB79VEIE3lG7bOiKLT6Z+O5rFFfGra7UTKCiluqnU9+BSgAAAACOQAwEBQAAAAAAAgAAABFsdWNpZGUtbGFiLTAxLnN2ZwAAABFsdWNpZGUtbGFiLTAyLnN2Z/////8AAAACAAAAXgUBRVBEUQFUAREUBFRFUVFAVQEUABVEAAREQEBRABUUBFQEBBFVBAEVQFBFRQEEAFBVQUUQAUQQBAFQQEBUURVURBABUUFVAUQQVEFABBAQQRQUABRFEUBUVREABAAAAAAA";

const chunks = {
  "lucide-lab-01.svg": new URL("./lucide-lab-01.svg", import.meta.url).href,
  "lucide-lab-02.svg": new URL("./lucide-lab-02.svg", import.meta.url).href
};

register('lucide-lab', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
