
import { register } from '../core.js';

const lookup = "AAACB4kZAXUYSxr7iISpWCYyZzJUR3RHWGdSWTQmYmJFR5ZJBUJXVxhlUzdpYoZjM0g3WFRHAlhNA2gUAQEEDzsdFW2AAQHOAg6kARUBN5MDNgIBLgEBBwoBHxAQrArcBgEXAgQdBJ0BAX0VFwgjGNQHOAE9EOUHEN8BA5gC2AMCBAZSBgICWQF1hqC/u0wmgnSn7u/alOi0UQ0r/e9J54YoL6wQJ+e/x0/TKrBpxSRr6JjGw0Dv/XdVJknqoOQmcGDKLo/t0EFsfA6XlY4QcAAUhpUTykt19NYg2VroM92QMflKAd/elxG7BNIgoZaM0M8NS9mYPdecTSfk1EeD80e5p8z3wQ61QcFCTGW8H/9OQi8k4d5WtSpni7wPY1N5AtQt07I4aZsornnr+D4AsnWZAZPFjQgviyHeeE0yHatBmVSto67ketNqIvsTnfLXgqIp3TbkCh0RJ8qnbgcvqKyTgfrlHVo7ITnIUg5UOXhwVyHZYamPDsY+tMJG+GYCB/9ZRd4NAwXlpLOZmvRWUoEXofVCdPNgcANpfOzozxSZnCgcHa7zm5J4wqh8xmZ8rZwkxlWuRZoHm0Dneda+j68IANMh4+SK8wEnqFu9gdyIWYFBFAai0ZHiuycPyuU5CWmPYDjoh9ChTRdNnCpKK4FvnhK5rMrqP49bQnIe/UoBAAAwgIAg0AgAAAAAAAIAAAARbHVjaWRlLWxhYi0wMS5zdmcAAAARbHVjaWRlLWxhYi0wMi5zdmf/////AAAAAgAAAF5FAAQQEQFEBQUVQUABRAEAAUBBFBAQFUUUAERUUFBERFEVRBQFEEAAFAEQUFVURRABEFFUBQFFBUFVEFVQEQARBBUBFUEVRVBBBFQREURRVUVUAARAAAEREEVAQEQAAAAAAA==";

const chunks = {
  "lucide-lab-01.svg": new URL("./lucide-lab-01.svg", import.meta.url).href,
  "lucide-lab-02.svg": new URL("./lucide-lab-02.svg", import.meta.url).href
};

register('lucide-lab', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
