
import { register } from '../core.js';

const lookup = "AAAEN4kZAxMYnhpCXZcQWE9TJHJCSINElSQpVWMyZ1I2hCUTg7ajhza0QlZGZHNXRKAXVyZjZ1SjWnSll2NoNVNmGFeWc0ZlY0RGZENCcmFTM3dVokcSRElFRWBpdBN0WKwCNAIGCQEQXi8DURsDOp4BBwXmBAQEKwSKAQEBXxABAkUBCfEDKgcBzQERl5oBBu4jjwHvBAkBEdSkAQUKZATIARUeHQMzHgYiBH7BATcHAQICeQMETgONBc4ZBQdFFqASxwKbBwb4CzAMAikjB6UDUAWuArEPA4wCIgYCpgEDPBAHggEICgQECQ7DAjQBDcEDbA0uvhNnFQEDBIIPBgwRChsmyAUIBtoBBwMFAlkDExl3CiJScH7Qer+KPd2E3ReVAHV1FAKxA08uAb+12KqXrzBWHvt6K6U/b/3hTRddOD+nJwEGjSiz0IYMdV47YfciKfO0SYyPnPQkbM4dTQJ0trNU2eCy7XXAkL5N16j7VwtLYWOTUg6Rsy8KMHfhlNHdnQAc3lnVK+fOM7Her5deK6IxqGMShduflyweRi+p5bxgYmoCIQAzcFyV5L3PtIGyhgSaAvxuTh7KOxDCGYIR0X2Vj4ERzyQN1wVm0NjZa7T2/0diSk9uD/Hj1IkFRwglOLRpJsMOA8IoIMTJgZg6btJ+psPV1Mt2i8dq7pwBoGsSunZTu+Vxx0fHV6TTooIyyxAuqL3jfw54vtsuwPll1xhTE1Z0V/MJHNvNQgELhNWAGGqlF9yNIvJXxd4+dRStwf/ghq1SBx1v7UkPwvIt8xeQylgQ1V0oJ3+GazixtJAzzaLyRsrbdmSf5zxmiIAR/F0zIxSrhH1BjKARGMo4wuIEKEYGSyYS9ev0NGWdlFIHH5inwnGZg7+/fFNXDyqBHMoX27LDW9RHqVCyb1NeEdgQEv7ASKK58CgR2hMog/F+hO9A20HFJ+5vzHdxREn6I+0FHlmJf8fgyz8whstlOKyH9wTQPBsy4U8FB9nnPJ45aSx7fxOYP//dnHJASFzHaCAOqFRPGhfGYO//n4zPwKG/HQC9ZrBu3T89X/DbcZB5+4cD5JEkACi5gumZ4ygQLsbuFcFzj2lS5/VBGYd4Syr6HEJ+0OrxdIEA54UzWKaGlrhcpJqpZb4lPmT00tYDjmtQfGtyeVbjvu/ZeQIH8IIeYOLpx5opKIJA3qjUWde4Wx2zrbsWTHXltD936Xw+o/FVyXsxpTrvlKsYCJZLNn3utuXfzyZ+dgVColoLxGQdlrWuHrnAiz4JfxbHYb4wJUbV6jlyYArdnfyU/A2MJWqBvpImXOJuwKKI95YcHwGv6IGWvtMZaBWqY2XPh3NcyiD4aYUQZqNxIrpgtWqlxcu45aQ4dZcG49twsbUa8RnWkOMHgHjd23IUli6jF+C+pG1UEAAAACgAAAAJAgBBCAAAFUMIEAgAAAAABAAAABhzdHJlYW1saW5lLWVtb2ppcy0wMS5zdmcAAAAYc3RyZWFtbGluZS1lbW9qaXMtMDIuc3ZnAAAAGHN0cmVhbWxpbmUtZW1vamlzLTAzLnN2ZwAAABhzdHJlYW1saW5lLWVtb2ppcy0wNC5zdmf/////AAAAAwAAASibFCSCoigAIkSCpGTBEGgZEmQQpiBRAm1YImWKMEmAIiHCgEFCJC2KkGwKNAmItkDRNmFZgmRCIE3KIknAEAzAAiVItm2Lpm2Rkm3CkkhZgGDQNikKoEgQMGWRlmEDlGEKFgWatklSEiAZokWZBC2LsiiAImwTkAEbIEgCEGQJhAxLNAwaMEgKgEHDMEBIBkgIAkEZJiFDoCXLskFIgGnKoCUbkCVTFCTRBmUIJCBJoizKMiHBIA3YAkmZkGzKoGBBskkbpEQaok1AsChCNEGShESbEEiZNGxKImBYICxTJmXQAGyLtmCTpikAEg3IpgmRtkDAMEBbMkhJIgDCEE1LgCRBAggDIAUBJggDpkzYpGlaEmBbsGVStggBpCiIgGBbkAQBoEnCAAAAAAA=";

const chunks = {
  "streamline-emojis-01.svg": new URL("./streamline-emojis-01.svg", import.meta.url).href,
  "streamline-emojis-02.svg": new URL("./streamline-emojis-02.svg", import.meta.url).href,
  "streamline-emojis-03.svg": new URL("./streamline-emojis-03.svg", import.meta.url).href,
  "streamline-emojis-04.svg": new URL("./streamline-emojis-04.svg", import.meta.url).href
};

register('streamline-emojis', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
