
import { register } from '../core.js';

const lookup = "AAABxYkZAUEYQRqud8OjWCFoRnRGUyMVM1NCFUaDZEJ0lUWFY1JIg2U3pTQ4ZKkyZwdYRbQEjgG8AQkSIDcBBgYHAR8DAS4BBAgqCgOvAgOpAQEEFyMvxwcuBAsoDwESNgrWBQps/AK0Aw8BbwUDIs4C+yoBAzI1BAJZAUG72WBt+fRnQO/7a3DF7vQYg6MBlezWHHXztc6SArrf4naaPLG1G+bKv6OWO0YTcZC37kY/HT6r5GAYGUOHAQaMMQ9K04fjYtr/U6ztRTai6ECszxFS8oEyAlXGq53z0IWMziKnHCmsNVD9LyGe43/fQdP+cDTPlV+PuUq33cfn2hs995Q/cswJqh3BUebPLKMG/4Hb5Uehn/jSh19+c1zaLXssSxL90N1EgLwk9ewKvsxgDmhpEXQb0RTzHLNLlP7l0YxblcCCNaOF8gtn7QflHD0c8DcnfvQSoJgHyVt6WofTMJwNdumUrRN1U/7XJmweyW2towYXq/dRefLMHTEyOUJjWVCjXLkJlbAdLcXSx3qdswOwEgOHc9f+utGDHr5YnAYDYO5NQYSZ2Kvt0nbQ5Hxil26pWzZsOPSGHtIWo3VJAKAgAEAQBgAAAAAAAAIAAAANZW50eXBvLTAxLnN2ZwAAAA1lbnR5cG8tMDIuc3Zn/////wAAAAIAAABRBBFQEAQUFBVARRAAQVAEBQEEBUAARQEABEFEQAQUVFBAAARRUAAQARBAEQQUEAFURUABUQFFQUEAERQVBAQUAARUEAEQFAUARQQRAQFBQUAAAAAAAA==";

const chunks = {
  "entypo-01.svg": new URL("./entypo-01.svg", import.meta.url).href,
  "entypo-02.svg": new URL("./entypo-02.svg", import.meta.url).href
};

register('entypo', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
