
import { register } from '../core.js';

const lookup = "AAABvokZAUEYQRqi1sCEWCFURSV1VVaVo0Qyc7ZEmCQ3RFU1Y0ZlUlSFZmNzRiV0QwRYPgI2ChsPA50EBR41DwJWBaU8Hh4aBmUCiioGKzEVCAQYAT0CGMsBBwYtAioDBAPNBV4SBQQBvgIpCQQQIAoLAlkBQems8B3ju34d8tKURN+QCWLfErMG8hnmzgJGoh7ouj2HLPNx/lFfF4fQNLnFBq11zEWGNttoNZS3lXMx5Mcd0kpL5VKjP3y5WM5BJFG8Le2jlkrK4nUpA4L+mYTuG6ODmGmqSyyMU8HREtfmoxgB83TtFDUtnc9yTfPdt/IcbaEPUK2+nCf+/bPH9WDkW0b/9HbRjNOrgEBc7HanZwGXQ3rPOz4w0Pm1YCYHxZ3QWpJHISILW/Rj5zIK5dqBnFVgzGD0hck5Efh17kDWvtHsqe6HqwdwA6uMDtd2Hh66/jyaMofSyWLZ93mVwEHaHP/MzwPlAmcGWYMGE2zGsbDTX9g3OIF7P9KHHFz9Em5TGxuebKxClONbbTagGPSFcJ8N7dqjFqsx79M9HKMRa7Avv48T3ZV/UAlztaP7ehx+rJX3HUlAAASxQAAASAAAAAAAAgAAAA1lbnR5cG8tMDEuc3ZnAAAADWVudHlwby0wMi5zdmf/////AAAAAgAAAFEBEUABEVEBAUFBEABUVEREVVEBFREQUAVAREVFEAAQAAAFQEAEQEEAARQFBEFQQAFFQBAAUEQBAUBEQAVVQEBFAVBUAFEAABAEAUQAFUBAAAAAAAAA";

const chunks = {
  "entypo-01.svg": new URL("./entypo-01.svg", import.meta.url).href,
  "entypo-02.svg": new URL("./entypo-02.svg", import.meta.url).href
};

register('entypo', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
