
import { register } from '../core.js';

const lookup = "AAABwokZAUEYQRqYkkbCWCFXVTNSRERpgoZpZVVDJiFmM1OWVzhkRbSGcjZCVCRURwZYQtYBLTYJAQQnCQgCCLgIIQQ2UoEH0QoOPiYWARJLHgEDFO4JuwEPvwUDAi0RAgPZJ17TAQMjIgQCFAsnHAEIQBUBTAJZAUFKHoyfrP2wHPRjGxywnlzpMjigPi2Syf5GlM8xBiGsD9dfRcXH7R7G7M954/cdQczSXwmjcxIn0B3+c5USrQPOmKFL89O3adHX+HUBgWirEeVckNB1v1Hk2gGF7lKDYLWdenSHJKMmhcxgUz+GvNHYNESUW1ixA20Y//RNW6Od7dpy/6IUNXVbYg1+nOiE9IDkvgdG5oOVMas7YlEG0vs95d+C7rlgf9LzoxlgIsBuo4yj9Up2PQcG8KM/p/Jw0/kTei0wQ8fz9By1Bg7KdrsJltDZcBxxHWcszBML0jkDfB5Aa8lCEX4y3WcbQQL+8pqtPIcK8jVH5Sy+j1CMN1BsHAIv7OMYQJzR3ZXOVWyBq9ZaWVOpl3YXEtqzrLrvxTY2e7fP97nn/tOrum2Hqu6ZlEsdwZWzh4fb5v0bFini3+1JQAAQOQoAAAAAAAAAAAIAAAANZW50eXBvLTAxLnN2ZwAAAA1lbnR5cG8tMDIuc3Zn/////wAAAAIAAABRAFRAQAFRUAQBAFAEQBQQQBBEEQEFUAVREBAARRQVEUQQRBQFEQEAAAUBAFBEEBRBAEBUAVFBERBQARUBAAQBBERAQURFAAEAEVQREQFFAUAAAAAAAA==";

const chunks = {
  "entypo-01.svg": new URL("./entypo-01.svg", import.meta.url).href,
  "entypo-02.svg": new URL("./entypo-02.svg", import.meta.url).href
};

register('entypo', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
