
import { register } from '../core.js';

const lookup = "AAADBIkZAjIYcRrvk7X+WDl0Q0QyZnNGW4NWMyVWKlR3JGS3JUSFR3VYOYVTYyNmhCMzWlEnJmVDWaJ2JjRjQXZgdYZkdDVHdAJYdQhVBg8GAgJhCwQ4BQXoBQLMA4UBEAgPARwPsRUIKl5fBgICDm6iAwoIAgwG2gEBHO0BkwEJtgcFjQFfBQRDA1UEBqMBAQJeGgJTA5wBBX8M5Q0EtwoadTMDBAYYkQEEEcICHBeUAQyRAgpPJRoTA6wCLBFPAgJZAjJbczGQMy0/vNphv6gqz7b3VpKiykKTcOI8pJ/LXXvXA/HS/RvmUiEujEw+ItVeDvd7uEnpIWELSOqMAXLiCVPav207vA9Waa1KtuuicUnJQH2VJ4r55lfC0Cod+TNErOeTNTUyDwO7NgqfDNfJG4AvVtMxMJbrC3viFZgcwdbEdzCmSZdgStU4ZKH5/MWUr769abxRGrCWQuRryNjvhjfYoMjSrvMUasFDF/t19D4FLdcwLwkC0/mPOP+rUyTDnXJOQL3sjHvzJGgRxmyEgy47K3Z/7ux77PcDSThrKBa85sySHcQqlnMHIjwRrt+x6RohaDTUAfNPyMBt1j8ney0dnR9LJbricMVSaCp+I1x6SFyTrOaO5CSS/ikd6Aff6zseZW70vqcBLO+2ZU7YgZ29TrPryHqDEe+BEgZ24m8ZOVBCS76Sv1/lOb3uafsMwVQva7V+vlDHP6wapbQMLSgORxoI+otg0r0lBZC/IUA014w2m/sZUx1tcWnSYJ+/SIcfhNbAEucJAWyV2kc/1x2URg4Nii13BqfoOV/PtvaQ2/4S+XGV4hLauSqLWxGt6uaHup4Lf2wdm7e5aQTHaweGXAeCSYnDHv7Xs606XIHhB6xcPEaHNKGZ+g2Ibr7Jz50ryHtEZQPVgynH8nRsC/FBrLBND+DEvCHmfrcGQxSwJCHSC+Z0I8sfd+RwNuDNPLDfIEo6DoTy2lapae+TxZE0g7ExJh3+BxyLKQC6mCyMv11TT0AAIQiAAEAISkgEEAEAAAAAAAADAAAACmNpbC0wMS5zdmcAAAAKY2lsLTAyLnN2ZwAAAApjaWwtMDMuc3Zn/////wAAAAIAAACNIQYQRBUESpYRFRRqQFFmQUGmFZAghFBAlRFVCQBCVlEoYSYgmJCqgAQFoERmVqGYgJBAGRWBQipKmJAmSCBRhZqUloSEkBZZBWKYgVYpERpCQZiUaalmlAloYZiFBSAomQBQWQpRCYGlYaVGBElFFAkEiUFpiUpApghpQgkImGRmGqiaJliaSmCFWIQAAAAAAA==";

const chunks = {
  "cil-01.svg": new URL("./cil-01.svg", import.meta.url).href,
  "cil-02.svg": new URL("./cil-02.svg", import.meta.url).href,
  "cil-03.svg": new URL("./cil-03.svg", import.meta.url).href
};

register('cil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
