
import { register } from '../core.js';

const lookup = "AAADBokZAjIYcRpnSRlYWDkWY1NCc3Qzs3Y0OlRVZEFzYzp1NGd1eQJzQ4NGVEZFaDhHOCUoW2ViR2UxQmRjFXRUlUZHaWM4RApYdxUCCAIBAQYDMQ2WBQIUAfoxDXwSA6UIAwYyGgcGFAMBVQL6Ab0uDWoOAZQBFRn7BeEHCwIKPAYSAhBJDAQwSwQIkQGiAQKJARrIAQggAbYEARsVMVcQjQEMDLgCGT0DAgkIHAcFE/AOAhZICO4EewJoIwUGBaAzAlkCMpG2yEmEaZXrERnscYGwNenyIaHSyEvGEse/bdOTC5IlL4qdc07SramM4WiGkw+TUx3ECckXCtX7A/kRlLc2QnskcOQdLz97g1DKOB0umCoaHLC+9GW//Wtt678M93uUkpLI85/IYSpdO1M/X5ZIVozX2Mku1yjSCy0d9KcGXeQSXNgtPnpkxbYbrLfmPLHqpdsGZTQO4v69O1yQaNow3yQssXHTuocgveamK3KBSIt6e3EUaj4LQDafaYQPsyGs16xOAD8UQsOvYG4DdGBcGRrDKZ29PB0kgOeVW/GwvPoqv32JxWyou+/7wSK86g53OFSHhuTvIx5oJgXPpE5unrTm6AUiwGxTL3bmrdravkNSV4wxPE3rOkRvB5/uZexWH5sOSrwBvjbgv804c/K8Shrvazza5kNr1UKdgvrMrL0E1gMtrTdAorpworM5/Eo/cAMS8cdJLIyB1l9sRv4V0mkdCWwprsV/9x8G1tokIZYw+c8Mls+MB2DmabgnwTMbdJvSv0vBKpd2uo69STQLncRtKxFWtlCuFsgxCXcdh3dbg0HvQFHAIb5+DYtJH2vz4o8NlbnXx+V1e4SDmFwdfxFGOicq8y2gOyhTRAeK5997gwd+whoPXmno6eK+mTKL+Qf+9yVWCDEj4iFp4gdSkn7XAWEOSDX+kNVMC+ApScTi2BwBrKvs61zLNPm5T0ceLXICkAHU/8nL37X5DNCItjCTezmh9jkzEqf75rDXR+4hvDRPAgAAEAiAACgAQHAhAAAAAAAAAAMAAAAKY2lsLTAxLnN2ZwAAAApjaWwtMDIuc3ZnAAAACmNpbC0wMy5zdmf/////AAAAAgAAAI0UUqZYgQVGklCgABFGpGpFZBJSAQmQUEoSghAqCalBIVapGoAaBKVhBRWoJRElYJJYmYKUqhVQQgIRhAoCUpFGBVlFRaSkGlVYohkiKJKAUlkAliCKBkGWYFpEJlFUSUkhBCGSBIlZgYZqAhZJkmRRIgSJJKSpmApUgRJpghYEkWoSZQYJURpAQUAYVQUAAAAA";

const chunks = {
  "cil-01.svg": new URL("./cil-01.svg", import.meta.url).href,
  "cil-02.svg": new URL("./cil-02.svg", import.meta.url).href,
  "cil-03.svg": new URL("./cil-03.svg", import.meta.url).href
};

register('cil', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
