
import { register } from '../core.js';

const lookup = "AAAFcIkZA/8YzRr6h+jNWGdURTRYNVWjMYZElllHYkFlhSSDUHaDdVhXZcWFVHZpM5uGtzNFcocoUyRYNyZhVGNTMyVYZkI0dVVnc1NoQUQSYlVIdTSSM1ESZjNyN5hEeGRHNUOnhFFzNzRkRnVjcnRFoShUJQYIWNoHGDkTAggUIQIOoRACzQHXBwUKb+8IrgIgHgNTDSJnDYcFAwEQOiGVAi8DoAMlMCUJDBwODYMFDZcGARccmwGSAjMDAbZwtQI9zwizAqdpAgUMAsYBkAG4AuICBhYM+gMmCgEILgUXCpIBAgkBAQkCxgUpDxUBAwMrngEKMeYCDwiCAgnnAoYBGgUTARQRBNYEIUwECZcNAgYrAT+4AQIBSvQBBeQDqAQUQw8QCn0HCgIJA2XlEAhwBAH0ATgKAWgPDzpUAxkC3wIEjAEQAtQ8kAICASEJAgPHBAJZA/9Nt1NqCcIGGP2yjtCTCktbkL7gtRx+jti0j1jQh/oEDYNj8RS+4x3+5K2jMc9ME7sUAbbXPvDWNCdHVJJrL+ZjYXjJI2z+6HatBkoGBqp0MqhDWu5IR2yp1IzH6urvr/QGrr3okqVEy6fS5KwklRcdRHf877ppvtmJpiUhkCWl49U6quZNHATGqfy9IFTnGm+X51ZD5xY7jxOJC3QbuO3QvWDm77X1rVXmkuQJMfHvVDEQfEuU//byahEXkj5ErQqgVx65MPAdZXC0lx/ieuAC3rse18Ti56Pp5CmgOxZcRO32B9Stkx2pkzJTGOW0QBBplir5DzLL4B7aqEhEOAjv9EUA1nd0G3enOu+Ze77H8dM+lEY2Ts4leYdTIJEi3SufAXO9pOqh6MSHr6ClKsfxipfB68M/h2Oe3KlQHYlLe0dla80IjtIRh4mvOFjYH1ZwgvKF0W2wgdjjrOk3jAfF+7253uEpWJegzxWNYtjQBn5LiexiPLryxbVw5FqpNJ72mTMaN5lENuSflpNbQhgrcoOy0wk1S/YeBS2Doq+SsQ+yEhY2ulNxVeWoAL7B7NLWCCH0fz9gQXJeDJsnHWkHOwg+yvLY7XOhF5fEnmlRtayCUlAl+wXMcBPwQISgkMdioRLIBl3QtafX+dWzW//jcdEUu1uEMHdgIIsq1bwJ8XVBvZOQ7hkxzLuj5zskbda7/oseaq3q1OzacntW0r4GG03V5y04IBzG+88d/g9bp1kb9CmlMbrGZznhZ9BFH4MR+CC8JiQ/xHU8+K05joVnLP5UnAW4YMZf2WTASpcriGy2a7PsccFdG2/ywhXa5o4cI3cgSakiSTNekd5MOSfGd+fW1vlQYddnOyE+EkrzKkKQK9ajerbG963FD50JRj305iTsztCVcJgrvZYRvCdUDFfzv7BTq7NMm7nuNoGTrAqiZS5vBvrVWPpmwaMh2Z2Lyx1si3zPc9U/zsrxgDQI4xXabXsCvye5zFvPhouBT0NkGphzQCiBiqX73wyEg2QvqDVomwE8NZzJwrHWkjDdZm9JM+eLub8EqvXc2jh6d35DamB9lORhA4GVTs98fJM5xf5xJLDAJJtGW7itlqXdKv3x1yO4gkhmkmophXa2aWBw7ygNboLyAx0665aIKpLg4q3tu/OkeqPMtBilp3gZ+U6amwc+R8deHrgTdKeTmVxaiEzOVTjyovmBVpaB/XqVw/tgh2PtyIEXgCLSG6KCJZUROTKDf9C7GfpMeDAsnPlFkfbxtRgXtXlCIwsPvTUrkYKW7LsCMrwnj/LjsHCnsQRrDlQXYOaHSFa22xNmqYAB5ap+qS6fPkf7WGncxQY4z/5S1nHinnkqQSZYKxlYGghYABJAgAAAAIIIBgAQgMQgQSIQABAKAAQIAAAAAAYAAAAPZmEtc29saWQtMDEuc3ZnAAAAD2ZhLXNvbGlkLTAyLnN2ZwAAAA9mYS1zb2xpZC0wMy5zdmcAAAAPZmEtc29saWQtMDQuc3ZnAAAAD2ZhLXNvbGlkLTA1LnN2ZwAAAA9mYS1zb2xpZC0wNi5zdmf/////AAAAAwAAAYAdpSHYugBjGIajQknKxBHTCC0iCQ3ZwEgbhIkbIioMyQ1EggyRFmmIBEyEKIFcoHHjhIxcJoARxigAGClhCLCEKJLiMEpsoilMkiIDOQ3JQmkLpwhiAmgbIi4JlgQgKYxTGAQkhGhSNCaEBhIBQCoklwAYFIULxwDihGTYyIQIEpBqgEALQ4pICIniMjFYMIbDJjDhwlEMoW2TIAnYgCkIGFSUJgWTCI2ihpAAOGTaIooYQEQAsUQiSWwYCElhxm0TtA3KxkEcJjFCt0kDAgbZACTQCGDklmBQEmighiUaNyBQWDLRJmJAA4Fb2IAiqCkTQiHBggBQwkwACgkbpKgTNQFatmAKGAmKQi0iOYQTtgxbGIoMhEkZQEmAMCbZEnIYpFKRqEUjF0jQIBEQuGAMC43RFpIURUkAtoVC0ACMOGETUJGjxiWZyCRBxCUkRAIBk1ILNkpMmkRCtmkAw4hIOAoUl2XJlkGJOCLKWI6oGAiTJmLKRC4bkRVMyUhEGAkAAAAA";

const chunks = {
  "fa-solid-01.svg": new URL("./fa-solid-01.svg", import.meta.url).href,
  "fa-solid-02.svg": new URL("./fa-solid-02.svg", import.meta.url).href,
  "fa-solid-03.svg": new URL("./fa-solid-03.svg", import.meta.url).href,
  "fa-solid-04.svg": new URL("./fa-solid-04.svg", import.meta.url).href,
  "fa-solid-05.svg": new URL("./fa-solid-05.svg", import.meta.url).href,
  "fa-solid-06.svg": new URL("./fa-solid-06.svg", import.meta.url).href
};

register('fa-solid', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
