
import { register } from '../core.js';

const lookup = "AAABl4kZASAYOhppn1HRWB2SVjVRMiJTWCWUEjVWZHbEaTV1xzZ3WDNUYVBVs1g9ogYMCxsEBAUCFI8BCA8F5hIBJgkqaE8cAfyoAcQJIwIC2QHgAqACrrQIawS9AnGcClIDARMHFAYHAgK/DAJZASAscEkwc9d4nJ2uz9q/ABuGrWmVgn5Avg5ZeoM6cyz3KBfC2MnXSQ6T4p1qnNOYnL++GGqwVR1b4UjPlls5rEd75WhFjzJS7yMWZj/y5r4zNi8GoAGFzJROu7fClbPyYt/XVP/LWBTtuoAXf9Fj2d7tVKnmjZ4dqXF5h2ktO2bLQtjiOt6r0cp17eCoEx1z01eRSZ/UB58ZHr8b8InjHqWQKrvJqOZ5U01BVW2USVdgcBRDsFl7GB0VZs6Wgh6+ZULPBwPAW0oMdNmRko7MU+MK1s7Mu8wQlKCwW62fg9GmISWufAWm0xE/wDMsxhSi/AASao8X1rMbh71T7RfoJ5DjevP074Iu8tPW+sGfOz5INMfMROKGopREt9F1nlQwr1FIQQeiBAAAFAAAAAAAAgAAAA1jaXJjdW0tMDEuc3ZnAAAADWNpcmN1bS0wMi5zdmf/////AAAAAgAAAEgEBAQRQBABBQAARBAAUAAAEBVEEBAEFFBFABFAFBQFABAQQAABAQEQUARAAAAARAEAQQQRFABVEAAQBBAEQUFAFFAEUUBAEEEAAAAA";

const chunks = {
  "circum-01.svg": new URL("./circum-01.svg", import.meta.url).href,
  "circum-02.svg": new URL("./circum-02.svg", import.meta.url).href
};

register('circum', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
