
import { register } from '../core.js';

const lookup = "AAAEtYkZA3oYshq8c+lfWFlFaWRYU1UWdVRmWTgzOEdSgkSENFQmRBdmUpMzdUNSwzGmY1N1Q8RFc3VVRkZCYmZoVYUYUqZlMiM0kkJXVkWFRbdCRVFXRTl1NVZzViRnY0JlR2RkFWq1OVi2Gwv7AgMoiwIFCBEKFSQChgEDCaQCAacENo4BAwLQAY4BEwFWA9kCBCoRhQEFJDAECi+QATwBeQKyAwEBBUgIAxGUGgUapg0pBwIBswECKPu+ARYBqgERmQEIBDsGUgQBAj0zT4UBhwEDCwN93gICRwMpIVEMBQEIA9wKAQQSRhMaFWMFD7IBWAUBPwILKgYzChnZAiAGEQSkAQoFECNUCIwCAw/BARIOAwkDAyXdd1ol/n2hBgMCWQN6zWtrfPFZl8n4Fo3cHRAMeLIonbIFn3EaHPE8BVa0uzlSVFLRSzTQBHGCmnJp7JTrG67OksCQZwFnC33sFLpayQCm8wH1DUDgjQiNk/Bo2pYDFyuFSsegRGuVwkts78a6aYGdqjaNkfRNwoPupdfZtm0cl2Qvu0c7el3t48XlLjkIJedW2jAO13e94W1K/ds8phMes93stfzgkOdvOj/yV0Ecl3FMKaMTwdvQ4BrzmeOdHPG6Iu3rfZqOmJ26pgn1C+O+Zi7or1oZlpAv9rBxiuMu2Yh/3mE2Q0RolEVzXZgoIbESIhcbZjw/KRjlFf80xadE986689PMSMbwjNSiauRU2/IE0TYfh2cskI0j0Yq8gpgPbnpAdDqJCmOqy85A6vSq+cpID9+ealVbaNsotOmW7VKKZqJfQ5VsKEYoSoAkVuDWDUkhL921kodPzqPemsEoyVixaOkiwC29JzSzrxy7GoysBu3f5wmS+SqZiGFE6Usn4oyJgHXmL2X4rGMMpOtf0VyxvvBMmtMTehDGaXLPg+OY6dsxtIOIsJrhospJzpiHka+xeQ+bbKiKXA0UcmWDwb0rwBpTUPM5ZjpCLrOjCcz1hY1bhVClc7YFFAvu1kbwt1nDYQfoKjUO8OhCxeOuA/1U5MWk1qePFxKBCwn5VfidXxCgU8+VcWIsTJb0aqGPfC2CKxMAlPuoAQWkhSumMxL7kfOd1oJcJImCDHJGxVBT60Pr33hUgqmwQI8fbDcyMJ7CpFUFf+/BKRm0Sn36Wpa8qjuGX07uL3kihnKX7tOkXE3KI/WZhweVA0/eKzs9x79MftjV3M8dd8iHzWd3Roi+vfyhp8p73rqQnPX6sh94UKtw5Vx+GnWNsE998hKIGwztgL2vDXNkdYi0igkPWRG89/LlrOzT6QEcya/jX5jlM3a4jkLSit5kIg31cRLqfGYIbQmciLlpXUETEdaCoVbnwG1pX9K5VvPaHvbPCIlSItfn/1abZ1JewCWa90+PIJC3Y9owlN/YFrOspnZIWyUldtjGEgA3NFqJpY3MgOQuwGPhgJYT9vUGs7cTyVV/tYhpwcajSad/y4qNrInKMdPiRSGvlpilyzEURHzgR1Md4JByUC4G9Rep7uF/Fpfl01OT6NXWU0NCEz2Kc53xY4w6181y5iE6DEXVXvwU50y9n9fRzoJXCCAACcCIAFARkAAIgEBQIFABQAgBCAAAAAAABQAAABNmbHVlbnQtY29sb3ItMDEuc3ZnAAAAE2ZsdWVudC1jb2xvci0wMi5zdmcAAAATZmx1ZW50LWNvbG9yLTAzLnN2ZwAAABNmbHVlbnQtY29sb3ItMDQuc3ZnAAAAE2ZsdWVudC1jb2xvci0wNS5zdmf/////AAAAAwAAAU7DoA3TBAEYEEDYxIijlFEKBWHbFCScEgwbNGnQhgxJEkwCkXAcJBKZQAWAMGRbsCVCNkRYtmCQAAxLEGhJoixLojEQspEBhnARBCZaAkAYpIULRgSYBJATGQESxGWCJESItAlaFijbhi3ZiEyalAWBBkjhEFEDkyiiAkWSEC0EoGlYtAjaEIwUhoADpExDyIDTQiFSJg0BA0ASEGGMsGRLomQkxiUkJGlAME2KFhGYGIzAkGXjOHHDFAkUQXDgNgyZgGwaQwhbFkAEhwXBMmXIhmCIRCRKBmVZomUZtykDgiWklikaNwyKImCJMgibBC0MEingNgoSGQRcpFAaAmqioEFAtklAEgqRhmUDp40KsiQZFY0ZQDGQECXCBEUThgQLNkUSM3GJBGUAshBJgIlCEGlKJCWShCwSACQIEEDTMmVSJpEByAjRMC4hNAUSAAAAAA==";

const chunks = {
  "fluent-color-01.svg": new URL("./fluent-color-01.svg", import.meta.url).href,
  "fluent-color-02.svg": new URL("./fluent-color-02.svg", import.meta.url).href,
  "fluent-color-03.svg": new URL("./fluent-color-03.svg", import.meta.url).href,
  "fluent-color-04.svg": new URL("./fluent-color-04.svg", import.meta.url).href,
  "fluent-color-05.svg": new URL("./fluent-color-05.svg", import.meta.url).href
};

register('fluent-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
