
import { register } from '../core.js';

const lookup = "AAAEtYkZA3oYshoETxgtWFlpdyNqFDR2WYZkBjZTJ3RTEkZnY4ZIJlZVYUFVRkZmQjlVOSM6eVhIU1h1hEY2NlZXSDJFEzRzRzVlR4RnU0SaEaKERUYlU2RkSXSzVYNWhyNCY2Q1RYVEM1i2hgIS3wEpAvQIIg4LAYQBaSo5KUYQHQR0DdgBEwICBQjnAkYCKXzoAWwKPRMtFikOGwcMWwFnA1AOAtYSAlcIvQEVAwGvHeoGJKgBHLoBBgEEsgMJPvcBB8YEEAkEDgPdASYoCNYEAiUBBAO8AZMBCQoLmwGvBAIDwgEseQYBDhe5OeAJ3QUU/gMBBQ0BFgEDDBcGDekHBxSCAQKqEhEW4AJVBz+nAwcOBCsDUgcCDwUOmwIIAgUCWQN6v+ooVFOvvX3sHOLAiO783mfYr4brIub9L1JmZ6o2L1Y6wFNCqPX5lJ2QoFsMkUyIXWEpKCXsPe0nFJQclg3b5bNa3ar7fLwUs+VSWmpD1ppksoCPSY2jzFRIC03o6eyY4d0FpwBVmQj1SvQP8ZbRckA/XC4D1/qX9wnbaFBZx4g8+IKdztSVrJrhfEySE2+QtyCHOgyAO4DeqZoa9Zu6csA8/EFH3kTnBjE7hQu5IfpwfeuIAaEvjYIR3yiCCfNLFQW8qJiQ3ussHNrPbAmed1LS1YJxWXMbhvAcVt8H/MrbIj+C5M9VM8pmoXP5h7E0ogxC017W4IgSMNra9ZfXc0rlSInTiUxfK2gxRXF5jHYTbVzF7pRpDOMP3EOB581/L7q08vGF8l3kg9NXkBlnA+IJmc5xEvVmZxMFYWnfWi6wHLvLoDRVUETbpPT412NDK/KKpbfW41bkuudkxlquOgfzIVKj8B3txniSbHZiDpHq9v1IMrOHFO96LqdTKBvCwcntLiIiw4hQIsyPfsDoM3IarzZfo2bWCsZypoox0q7WTelSRJZj9uN3mDu00ejxmlM3DUDXipZcE+aNbbsBLhqkH9WymoFPiGwr8JnzicvwZCFYr3XOnclqxb6UQXVfnX8pKbrno7LO4PBbg9nNpiV041ml+Ym3JGvsToL302k2jkR7taqppJXzRmeAvVDxf0mY88oLjSR45yJo88Gz6LSslQa8MIKnaZAff9rJJV9r4FMvkGZ8XY2Kj8dxT6JxEu4jlvVsRmXLeX+MEnK9VsUFFkTyAFSsHOkBohQeXAxQ5yruHaxGvhr2crCYkzWO+JglhV6XbY1HtdOcBhPe30zC0fdLS0rtmtmPdYgUXwTFiq8D7cmRCIdFnWHIps88nD2JyU+NF6TWOZM5ykBqVQ8XmLSfuuO9Da+DwUqwYzeDU30w7uNAjZ1jsX6WKJU0DnqKEBbrl+C45Q1CG6bhQ6cT0wvbabYq0NXRIwiW///pxrG9bpty0LWxpYxPOjkupdhCoXNUIeC5jC1M3HrgEI2kwOWqeNEsAMUoFgmdzpd9ih3N6QW92M8ZiRH0weOzzhBokBOeSQhjRhrAuydp9b4SbWu671/BdrCrVh80gKblOi22rB7K6xNlzPsXig0X9QHXhUUS4SvGK4KStBgJXARWfMJbn4dxD3dXIAKgGQMgFEAAAgAIsAoCAAcIAAQGQAAAAAAABQAAABNmbHVlbnQtY29sb3ItMDEuc3ZnAAAAE2ZsdWVudC1jb2xvci0wMi5zdmcAAAATZmx1ZW50LWNvbG9yLTAzLnN2ZwAAABNmbHVlbnQtY29sb3ItMDQuc3ZnAAAAE2ZsdWVudC1jb2xvci0wNS5zdmf/////AAAAAwAAAU6QokyAMmRTQmkiA2ZJxg3YBgqjIG3ipGAIBDDKooGEoABcgmRTRjHUhoVSRkaYhGFDOCwSJkGAMgxBNkEZhiTRtCXZmGTBNiLSskjREAKgCCgRAmAABnLRJgyElgTSNggblilDsiUaBYKasiybpC2CtiBSJkGhIgiKsEgIsmRTloAcpE1ZBCKCogVLoIAZBozDAo2RhHGRtGlbJmWIMiiAKAxZIIkLmG0DBiliokDAhAnYgERAKA7cxgRLIiWaOCVChGAQqGWLIAzJIiDhMAhMtGAAhmHglkAZsYRZoHCLpAkAMhHMgAhCggBEpC3ZAoGbBCSExmETNEwjiG0gtSXikiEBpkSYGFAiCWBEhmBZFG2KxGQCAAHMIAGQiCwSiSgSlE1SJElcoAhblCWKMAnRhJEikhBMhCEghA2BiCVCImZjEiWUQmkcIG6SIgwQAAAAAA==";

const chunks = {
  "fluent-color-01.svg": new URL("./fluent-color-01.svg", import.meta.url).href,
  "fluent-color-02.svg": new URL("./fluent-color-02.svg", import.meta.url).href,
  "fluent-color-03.svg": new URL("./fluent-color-03.svg", import.meta.url).href,
  "fluent-color-04.svg": new URL("./fluent-color-04.svg", import.meta.url).href,
  "fluent-color-05.svg": new URL("./fluent-color-05.svg", import.meta.url).href
};

register('fluent-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
