
import { register } from '../core.js';

const lookup = "AAACP4kZAaIYVBrMqtQiWCpDYmdUYmZWikJDJIVlQ6Z2VSN1ZjllNYNVJWVlVVZEJZVYVBdzNEQmNJRYUwEPOZMBBwQplQFBlQEPENUHxAEaCA1NsgE4BwEMJ+YUERIKFAcBDD8ZAfgQAiBJEQFLZAIFAjwkISYkFS9QMCMCDifcAzAiAhoLsQEHBAsCGAdvAlkBohJncIv9nnZ8cglh8pn0eCNTHN327bx6xVoCZPyXkzrnXGmv5XDWCuhEHC2ncOq7xr+LOmNvTZJLi27d/yDZCuubo7ceEMoSYY/fhnhC/mXGb4U2KQjsS72q/fURxGMLMQKj++sX+XfmuPgbp4w/bMqcr32vPGINx52edQYSuE/Olqtg+Rz1S4SEVBQLKVasNfoMFpJFOLoGkxvsBIcRsXMjRuCqEKZ8I/g3tpv7i6EKoHjYtDEGKBMJIQLEi2CvfNa9fFTKc9tZdx2HxzckdyYQryPI3FLkmZpv/9wkgAy6DhxBAb1MhMZHfcH3ZunozT7bUnr9yklZ9PgtOAcKea3vMkDEupYnJ6QxYsDL9Gf7QDM5sI7dXi7wD/NWRWFYnXxsNb6QR8P1QBlbda17SdmOLFWRh7SflPmYS6GTpFDlHMWL9YbP2WuH9uA3ZtMl8jLs0CxUjXJtPMak21wF+Fia21K9Drk+xdr3Yr7tW+91sCePZdzofUjPv5Dmfgf6phcfAeby/49chcVAs8A/r9bIOq5kkiyfUvJKKeRybQaQcndLBAElAAAgAICAgAUAAAAAAwAAAAttYWtpLTAxLnN2ZwAAAAttYWtpLTAyLnN2ZwAAAAttYWtpLTAzLnN2Z/////8AAAACAAAAaURQBRUAQJhhVQURBQRVQUFVVEEFQhFQREQERRQRQEBUFQBAGRQAJWglEQBQFRBBUQAFVUAGlZBUFRUVEEBEAQAURUQRVUUFBVAARRUZFFEUEBEQRAWQIRBVURBBRlABBgQBUVIREVBABQAAAAA=";

const chunks = {
  "maki-01.svg": new URL("./maki-01.svg", import.meta.url).href,
  "maki-02.svg": new URL("./maki-02.svg", import.meta.url).href,
  "maki-03.svg": new URL("./maki-03.svg", import.meta.url).href
};

register('maki', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
