
import { register } from '../core.js';

const lookup = "AAABoIkZASUYOxrN7gYEWB44M0WIRyRDSCY5NZNHSVVWU1NFV1VUczk5JkJGdAVYQH4DAwEUDtUCjQVcAQQBB5IBDg2NCgEKC4gEywMEvhEBDRN5AwMLASMzIs8CBw8MBQYVyQHSB7QNEUIJKRQMRwQCWQElZ+kX+9oPaMtC72czsSZpeXPXMSXcG2AbS+Z2A9e/S8a359oe23itB+OshNTEvJ9/F9On9BRpeVGbsV6Uf6/zQd6hClY9DTK/mdxsX6XwzFh8LAfq1HDQO0ey73X5Ss7ZtstpAL5+/Jnfnf3HcdNjnof+qBXSzq25lVQSCgAudfn+V1KIFY39kA5kb/ihCac0tTmsCb4qx8pJE/eswW0hG6UdyHpasNYCu/grg0mfBxf0dUVeuyeGCTMe4SrCsG8INgZa8vLmoFaSrhawNpVQh0/Pxgb0crQRfuKKvXBGYFqXGKCDyOQmdBDAHW2nx6JyOVPTelv4AYO4JbfJR62OlhTYLX85AGGP/JVToTx6aKbKOJ1zp7kw2b2U++XlXMdbGY0RgxJIAAhCAACAGAAAAAAAAgAAAAllcC0wMS5zdmcAAAAJZXAtMDIuc3Zn/////wAAAAIAAABKBEAQARVBBFFEABAAFABABAAEFBARFUQQQQQAAFAQBBBRBREEARAAQAUBBUQFRABAAFABAQEQQQFARBBBQQAQBAQBQEQQAEUAFAAAAAAA";

const chunks = {
  "ep-01.svg": new URL("./ep-01.svg", import.meta.url).href,
  "ep-02.svg": new URL("./ep-02.svg", import.meta.url).href
};

register('ep', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
