
import { register } from '../core.js';

const lookup = "AAABnokZASUYOxoMTzzPWB6ChDJUVHtDWSdIdDdrM1d2ZIYzEWRQM2REdEWERQdYPp4DBqkCAQECDB8C3SV9Aw7lJEWeBAgb/QIHApEEBAEBRi37AQQ1E5MFAwIBSwgCAgQbAgULJCQJAagCJrMCAlkBJe+2RYpWYJ1ayGeHJtvlt/i+u7u3KlFLg874/npyDvj8iL+nG2mfMaJ/5Ae102isp4Pe/TCDbY9c+cmDKsGNEMgIK39k1wGU3FulG9QArw3iPB5GCRRa/Oc5obh+dF6npwDCE8etYxfLlVMU0+8X5v1zHbn+erxYLgdpsLKwylu98idTXpDLfBYyYM+EoC1/9Nx2VyVHLHWux0mX9FDH31qSEqjlCtl1xNi+QfPO+XgC+5sGmVQVtOlwxur3Gb3SrZ30JobZFZXyoZk05o2t+3mxHuM5n/BLR3I2sGw7CWgzb5RhoMA51nMd2lKsF45vv4dK2gPQNmdP13WhuVbGyqas03ohbdRJlbERpRHHMwoAOBhfzEI9CQYblgdxD3554RJwaZ4lSAGAAiDABAACAAAAAAIAAAAJZXAtMDEuc3ZnAAAACWVwLTAyLnN2Z/////8AAAACAAAASgQQABQQEAUFARBEQQAAEAQBURQUAERAEQEBAABEAUFABBRAAAEQAAAREAEAAFUFBAQEQQVFAUAEREQREQBVBUEQBEABQBABBAQAAAAAAA==";

const chunks = {
  "ep-01.svg": new URL("./ep-01.svg", import.meta.url).href,
  "ep-02.svg": new URL("./ep-02.svg", import.meta.url).href
};

register('ep', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
