
import { register } from '../core.js';

const lookup = "AAACFYkZAYEYTRqVXUckWCdaYlVyJYd0VUJ1VRRUV1lEhCRSRjU1MSVlhoaRgnWCYXYlVZhlJQlYTrIHDAE6KgNFIZYB/wkLjgEFJwGxAUVHAg0vlgIFmgFFFQcRMwgCAVoBDQ0DAQMBHC4aNVtOaQMPwQMBuwUGQgINARBC+gLGChy1ARaRFwJZAYHMl+Ybh+LshvIPMJglXJJABfRUVSYEyRnjELEcyAHMjS96O6E55rXbtmmTUX8VsD/QrWFR6JW+FYWMSq9VvYipA2fraLNl0THEp+4RnSEFGG0Wy5bElS7RMO1ozzosIqOZHD4y0o/+usk9s/JZ7KwHbMOsLAJgS3QWXdbD2Vj5c4OSnv2+Rkr9j9NggluVCV/rdTMS+5w/mHJqSDse7QxJub7WF7T+gb/yQHKOL8q/vpX+gRdkLWvB6p+Qm7Y48yEOpK+/cuaCGZW6ZKxmzJUP96moira9fVDBiGwyqR6MNi9BIIINXiqmaQ4QoI5cjxDCGeoUMCqQzqKfhViW24u5FgmFUot2UY4eRZKnBawfxaupCuU9j3VtD07TQntJc+tBUbBs77ePH/uOoKxVF1UFZfK75vAcM7qcUuI5sV+QYEnklxYHvzvFf51s/ULBwbJ6T16jQmsJAtVHfnp8rWP2Df3Xr+QDac8XIvJsxeFEd89yqbuBlOXWUD7bHFbkYqUHSkACkQAQFEBEAAgAAAAAAgAAABhoZXJvaWNvbnMtb3V0bGluZS0wMS5zdmcAAAAYaGVyb2ljb25zLW91dGxpbmUtMDIuc3Zn/////wAAAAIAAABhUBVQUVQAQUBBVRARAFQBUFQRFVUABAUBFAFUVFEVAAUVEAEVFAVBABVFBVAAFQQEUQUQQAQFRQQEREFEQAVUFBRQQAEEUVUQEBRAAEFVRQAUVVBBQFRUBFERAVRQVBRAAAAAAAA=";

const chunks = {
  "heroicons-outline-01.svg": new URL("./heroicons-outline-01.svg", import.meta.url).href,
  "heroicons-outline-02.svg": new URL("./heroicons-outline-02.svg", import.meta.url).href
};

register('heroicons-outline', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
