
import { register } from '../core.js';

const lookup = "AAACKIkZAY0YUBpZ0ROvWChVZ3eHZEQ0NFS2VkcnghhFVHJjZGNkZxJ5MydUaFIyR0V0dDVWKGM3WFQPJ6QBxwIGRYgDBE4EGhwBDQgFabW2Ay0THwEmAQGfAlIBCANfugEBiQIBCwIrCTlsBAL6BtYBCEAOEKkJKQcDEwEsDQr+AQFuBgEgAssBBROWAQECWQGN5QTwi9jDjd7o2TN2W33DuSnvQ/8CdAAHmxcmWJDolqaVAJzFgIdc2TRRaqEGtiirWTDO5SrArWS+Z7TuPxqOkJOafqFGDoJEkdfTUS19iFHGtGPH1lcV3//MJQilM1pw71a39AD+OlmMcLZTL8zKkc/gtmBL69Mv0SSOQrxAe23/a2EupgBjY66SZgKhQRIASQosdh7cjFV3NLSJvNHIp60Xo/sp6RxBfgn/PuKCwrr9FGIppS4TMEyffUWTGuijpBM5OGCh9XIEW0mnitwy8aotzCbSnykKMfK3ojv4zXZ31qVdtoYKkMdBgpHRKOa2jVOYFwdFBGI10EUFm0nB94+yBlQy4GXftMkk3ODGIOdfuj2wYIN3YFNUz9ySzei60Ui6Vz0isdi7abKSP+lS39XwjWTAkYmPAVnzXrO9QextVicjU6e6kDwarfd+neeg5JKGW5lEBFb2hlD0On/obFfUIKYASA5G6W+teh4gN8dAMwXgO1We54jZwSmEHEeEDZeZMqSUQHpkQjT5FkoBgAAgBIAoJAAIAAAAAAIAAAASc2tpbGwtaWNvbnMtMDEuc3ZnAAAAEnNraWxsLWljb25zLTAyLnN2Z/////8AAAACAAAAZBAEQARQRVQURQAVQEFAREUABQFBFARUBEQFFVVEERERABUBEQBVVBFVRVBEEFFFREBFUQUFFRAEUQRQQAREFQQEFVFRARFAEVEVAEVURURVQAUQEQUEUBEEFERVAFERBBVBQAEAAAAA";

const chunks = {
  "skill-icons-01.svg": new URL("./skill-icons-01.svg", import.meta.url).href,
  "skill-icons-02.svg": new URL("./skill-icons-02.svg", import.meta.url).href
};

register('skill-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
