
import { register } from '../core.js';

const lookup = "AAACKYkZAY0YUBqxEsNRWChnGzY1ciQhZWhTZFM1MkOoR4RIiYYzQ2U0hGaVIwRFQ3RVVVVHWGY4WFXAAS3+US0DBgwB3gEFAggGhAI3BxQtCgQHQgEFhAd1WwkKhQSgBgG3Gs0BIPYEAgMDAS0cFAgC/wJpCwfEAgIVFgEKBdcBBXABKx4KJQH3BA4fflgDAlkBjdGmoY12VQCwfbbW8ARmieIcPgUmCt7QY0JD9tx6tqoEniflo8K6/2DTSEg67m1FNGtGQIYKBAdighoUQC4Ad+b7kPe2fjXoW4Iz03Z6yrG6AH33VPGNpojp2cD/myjGZKSmlvhWq4zrzxce6KUX5BpFLwkajyRUcDBRzP/1vSPpn/OCU0QyKtUpJFs8jmrw4N9ZPxM5/pEIjkmNw+eSvofZPZE6336SKItyFbcBlUWhUKCGE1dgM21s6MDRtK2tMn2TtPlGd9i7kNilRCxvQGX0QV+AfwbRXrY9F5G2Y5vWW1JnzEFWHgo08lc0YrqS1+jolO/MZFmYAAfOforRj+UmpTBashattNzNdOlWWFE7yYaDxt8zp9y3yM1LYJCZP/8ODgb0zwVpe9K6OKQvIBJThKH9JXZV1Dcp71m5Y7NgU9xT4OfHvDEul2Eco1wAn8PgmQCiIryExUmnkl13cJMpKcfHQkGaobTsO8GJIC2uMmSIQVENrUeRjKfnAuACICmcnS3ZugTBSUxXspBKCBgADgAAAA4AAAAAAAACAAAAEnNraWxsLWljb25zLTAxLnN2ZwAAABJza2lsbC1pY29ucy0wMi5zdmf/////AAAAAgAAAGQAAEAQBVBEEUEUUBEEUAQUQQRRFQAQUEBRFFQQRUAQVFEBBRQRVBUFFAQEVFEFBFVRABBEFVBRBBARUREBEQFVFQVRVQBERUUUAUVAEVFFUEQRBFEVFBUFEAAFVBQFVVRAVAQAAAAAAA==";

const chunks = {
  "skill-icons-01.svg": new URL("./skill-icons-01.svg", import.meta.url).href,
  "skill-icons-02.svg": new URL("./skill-icons-02.svg", import.meta.url).href
};

register('skill-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
