
import { register } from '../core.js';

const lookup = "AAACJ4kZAY0YUBpvdhQKWChXRHO4VXN0gkZFJEhxd0UmdUglYzJEZ2JjWnZTWFJlZzMbZSdVMzQlWFOJAR8hCpEDuAiVAisYBJ8CCWlkWAcJCQviAgpLjAEGIAVhB3qjAQoRBxAuAQEEFAmFAgMo1RIx6AGwBgM3ywMHCgimAwMB7nsQMY0BCQICBQoBKQJZAY1Jgul9kUYXpUn/3BfohiqhaTpWVXcz72O6Vib/80D3UijuBKbvQZC2p8HKtgqQiyOyAK26LqQcbOdyL1tj+fcIUa0Tz2TBZxYczuRHnPS9/ylmDrShsobxKTiGUG0Nxdw0MNdF06WSRJK6zElcJH0+MIDnB+VfrehBxjfR0i3regbgKdi63twxkcDJ3/I0J7NE2KYzPZpTdpLWmchX0Rp+6GA7MpL+IKAJ4D9/QdEmcPi2Xp89h0WELENUhIIugv/g6VVaANAKBIkpa8ClRVO2o8O5u2DorbTCx5bosIPPQTJ+BDqkUW2MAEiiAsZgsYrcVyKbm7T9vlRkkACVGiWme5FWl6dYvKPwiR4AtzX0x6edzUJ9Y6EGtARX2WUyd1uQmJMgjFkCrqEFzAFTiDxwbw5TKJPi1hrN1RXRLTsg9reZwzmRfuee2fWPKeXTx3QKiHqO32J2+xJCF1HwjQVIB+y6RiSfXdk/FB5gWeA01Lyrj2RbjXdq5unMWZSqtt+NL44zYRNLTGIAQEB2SghAIIEAQQAUioAAAAAAAgAAABJza2lsbC1pY29ucy0wMS5zdmcAAAASc2tpbGwtaWNvbnMtMDIuc3Zn/////wAAAAIAAABkAVURRBBBAQAEBFVAERAFRQBREFQRAERURQQRRBBVEEUEEQVEERFQBRAFFBFVEARRFUUEBAVFUABFRUBUFQQAFUVVVVUAEQERQUUQQQVAQBEAUQBEVERRQQUUUUFVQARERVQFAQAAAAA=";

const chunks = {
  "skill-icons-01.svg": new URL("./skill-icons-01.svg", import.meta.url).href,
  "skill-icons-02.svg": new URL("./skill-icons-02.svg", import.meta.url).href
};

register('skill-icons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
