
import { register } from '../core.js';

const lookup = "AAACaokZAcIYWhrHID79WC1UZGaFVRZVYmRkdDVjeKdlkjRlVUNUZnZEUiN5VYZURiM2VkE1YVU2ZTZUl2ZYWgEDF381Fzy6ASwXDwQSAwwRbRlvEMsBDwgliQE0SIQBCAcBugkdGg4LEAOKAXcFKQcBBAMBpgKCATsEYHINHB8jARgFdDYfE/4BEAGHAQINGF0LAhcKORjiAQJZAcIOoA6+MP+0v5fSCCQpRISCkhXtib445RM98afoaXk7t7LoyC1MUGoutQKqDjtZbu87AmQHVCgvuWgGW6MZvyyfhMr4+HoMJIi13OxXMH3Im44HGuE9E78QuhYvI0rt71sp9PwqtlFAUVYAvLBueCeMdXE2Rwhu22FDoPReVocFZ+zZz0s8wL2KrOmzYaT/F4h+DZ2yuP64dl/VfkMrf8GLsO5Et4vLB/fo/HxjxZ6a0ty++rhuKtjSokBxDvRRqQhOJMFQN5bXA2T7FWRkt6ssDp5QE+wbtBUk2SLdMzGrev1/tIecsm1MrE5ng7WinI31FKJQ1tiVia59YbCLR3dukmX0Y0DwHf/X3zwByX0BT2K9FghUdBTM+mk1hKzKEDiLOI+MXyiZmdAafiAhRw0cOOK3HhXK9Qicpzv2N6BGaVA1qJBMgJtSrCAmpjUWWwsoJ9YVDH5yKTDmvXkIqwQ+9gs62ifL0tSem6lNLF9ptPiUNKbgodXS6dzp5P0Q8l3OMRSRAYcWHmzspF6RxR8KCfyPBjhq9VPunHorqJGMDPWpLKmhXqtZ4PwKcOs5SVa/sSis3hZsXI3vvfV/WcC3nyZMAAiAAJgBAgBCBgAAAAAAAAMAAAAQbWV0ZW9jb25zLTAxLnN2ZwAAABBtZXRlb2NvbnMtMDIuc3ZnAAAAEG1ldGVvY29ucy0wMy5zdmf/////AAAAAgAAAHEEJKZUBQQBBUGBBRBAgRBEBUYEAUVFRVlRFFFZVEFBVVCVSmBZkVRAQEElEEBQQBUSFRFRVAAKglBFlFRBEQEVUBCAACVGkWQJARaBGlFUVAEAURkVEAQJURaARKFVRAWAkRBQmRQpURFgAIGKFRZQAAAAAAA=";

const chunks = {
  "meteocons-01.svg": new URL("./meteocons-01.svg", import.meta.url).href,
  "meteocons-02.svg": new URL("./meteocons-02.svg", import.meta.url).href,
  "meteocons-03.svg": new URL("./meteocons-03.svg", import.meta.url).href
};

register('meteocons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
