
import { register } from '../core.js';

const lookup = "AAACeokZAcwYXBplGqUNWC5GZ0YUc1UTN1mBJXhnQ5NRZSZDNnVGZWOUKBVUV1RoYUhnMThkKIhVWhRlQ6RkWF8VA/4EDQ0MDgKRAQYbAbgBA/sdRQ8HB50EDDAHBLoCDA4aEwEOBV0EAasDIgkQSgUoM7oFMAJcCQiCAQcBsgKMARqAAa0CCAaGAQMDIzABED80RCQdCAdlCg4Slg4UTQJZAcxTvJaWpLX0RQM8ZnAeUe1+RnicnxK28gGvonVczq0XiLKArhBv31sZWsvOtZejGJiIH7LCeVG8Wv2xac5A2AukoWa6Kngh9DBPrZidcv53wzQEAARc6Sovbx5H6AzGKhuMRCZFPPuPlxJV7vhYu208jjqGf/aEo2dyr/AVl65fYJjYkVzyUKR6FdA0EQ+ng4gQsNFTj1EFMbltJMYPSNcVb/ZYQBuIduzxG4HTxp9k4usfw2rXyygQ7oGJdvxB2BKO8pJdNtisw3vuVvNlzs3nykDnybCJV7Z3rCFhma5JgpQ8MOiPdba4outCbA63YKa1uSO7HxPCcTFbjYkSIdGctFKO8sE690LF6aF0SPciULOyC1PLV7fZb5vQx7ft7vm95dRdyO1Xm2f9PX8SQal2Eaut0NG+ejiDZYZz2kbmeTz2o1G2fKwiXICh3S4BQR2r62Dfox88sgbjrZQ9w6si535CEE0/apOyQWUJ4jGHm8JD+WHj5lHc1uJsh8/rZSqladA6c0BxXpslJ6G1QT6d3oudRjlEiTLJiG3kypRHypETwQg5X9D9qU7MrbtI9qfNjALtNm0q27GRlJCDpMKDS8/CIyoO71Eo5rJITIAgBEwAACBIEgAIAAAAAAADAAAAEGZhLWJyYW5kcy0wMS5zdmcAAAAQZmEtYnJhbmRzLTAyLnN2ZwAAABBmYS1icmFuZHMtMDMuc3Zn/////wAAAAIAAABzFBIQAVZkFgoUgFYFmJVFohWBCQgQREUACmYRRBGJAVhAEYRBFRQIhZRAVWlRBAWAZFBlUWQBGVJVGkESAGGRVRFEWAUARGFEmRBChFQEBFAUlEUVhQBhBFRBQUllBCBEUEWBkRBEBUVWEFEQFACJFgBFZAAAAAA=";

const chunks = {
  "fa-brands-01.svg": new URL("./fa-brands-01.svg", import.meta.url).href,
  "fa-brands-02.svg": new URL("./fa-brands-02.svg", import.meta.url).href,
  "fa-brands-03.svg": new URL("./fa-brands-03.svg", import.meta.url).href
};

register('fa-brands', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
