
import { register } from '../core.js';

const lookup = "AAAC5YkZAh8YbRp6fb8lWDckMnlzR1k0RHaCdHgTIzVCRVSXc2ZadkFEZkWGdUZjRbWCRSNYUUIqZVVmRkMhZkozZGYzOsQDWGwBC5ETkAEGCKgBCPQIAg4JBAw1AaAIASLlAYABBAIgAQEGER4DKu4CASYS0QEQCwIPAwIJCQQIG5cCBsICahAElwEDB+0DBpgCDAEBE/sDA00BFh2iASIOAgIUAdYKBQkGP4EBCKcFBBD+XggCWQIfH0pI6yUy0FME6S0vJrEL17r4OMbYEkFMwebP3X92qTsDVmQQ+cnR63WmTARj4B1BDtRvTYbZrR04YIGvyHkw1JfQt7uBnIydVH2sEsLC/AeFDUUQYYCE1wirsLX2qI8er+NDRSX574Rr7lPmr1byBZ6zDIgt3UU38Guy+RklA4bRfxr5Bej+vEWthOhBQgqFUtY9IhM42yfdmpkEuTKqzk3kMi4EqyHen3cwP8wPsWBApV4ChqTMjS75/IeO6+LUFJhsOPJMRomgd0d3EdIc4et7UTtkxx011wRcyessDTWTNIx1QA934Glcjgea1ZQMIE32gaX7AbA8B7OKeTVaHXCfMb94OUtELYFLoVILNDe0g/DNgCnYXx1acp1tS8NqUlQuC7nJMcEYGwr3tmKAZHOjT9seoJBc4vhlswJHr1M9hihDWj4TxU/xJoMc8xnvl7rFF/aO7BKZzXr6tGg6zDIYErkc7JwQqYgZazQifv8wjfCfSyuF+UYpfu3mwb4+Wxsh1hy87MDRj9kZCHeqqb/i7pcw5oQRhnDq7mTDUJoBk1Y7Z/u+ySHzTh3CNqJX5urOgG3utzjXlaELEMMbg9HNb/VLC7clshRVyfNudLYi51SL6HlnU+y/2LOBmT1se4vaizbAsFxNxhMPQuPiDh62HjqRKwh+qP58PqobWw/jzc8IsdZVgZZ1Dee9bBt3IC8IfkP1bfm+TaLtSOzMTgMgAAZIQAAA14QAhsAAAAAAAAMAAAANdGVtYWtpLTAxLnN2ZwAAAA10ZW1ha2ktMDIuc3ZnAAAADXRlbWFraS0wMy5zdmf/////AAAAAgAAAIgBAYahSQUkSRCGRKQQaEhhCBQZiYlWAGlmQlZKIRJmBIGUZkaVQYlQKhYSBQVZERWEZmEGVQFFChpYgqZFAqqBQFmWJkmpSiBAWFWEVVkVWhQFEBmKIIplQmhQUQgQAoESIlqkSBZIBYFkIIFpEECIJEJWBBhSYGRIWagFGGVVIIJaEBKAlUoFAAAAAA==";

const chunks = {
  "temaki-01.svg": new URL("./temaki-01.svg", import.meta.url).href,
  "temaki-02.svg": new URL("./temaki-02.svg", import.meta.url).href,
  "temaki-03.svg": new URL("./temaki-03.svg", import.meta.url).href
};

register('temaki', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
