
import { register } from '../core.js';

const lookup = "AAAC54kZAh8YbRqLd6GdWDdRZRRhQlR5VWdFKmRVc6NYVmlVUXI0ZCVieDZ3dERHYzNGdVU0NRVSR0c3V3UoF0VxqUVmN4QEWG4RDkwKIwENHBTABbgDCwZLUQkCsSoDAS0IFgM2A6QYyAI+vAEUPRwSDA9GBwIKEgUezQSnAlQCMb4BCFUFdC4PQwQD0QQQDiEBCwM3GE4DJBDGAgNCCDOqAoEBAlgZGxYI6E8vDnICvQEBE80DAwJZAh/zEw+OLVE7C24ZGTRO8rc5/O86pXce5zeaHR/V3YaMslus6yD1AUE9ZB1CBLcM+RwSZNH8lwV3XFpHfoRhfYtLMLEd9jGGhSlSkxEIdSV0IQjm7fiGEpG7MPBMnBBSvkrJ2BQ4jvDm5DA+r2cdb8UeucwURTuoA4R14O6BQUWHVB2515fOtx3mzatqNIkyXPl5r7x6JmPsQxtrO6lFn2DXLwgEZdQESyDNG1VTWzAZw/twviWNmgrsxq3WTYvutZ2kuqLJi7PPfEZoKdtLs6/YwISB+cxVyM0yArzt4tbzgfgvT8l2kJyXGy1aC+NUYDj/1gfUSIBSiEPFVk+/GT4Q6L3QsFwY2W2P3eLzjxLHDD9wk1e2TQtscn9N5hHMjIifgyae64aUUw9B4FYKse/YGzjimh6h7DFDQHmwquOlc23rCNEiB+Hd9RB5TUVkCOkOqZnPLfaV/sYHODYNmeM+zCFnMoqDHIQFyT1++Rqzmfqj14Xbd/aguTVeEB73jsOxU6hNtM3oa1MXGNANe77D4sKqD/klAoDCG366ySx18FqFHO5rLlz5wI3RJ7/q2l+fAYatEoGhBDZMVvJGJW3x+6n+zq/oNYGyTCveQOa2tgRpC6LsqyjR7J0TNxOqmDi/LutsgCvZ6qDBS9KBNOtQ+TIiCy6AwktUA6Z3DpYPREK0bIN/1yF+PD3UOmTBHCINYm/BR7NId3fuNed7eLBOYQAAAECBAUQDYAAgAQAAAAAAAwAAAA10ZW1ha2ktMDEuc3ZnAAAADXRlbWFraS0wMi5zdmcAAAANdGVtYWtpLTAzLnN2Z/////8AAAACAAAAiCZURZJAJVqQVqGRqEUBSaoqEKFElBFaIBmQVEUERRREkGKFkQghJAlQBBWWqZkFAYZoJqAWlCBKWSZIpmUkIhQqIRKCoEhgFFhmGkAAYRVkYUgISghCCpaFipWAZlFBlGSRGUQlJJUJFoFIiYSggQZQRQKEKpEkFBAVUihJZVBQBUWChSVWBBQAAAAA";

const chunks = {
  "temaki-01.svg": new URL("./temaki-01.svg", import.meta.url).href,
  "temaki-02.svg": new URL("./temaki-02.svg", import.meta.url).href,
  "temaki-03.svg": new URL("./temaki-03.svg", import.meta.url).href
};

register('temaki', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
