
import { register } from '../core.js';

const lookup = "AAABxYkZAUIYQRqvPeofWCFDVHplI2cnU3dDI2VkZ1UXRXJTZ1B1RoQkRSVkd3Z3NgVYRAYSDSWcEqsCQi8CWF6FBAcZLAwEBSUOA1GCA4YCASJXCQcBJwIEiQUCCxjABBEBB/oEBA0acwG1AXI+DG+MAYUDCQMTAlkBQq3tNY15bM+5fmBfSTg5y4t39qhoxIKbQZcYv51EUDUA5iRQgUe7npKNwcaS5YIttRFgvOIz5i5BHxEoiI1/JpRIrof9edObD+YqwWwZLxhtcAakaeLXGwB54ibMAdVv+SjctE4BGNzpxPeMoX4cCqxhJf2psqV4hkytKWJsEcgBLDUkAJ9gMYCKlht/A4ys92VcBcmL9xKUMruwc3qrmGPRTkc0/4ejnX5yX3NLHoi9YF0pYVR1a6hEZhaj8r7BWEEk6Xt6vh6UcjBk8hbxpiChVIftzRpowQNTMBv0RgIUZ85E2jAyMHiV5bkJwS59w3OC7VcNZqylNX0dq5lVANdobYN6WaBwv1KVIEBtsFOWCYRwn9Op5Ey6gRI2vrn+sZrR3RUsP7SESrgPu/lqOVA/OwOWEfsvPtJgUmBNInFrtipJAGIggAABIgAAAAAAAAIAAAAQd29yZHByZXNzLTAxLnN2ZwAAABB3b3JkcHJlc3MtMDIuc3Zn/////wAAAAIAAABRRAQFQEAABUEAFBVQAQBREQEUBBRRFRFUEFAQABAEFRAEEQAAAFUBAAAVBEEVFEUVEBAEEEABAAAVQBQFFFRAEAAAUFBQUFUFAUBBQAAFEEEBAAAAAA==";

const chunks = {
  "wordpress-01.svg": new URL("./wordpress-01.svg", import.meta.url).href,
  "wordpress-02.svg": new URL("./wordpress-02.svg", import.meta.url).href
};

register('wordpress', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
