
import { register } from '../core.js';

const lookup = "AAABwIkZAUIYQRqfri32WCGbNyMnRcVCZXU0h1VIY2Y1I2dVZUE1pGU1VFI0M5glQwVYP9MQhAwi1gIDLRcPpi4CGRwEBCsJxQL8Ayl9AwsBbQEBCAECtgIpbC5EDWgDApAdFBQbBBQCFwQIBNoEowkPIAJZAUIACWBUaVXImz/96V9oQBi/gm0k4uYaJIc0gqu03Z8REagA5URwclcwJn/NhjJ5SGx9y8HMbWC/nQGC00yhD7IFOT7t/4wy5SKIzv5duVMgYvfVLHN94pUDxn9QDymwuNqUG3ljEY11JYRHrIftuyxoVGVBuY3yjU3Bm3f7S/eXTAEkKqFZewERarww04sebfk75HodA+nmNSmj7WCfgR7cJsGeNat6WDj0lgrRYL41jHHSNWaWG2thli+0YMHmawm2U63XUrpJUr39gGcvvq1EUKUwsE5KZi32LrGZyWwcGKV5Fn6jREFQRw2d+ZKYlACS18FOc5qm0QIgFLvigaD3hyhGAEGpuRaDqHBgFWHDGXiEMBKVLh/Ebz8YcChkX74xu3gz8lwGi/ESA9ysOXMbiHpslIoqpLWuaH6sfqnENs9ySTgARAAAA4LgAAAAAAACAAAAEHdvcmRwcmVzcy0wMS5zdmcAAAAQd29yZHByZXNzLTAyLnN2Z/////8AAAACAAAAURARFARAAAREUAURFRAAUABQAEQUBAABAQQVEUVAUUVVAAAAQQREFRUVAQREQBBQEFFEQUEVVAREAQUAQAAUQABFEAAAQRBRQAFBRABBVABBAAAAAAA=";

const chunks = {
  "wordpress-01.svg": new URL("./wordpress-01.svg", import.meta.url).href,
  "wordpress-02.svg": new URL("./wordpress-02.svg", import.meta.url).href
};

register('wordpress', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
