
import { register } from '../core.js';

const lookup = "AAAB4YkZAVkYRRq17KOqWCNjRHJCcmV2NEaHUnFWVStjUoVGRGJUQ5ZVZXRXFEhmVnY3BlhHASgeDyABAs8BBgGoAQYFCT4fhAGaAQFMmwEJDAjgBQFSAhkMEAgTAgIbaQIBWaARDgYVUx3VAQYFA+wBB8ABLx4nYmkeA2YCWQFZdx2o7S4WfTP28eb0VNKE4rlpYl0rJTEH913aHgsxXxC5oC1eap+2MPchq/keJ0SjkvVuauspHBS7dDsieD2aF9O/ZY0Ku70DbcEbZH0MFbZoVDfSe4lkdi4fJWKVn6eA5pwF8uOlMCBiyFVCcbszGLtYSvzch1GNU+guYLXw6l1ZR02aRBtrqPBnvI04tQVhGBlStOzJFANebuHpfu646h6/ErKWrJOYYL797QLX8Dm8psXY7COtMZveZeLLdYisG7qk1/hrlg3PTLmyuTUqAgNgUQrZ/WFej6vaLFQmKY7sXuf6zksbtXOSOyMP5vvE8JmSn9wDniE15jnQ7cCv8xtSi6E8Qa29+AElMVap8/C2Y74NmPPDK/EhbU1SLsESEd8mRnAjh2tbig7LQflNl+5gcKF+F6oPaQxfihoxvPJ2/GMAvsitAGshulCrtr3WP5r4guzWNtI1SRABQCEBBAACAAAAAAACAAAAEGRhc2hpY29ucy0wMS5zdmcAAAAQZGFzaGljb25zLTAyLnN2Z/////8AAAACAAAAVxUAUBVRARRAQQAFVURAAVUAVBBEARABQARFQQBRVUBABBFUBFUEUAAVBREFBAUABBAUEBUQAUBFBEREVFQAAUBFEEAEAAAEUVBFVQFEEUBAAUUUAQEBAQAAAAA=";

const chunks = {
  "dashicons-01.svg": new URL("./dashicons-01.svg", import.meta.url).href,
  "dashicons-02.svg": new URL("./dashicons-02.svg", import.meta.url).href
};

register('dashicons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
