
import { register } from '../core.js';

const lookup = "AAAB44kZAVkYRRqdULEFWCNYdVYkRVVjNXQ2RGRTdoVkRBN2JlREdCp0ZWaGVVeDNjZEBVhJewgCjAVDCQMCCig/CQMQLQoLQDIKGwgEHwIBI6YBAtMCBJ0BCgL8AWMSChwXBxYE+woDjwIPMzYcLtwGTh9hEgs0nQFvAgMGCgJZAVkaYRGsYPYe3MstaC5eI+f7j3bE+WLmeyNd9E0wHEGI8JdkIZIwXmMxVNZYAUfIK628+iIQfc9ijv25G2CHJbZ2Cmomu6+NcKbcOOKjcwJUK2QPTFu54g9+45L37F34uZjYGZ4x7XXpOR6bhB8jyL8hUyeoq2XXwUo/a7Wta23qHUES5mDzu/NSFWPXivw7G8kDGDX3DRRqA/GnG0JxO3hgsqsDViaCKeZtXwzShxcXCpLsmrvugBgqpDHBbr5iIa3LuruYLmsbtr4HdE22tSzWqgV9FJ8NpcAgDPwb8As2bvC1oZXtWeZEZdq92gPZMew3v949zvK9UTP4q5wuLg5rd0bSMR5pAHAlNVKhqehh9SES7rbq8MW4ibzQKZ9+86heijy8M1Cf0pPfTY3saTlVBZlEXfGsFrSWjb3hufK6oF+WZ7IlNe0CmsP5XtNUS774/ZpR61KL8ABJAAAAAImAAIAAAAAAAAIAAAAQZGFzaGljb25zLTAxLnN2ZwAAABBkYXNoaWNvbnMtMDIuc3Zn/////wAAAAIAAABXAEAQRRBFBQAUBAAFQEBFUFRUQFBAQQURRBQRURREFUBFUEBBVARAUABBABFFRBFUFRQBFAEQRQAQQAQFQEBQUQURVEEEAAQBBEBAAVREUQUURAEUQAQAAAAAAA==";

const chunks = {
  "dashicons-01.svg": new URL("./dashicons-01.svg", import.meta.url).href,
  "dashicons-02.svg": new URL("./dashicons-02.svg", import.meta.url).href
};

register('dashicons', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
