
import { register } from '../core.js';

const lookup = "AAACKokZAZAYUBrbcioGWChFYzUmdlJGZHWDQ4N1c0Q1KFZiJEI2VXdUKYclNVhkUYW4VjY2ZDN6WFM2BysfAzcDD50GBAwoGRhiBCa6AQMCBG4QgAEC1AE2AhsBvAIRDgEPIAIBHQYSkQIxAgvBE3rjAiAVAkELCwI5AccGggLSWEAiIAMRDiQCBOUUNQJZAZAJzx7IDkm7tf8sBnq0Fr2xBfBNOmmWz9LmsWepEPYiR41MCttceSeMrKbMTnHMVVSdkx0dtwsxVu9YQavJNHl6HSfwJDVZJ9/bDzbDar65KJq1sHFG6txKTctTwB2sQyWbdZPdHNkVuVEdUUeSsb9UQz6krC0jWniUqMR68KIm9A9NXyZ99c0a8UOGDZ+oCyXX0SbyXaYWMtrpe8Dubc8lej77nBhzQzE76t9Fi0xvag+fRRhTjMhc+PQSDC98WVpQKWsPKqH1f+YebQfH4RMDaPvU2JxTEPdukTEKtYFMeW6ncqBli3BUd9FcWNqizdPJJ5Db6QPAxNeu7WLgJgAPu+lwncEjFux04DYSyOgz1oRxtCeto7Kswgr11q/oQnL5YWBP9dR/MB+TzIr/hF60zKAJjdVBcuUc+wTbRFs5UQzbdjRUZTYXMCQpOeiGVpbitufYlv7XTzJjr0GJrVw+Bvo/hNTeWF3mOBUoJvhhk6LpjHNLqoZUhJeSPMrlrVd9S20zYVGi5cXLcokNcEVvSgQABAACIohAAAIAAAAAAgAAACBzdHJlYW1saW5lLWthbWVsZW9uLWNvbG9yLTAxLnN2ZwAAACBzdHJlYW1saW5lLWthbWVsZW9uLWNvbG9yLTAyLnN2Z/////8AAAACAAAAZEBAVAEEEBAVFURARURABAFVUVAAQUUVBVEBEFQQQBFUVFFRBBREBFRRRFVAEAUAQEBEEBVRQAVRVRAEBFEBRUAVFBEUQVUEBUBUUUEVBEBQVRVAVBFBAUBEUBBERERQVVBUQQUAAAAA";

const chunks = {
  "streamline-kameleon-color-01.svg": new URL("./streamline-kameleon-color-01.svg", import.meta.url).href,
  "streamline-kameleon-color-02.svg": new URL("./streamline-kameleon-color-02.svg", import.meta.url).href
};

register('streamline-kameleon-color', {
  lookup,
  chunks,
  baseUrl: import.meta.url
});
